### ISSUE TITLE
ShowHiddenColumnsAsDetails don't work

### ISSUE THREAD

**Issue by JujuPomme** [atatanasov/gijgo#10]
Hey,

I copy this example : https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.ResponsiveDesign.showHiddenColumnsAsDetails.sample.html

for the hidden columns but it doesn't work. Moreover, only one rows is displayed when I put the option 'showHiddenColumnsAsDetails: true'.

Here's my code : 

$(document).ready(function () {
    var data, grid, dialog;
	
	
     function Delete(e) {
         if (confirm('Are you sure?')) {
             grid.removeRow(e.data.id);
         }
     }
	
	
    data = [
        { 'ID': 1, 'Nom': 'Hristoezfezfez', 'Prénom': ' Ménage', 'Téléphone': '0606060606', 'Portable': '0000000000', 'Email': 'menage@email.fr', 'Fonction': 'Femme de ménage' },
		{ 'ID': 2, 'Nom': 'Hrizadzdazsto', 'Prénom': ' Directeur', 'Téléphone': '0707070707', 'Portable': '0101010101', 'Email': 'directeur@email.fr', 'Fonction': 'Directeur' },
		{ 'ID': 3, 'Nom': 'Hristo', 'Prénom': ' Hot line', 'Téléphone': '0808080808', 'Portable': '0202020202', 'Email': 'hot-line@email.fr', 'Fonction': 'Hot line' },
		{ 'ID': 4, 'Nom': 'Hristo', 'Prénom': ' Direction', 'Téléphone': '0909090909', 'Portable': '0303030303', 'Email': 'direction@email.fr', 'Fonction': 'Direction' },
		{ 'ID': 5, 'Nom': 'Hristo', 'Prénom': ' Secrétariat', 'Téléphone': '0101010101', 'Portable': '0404040404', 'Email': 'secretariat@email.fr', 'Fonction': 'Secrétariat' },
		{ 'ID': 5, 'Nom': 'Hristo', 'Prénom': ' Secrétariat', 'Téléphone': '0101010101', 'Portable': '0404040404', 'Email': 'secretariat@email.fr', 'Fonction': 'Secrétariat' }
    ];
  
    grid = $('#grid').grid({
		dataSource: data,
        detailTemplate: '<div class="row"></div>',
		responsive: true,
        //showHiddenColumnsAsDetails: true,
		uiLibrary: 'bootstrap',
        columns: [
            { field: 'ID', width: 32 },
            { field: 'Nom' },
            { field: 'Prénom', title: 'Prénom', priority: 1 },
            { field: 'Téléphone', title: 'Téléphone', priority: 2 },
            { field: 'Portable', title: 'Portable', priority: 3 },
            { field: 'Email', title: 'Email', priority: 4 },
            { field: 'Fonction', title: 'Fonction carte de visite' },
             { title: '', width: 60, align: 'center', tmpl: 'Delete', events: { 'click': Delete } }
        ]
    });
grid.on('detailExpand', function (e, $detailWrapper, record) {
         $detailWrapper.empty().append('<b>&nbsp;&nbsp;Place Of Birth:</b> ' + record.Nom);
     });
	 grid.on('detailCollapse', function (e, $detailWrapper, record) {
         $detailWrapper.empty();
         alert('detailCollapse is fired.');
     });
 $('#btnAdd').on('click', function () {
         grid.addRow({ 'ID': grid.count() + 1, 'Nom': 'Le test', 'Prénom': 'Test City, Test Country' });
     });
});

Any idea?

Thanks,

**Comment by JujuPomme** [comment]
Is this plugin dead?

**Comment by atatanasov** [comment]
Juju,

The functions assigned to the detailCollapse and detailExpand events clear the content in the details section by the $detailWrapper.empty() command and that's why you can see only one row in the details section.

I think that would be best if you use the showHiddenColumnsAsDetails configuration setting without clearing the detail section through the detailExpand event.

You can see a working example at http://gijgo.com/Temp/81e25198-6afb-4102-b437-73a7affec7ab.html
