### ISSUE TITLE
CheckAll and UncheckAll  functionality not working

### ISSUE THREAD

**Issue by csharpdocs** [atatanasov/gijgo#102]
Hi Team,

Today i took new version v1.4.0 and found that the CheckAll and UncheckAll  functionality is not working.
Previous version v1.3.0 was working fine.

Error: TypeError: $checkAllBoxes.checkbox is not a function

![gijgo grid checkbox issue](https://user-images.githubusercontent.com/28830016/27516245-be9915c2-59d3-11e7-8a14-f3ceae3f162c.png)

My Code is as below:

grid = $("#userGrid").grid({
        primaryKey: "Id",
        dataSource: userGetAll,
        uiLibrary: "bootstrap",
        selectionMethod: 'checkbox',
        selectionType: 'multiple',
        notFoundText: 'No users found.',
        columns: [
            { field: "Id", width: 50, sortable: true },
            { field: "FirstName", title: "First Name", sortable: true },
            { field: "LastName", title: "Last Name", sortable: true },
            { field: "Email", title: "Email", sortable: true },
            { title: "", field: "Edit", width: 34, type: "icon", icon: "glyphicon glyphicon-pencil", tooltip: "Edit", events: { "click": Edit } },
            { title: "", field: "Delete", width: 34, type: "icon", icon: "glyphicon glyphicon-trash", tooltip: "Delete", events: { "click": deleteEmployee } }
        ],
        pager: { enable: true, limit: 10, sizes: [10, 20, 25, 50, 75, 100] }
    });

**Comment by atatanasov** [comment]
If you use our modular build you also need to include checkbox.js and checkbox.css in this case in order to fix it. You can see an examples at http://gijgo.com/LiveEdit/Index/grid.Base.selectAll.sample.html

**Comment by csharpdocs** [comment]
Thanks it worked!!
But i observed another defect that all checkboxes except master are checked(ideally the master also need to be checked) and if i use grid.getSelections() then i am getting nothing.

If i check the master and again uncheck master and then check master then it works.. Plz try.

![image](https://user-images.githubusercontent.com/28830016/27518279-bacf5944-59f9-11e7-93b9-3c99bc982df9.png)

![image](https://user-images.githubusercontent.com/28830016/27518284-d2f2edec-59f9-11e7-8852-ac87fb37528f.png)

**Comment by csharpdocs** [comment]
even i change page next, previous issue persists
