### ISSUE TITLE
Grid Inline Editing - renderer template adding again and again

### ISSUE THREAD

**Issue by csharpdocs** [atatanasov/gijgo#103]
Hi,

To achieve inline editing functionality i used renderer templates with Edit, Save and Delete functionality.
If i edit and save it works but if i change page(next, previous) and sort then it again and again adds renderer  templates

Snapshots:

![gijgo grid renderer 1](https://user-images.githubusercontent.com/28830016/27516307-3b81d96a-59d5-11e7-8598-0d40ab9c5b7e.png)

![gijgo grid renderer 2](https://user-images.githubusercontent.com/28830016/27516310-45fea7d8-59d5-11e7-80f1-9c60eeab47e9.png)

![gijgo grid renderer 3](https://user-images.githubusercontent.com/28830016/27516312-4e7e7bf4-59d5-11e7-9885-7eb98fd232a8.png)

My Source Code

var grid, actionTemplate;

function LoadGrid()
{
    grid = $("#salutationGrid").grid({
        primaryKey: "Id",
        dataSource: salutationGetAll,
        uiLibrary: "bootstrap",
        inlineEditing: { mode: 'command', managementColumn: false },
        notFoundText: 'No salutations found.',
        columns: [
            { field: "Id", width: 50, sortable: true },
            { field: "Name", title: "Name", sortable: true, editor: true },
            { title: "Action", width: 70, align: 'center', renderer: actionTemplate }
        ],
        pager: { enable: true, limit: 10, sizes: [10, 20, 25, 50, 75, 100] }
    });
}

actionTemplate = function (value, record, $cell, $displayEl, id) {
    
    var $editBtn = $('<div title="Edit" class="glyphicon glyphicon-pencil gj-cursor-pointer" data-key="' + id + '"></div>');
    var $updateBtn = $('<div title="Save" class="glyphicon glyphicon-save gj-cursor-pointer" data-key="' + id + '"></div>').hide();
    var $deleteBtn = $('<div title="Delete" class="app-icon-space glyphicon glyphicon-trash gj-cursor-pointer" data-key="' + id + '"></div>');

    $editBtn.on('click', function (e) {
        grid.edit($(this).data('key'));
        $editBtn.hide();
        $updateBtn.show();
    });

    $updateBtn.on('click', function (e) {
        grid.update($(this).data('key'));

        var dataToPost = { salutation: record };
        Common.Ajax('POST', salutationUpdate, dataToPost, 'json', salutationSuccessHandler);

        $editBtn.show();
        $updateBtn.hide();
    });

    $deleteBtn.on('click', function (e) {
        deleteSalutation(id);
    });

    $displayEl.append($editBtn).append($updateBtn).append($deleteBtn);
}

**Comment by atatanasov** [comment]
We use a special technique for faster rendering of the grid and refresh only cells that needs to be changed. In your case you need to clear all elements in $displayEl all the time before addition of new elements.

`$displayEl.empty().append($editBtn).append($updateBtn).append($deleteBtn);`

**Comment by csharpdocs** [comment]
yes it worked!!
