### ISSUE TITLE
Grid Enhancement: Need more function to get pageNumber, pageLimit, soryBy, sortDirection

### ISSUE THREAD

**Issue by csharpdocs** [atatanasov/gijgo#105]
Today i tried to export grid using custom code. to get result i made call to database through EF and brought results. To achieve this functionality i used below code.

Javascript code:
function exportTable()
{
    var gridParams = grid.data().params;
    var parameters = { page: gridParams.page, limit: gridParams.limit, sortBy: gridParams.sortBy, direction: gridParams.direction, searchTerm: $('#txtSearch').val() };
    Common.Ajax('GET', userExportExcel, parameters, 'json', exportTableSuccessHandler);
}

C# code:
public ActionResult ExportExcel(int? page, int? limit, string sortBy, string direction, string searchTerm)
{
// code to call EF and writhing through Response object
}
Apart from this any plan for providing export functionality like Excel, CSV?

**Comment by atatanasov** [comment]
Yes. We are planning to add export to csv, excel and pdf in future versions.
