### ISSUE TITLE
how can i hook the event just after i get the data?

### ISSUE THREAD

**Issue by xulei890817** [atatanasov/gijgo#106]
I have a setting.

dataSource: 'http://192.168.xx.xx:xxx/filepath/get/all'

Then get my server data like

{"id": 131, "text": "root", "path": "c://", "type": "folder"}

Then i want to set the imageUrl by the param "type" before it begin to do databind

**Comment by atatanasov** [comment]
Hello,

You can use one of the following configuration options:
http://gijgo.com/tree/configuration/imageUrlField
http://gijgo.com/tree/configuration/imageHtmlField
http://gijgo.com/tree/configuration/imageCssClassField
