### ISSUE TITLE
pagination problem in grid

### ISSUE THREAD

**Issue by vinod408** [atatanasov/gijgo#107]
I am successfully fetching data from remote data source but I am not getting pagination it is showing  Rows per page: 0-0of0 
the code I used is this:
    <div class="container-full">
        <div class="row">
            <div class="col-xs-12">
                <table id="grid" data-primary-key="TestSuiteId"></table>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            var grid = $('#grid').grid({
                primaryKey: 'TestSuiteId',
                dataSource: '/Validation/JqueryGettestsuites',
                //page, int? limit, string sortBy, string direction, string name, string placeOfBirth
                //params: { page: page },
                inlineEditing: { mode: 'command' },
                columns: [
                    { field: 'TestSuiteId', sortable: true},
                    { field: 'TestSuite1', sortable: true, editor: true },
                    { field: 'TestSuiteDescription', editor: true },
                    { field: 'IsActive', editor: true },
                    { field: 'TestSuiteOwner', editor: true },
                    { field: 'CreatedDate', title: 'Created Data', type: 'date' },
                    { field: 'CreatedBy', title: 'Created By' }
                ],pager:{limit:5},
                
                detailTemplate: '<div><table/></div>'
               
            });
            grid.on('rowDataChanged', function (e, id, record) {
                $.ajax({ url: '/Validation/SaveTestSuite', data: { record: record }, method: 'POST' })
                    .fail(function () {
                        alert('Failed to save.');
                    });
            });
            grid.on('rowRemoving', function (e, $row, id, record) {
                if (confirm('Are you sure?')) {
                    $.ajax({ url: '/Validation/DeleteTestSuite', data: { id: id }, method: 'POST' })
                        .done(function () {
                            grid.reload();
                        })
                        .fail(function () {
                            alert('Failed to delete.');
                        });
                }
            });
            grid.on('detailExpand', function (e, $detailWrapper, id) {
                $detailWrapper.find('table').grid({
                    params: { Id: id },
                    dataSource: '/Validation/jqueryGettestcases',
                    columns: [
                    { field: 'TestCaseId', sortable: true, width: 40,title:'Id' },
                    { field: 'TestCaseName', sortable: true }
                    ],
                    pager: { limit: 5 }
                    
                    
                });
            });
            grid.on('detailCollapse', function (e, $detailWrapper, id) {
                $detailWrapper.find('table').grid('destroy', true, true);
            });
        });
    </script>

**Comment by atatanasov** [comment]
I guess that the names of the fields that contains page and limit are called differently than 'page' and 'limit'.
You can rename them in the response or use http://gijgo.com/grid/configuration/paramNames.page and http://gijgo.com/grid/configuration/paramNames.limit to change their names.

**Comment by vinod408** [comment]
Earlier I havent return 'total' in json result. Now I returned 'records' and 'total' in json result. The bar shows 5/26 items per page but it displays 26 records in the table but bar is showing 5/26 items per page.

Please help me out
Thanks in Advance

**Comment by atatanasov** [comment]
You can see how it works from our sample project at https://github.com/atatanasov/gijgo-asp-net-examples. Please use it as an example.

**Comment by vinod408** [comment]
we have popup operation as inline 

one more thing the date which is in json format is only formatted in display when we edit it shows /Date(234546464)/ like this. How can we over come this

**Comment by atatanasov** [comment]
I think that would be best if you use momentjs to format the date. Here is an example: http://gijgo.com/grid/Configuration/column.format
