### ISSUE TITLE
Json date format in inline/popup edit

### ISSUE THREAD

**Issue by vinod408** [atatanasov/gijgo#108]
<!DOCTYPE html>
<html>
<head>
    <title>jQuery Grid Inline Editing</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="http://code.gijgo.com/1.4.0/js/gijgo.js" type="text/javascript"></script>
    <link href="http://code.gijgo.com/1.4.0/css/gijgo.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container-full">
        <div class="row">
            <div class="col-xs-12">
                <table id="grid"></table>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function () {
            var grid = $('#grid').grid({
                dataSource: '/Players/Get',
                uiLibrary: 'bootstrap',
                primaryKey: 'ID',
                inlineEditing: { mode: 'command' },
                columns: [
                   { field: 'Name' },
                    { title: 'Place Of Birth', field: 'PlaceOfBirth'},
                    { title: 'Date Of Birth', field: 'DateOfBirth', type:'date',editor:true}
                ],
                pager: { limit: 5 }
            });
            grid.on('rowDataChanged', function (e, id, record) {
                $.ajax({ url: '/Players/Save', data: { record: record }, method: 'POST' })
                    .fail(function () {
                        alert('Failed to save.');
                    });
            });
            grid.on('rowRemoving', function (e, $row, id, record) {            
                if (confirm('Are you sure?')) {
                    $.ajax({ url: '/Players/Delete', data: { id: id }, method: 'POST' })
                        .done(function () {
                            grid.reload();
                        })
                        .fail(function () {
                            alert('Failed to delete.');
                        });
                }
            });
        });
    </script>
</body>
</html>

How to convert the json date format  in readable date format

Thanks in Advance

**Comment by atatanasov** [comment]
I think that would be best if you use momentjs to format the date. Here is an example: http://gijgo.com/grid/Configuration/column.format
