### ISSUE TITLE
Search Box is not working

### ISSUE THREAD

**Issue by vinod408** [atatanasov/gijgo#110]
html code:
   <form class="display-inline">
                <input id="txtTestsuite" type="text" placeholder="TestSuitename..." class="gj-textbox-md gj-display-inline-block gj-width-200" />
                <input id="txtIsactive" type="text" placeholder="Isactive..Y/N." class="gj-textbox-md gj-display-inline-block gj-width-200" />
                <button id="btnSearch" type="button" class="gj-button-md">Search</button>
                <button id="btnClear" type="button" class="gj-button-md">Clear</button>
            </form>     

js:
$(document).ready(function () {
                grid = $('#grid').grid({
                    primaryKey: 'TestSuiteId',
                    uiLibrary: 'bootstrap',
                    dataSource: '/Validation/jqueryGettestsuites',
                   
                    columns: [
                        { field: 'TestSuiteId', sortable: true },
                        { field: 'TestSuite1', sortable: true, editor: false },
                        { field: 'TestSuiteDescription', editor: false },
                        { field: 'IsActive', editor: false },
                        { field: 'TestSuiteOwner', editor: false },
                        { field: 'CreatedDate', title: 'Created Date', type: 'date', format: 'mm/dd/yyyy', sortable: true, editor: true },
                        { field: 'CreatedBy', title: 'Created By' },
                        { width: 64, tmpl: '<span class="material-icons gj-cursor-pointer">edit</span>', align: 'center', events: { 'click': Popup } },
                        //{ width: 64, tmpl: '<span class="material-icons gj-cursor-pointer">delete</span>', align: 'center', events: { 'click': Popup } }
                    ],
                    pager: { limit: 8 },

                    detailTemplate: ' <div class="col-md-offset-1"><table/></div>'

                });
                grid.on('detailExpand', function (e, $detailWrapper, id) {
                    var subgrid = $detailWrapper.find('table').grid({
                        params: { Id: id },
                        uiLibrary: 'bootstrap',
                        primaryKey: 'TestCaseId',
                        //inlineEditing: { mode: 'command' },
                        dataSource: '/Validation/jqueryGettestcases',
                        columns: [
                        { field: 'TestCaseId', sortable: true, title: 'Id', width: 80 },
                         { field: 'PipelineStageId', sortable: true, width: 80 },
                        { field: 'TestCaseTypeId', sortable: true, width: 80 },
                        { field: 'Description', sortable: true, width: 200 },
                        { field: 'TestSuiteId', hidden: 'true', width: 80 },
                        { field: 'TestCaseName', sortable: true, width: 200 },
                         { field: 'IsActive', sortable: true, width: 80 },
                        { field: 'IsObsolete', sortable: true, width: 80 },
                        { field: 'ObsoleteReason' },
                        { width: 64, tmpl: '<span class="material-icons gj-cursor-pointer">edit</span>', align: 'center', events: { 'click': Popuptest } }
                        ],
                        pager: { limit: 5 }

                    });
                    subgrid.on('rowDataChanged', function (e, id, record) {
                        alert(JSON.stringify(record)),
                        $.ajax({ url: '/Validation/kendoUpdateGettestcases', data: record, method: 'POST' })
                            .done(function () {
                                grid.reload();
                            })
                            .fail(function () {
                                alert('Failed to save.');
                            });
                    });
                });
                grid.on('detailCollapse', function (e, $detailWrapper, id) {
                    $detailWrapper.find('table').grid('destroy', true, true);
                });
   $('#btnSearch').on('click', function () {
                    var isact = $('#txtIsactive').val();
                    alert(JSON.stringify(isact));
                    grid.reload({ page: 1, TestSuite1: $('#txtTestsuite').val() });
                });
                $('#btnClear').on('click', function () {
                    $('#txtName').val('');
                    $('#txtPlaceOfBirth').val('');
                    grid.reload({ page: 1, TestSuite1: ''});
                });

search is not working

thanks in advance

**Comment by atatanasov** [comment]
Please use our example at http://gijgo.com/grid/demos/ajax-sourced-data in order to see how to implement search for the grid. Probably the issue is on the back-end. check out code for the back-end in the back-end tab.
You can download a sample project about it at https://github.com/atatanasov/gijgo-asp-net-examples

**Comment by vinod408** [comment]
Back end problem.
Now resolved.Thank you.

Is any calendar event with recurrence functionality?

**Comment by atatanasov** [comment]
No. We don't have calendar widget yet.
