### ISSUE TITLE
Checking a tree node  which has only ONE child does not check that child automatically

### ISSUE THREAD

**Issue by mrplayq** [atatanasov/gijgo#113]
I have a treeview with checkboxes enabled, and in it I have a parent node which has only ONE child node, now selecting the parent node's checkbox does not automatically check the child node. This works fine when the parent node has multiple children but not if it only has one.
Please let me know when a fix is available as I'm trying to use your control in my project.
Thank you so much and btw the thing works great. Nice job!!!

**Comment by tyjing** [comment]
just want to ask is it your checkbox will auto select once the table is loaded?

**Comment by atatanasov** [comment]
You can use checkedField config option to check some of the options when the tree is loading
http://gijgo.com/tree/configuration/checkedField

**Comment by atatanasov** [comment]
BTW: This is fixed only in the development version. The development build is available only at https://github.com/atatanasov/gijgo/tree/master/dist

**Comment by mrplayq** [comment]
Hello,
Yes I can see that it is fixed in there. Thank you!

Another question is there an event that gets fired when the state of a
treeView checkbox is changed?
I need to trap that and do some validation work.
Thanks.

**Comment by atatanasov** [comment]
Hello,

We added checkboxChange event in the new development version. just get the latest build from https://github.com/atatanasov/gijgo/tree/master/dist

Here is an example: https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Checkboxes.checkboxChange.Event.Sample.html

**Comment by mrplayq** [comment]
Thanks you for that!
Will that give me the ability to check a node in JavaScript when another
node is clicked? In other words will there be a checkNode() API to set a
checkbox after the tree is loaded?

**Comment by mrplayq** [comment]
Hello Atanas,

I got the latest dev build as you said. I'm trying to run the code below,
inside the checkboxChange event handler
I have a parent node with child ids {1,2,4, 8}, when 1 ("View") is
unchecked I want to uncheck all other ids in the same level, namely 2,4,8
but I'm only able to uncheck the first node, after that the call to uncheck
for other nodes does not get executed. It seems as though the call to
 tree.uncheck() never returns!?

Please tell me what I'm doing wrong or if this is a bug:

var tree = loadJsonTree();

tree.on('checkboxChange', function (e, $node, record, state) {
//alert('The new state of ' + record.label + ' is ' + state);
var label = record.label;
if (state == "unchecked" && label == "View") {
//alert('if any other box at this level is checked it must be unchecked
when View is unchecked!');
//*BUG #1 *=> I tried this but it does not work either as it doesn't
uncheck its children with AutoCheck!
//var parentNode = tree.getNodeById(record.parentid);
//tree.uncheck(parentNode);

var otherIds = [2, 4, 8];
for (var i = 0; i < otherIds.length; i++) {
var nodeId = otherIds[i];
var node = tree.getNodeById(nodeId);
tree.uncheck(node);
alert("Just cleared " + nodeId); //*BUG #2* => This line never gets
executed!
}
   }
});

Thanks,
Russell B.

**Comment by atatanasov** [comment]
Hello,

Yes. Your issue is caused by a bug in the code. I fixed that in the new development version. 
Please get the latest build from https://github.com/atatanasov/gijgo/tree/master/dist

You can see a working example at http://gijgo.com/Temp/8f8d6cec-004c-49a8-89da-4b1e6b0fe536.html

**Comment by mrplayq** [comment]
Thank you. I'll try it and let you know.
Russell B.

**Comment by mrplayq** [comment]
Hi Atanas,

You fixed BUG#2 but BUG#1 still remains, and that is unchecking a parent
node (in javaScript by calling tree.uncheck(parentNode)) should also
uncheck all of its child nodes when auto-check is on.
See my below code snippet.

But good job on fixing the second bug!
Thanks,
Russell B.

var eComTree = loadEcomTree();
eComTree.on('checkboxChange', function (e, $node, record, state) {
      //alert('The new state of ' + record.label + ' is ' + state);
      var label = record.label;
      if (state == "unchecked" && label == "View") {
 *           var parentNode = tree.getNodeById(record.parentid); // This
still doesn't work!*
            *tree.uncheck(parentNode);*
            //alert('TODO if any other box at this level is checked it must
be unchecked when View is unchecked!');
      }
}

**Comment by atatanasov** [comment]
Hello,

I think that you need to use cascadeCheck set to false in order to do that. cascadeCheck is new config option that is added in the current development version a week ago.

This is a working example of I think what you need. Please test it with Asia as parent and China as child that control the parent.

http://gijgo.com/Temp/6dd5a377-f905-46c1-a3f0-84aaea8cf939.html

**Comment by mrplayq** [comment]
Hi Atanas,

But that defeats the purpose of having cascadeCheck on. I want to have it
on and be able to uncheck the parent tree when a child's state is changed.
There's a workaround for it and that's the other bug you already fixed,
which lets you uncheck individual child nodes that belong to a parent. I
just thought when cascadeCheck is on it would be easier to just uncheck the
parent and then the whole branch is unchecked.

For example, in your case, when I uncheck China, I want all of Asia to be
unchecked when cascadeCheck is ON.

Russell B.
