### ISSUE TITLE
Grid & form fields

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#114]
I'm using Bootstrap 3.3.7, Jquery 2.x and Datepicker for Bootstrap v1.7.0-RC3 (https://github.com/uxsolutions/bootstrap-datepicker)

There is a problem with the newest version of Gijgo grid.
The script grab & manipulate form elements of my edit / search forms with the css class "date" outside of the html table element for the grid.
That destroy the layout of the forms and is not good.

Sample: 

````
<form class="form-horizontal" action="http://xxx/periods" accept-charset="utf-8" method="post">

		<div class="form-group">
			<label id="label_start" for="form_start" class="control-label col-xs-2">Beginn</label>
			<div class="col-xs-10">
                <div class="input-group date">
                    <input type="text" maxlength="10" class="form-control" id="form_start" name="start" value="" />
                    <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
                </div>
                <span class="help-block"></span>
            </div>
	</div>
````

....if I enable gijgo script, than I have this result:

````
<div class="form-group">
    <label id="label_start" for="form_start" class="control-label col-xs-2">Beginn</label>
    <div class="col-xs-10"><div role="wrapper" class="gj-datepicker gj-datepicker-md gj-unselectable"><div class="input-group date gj-textbox-md" data-type="datepicker" data-guid="2c0d94ed-e5ce-3042-b294-be812f45b5ed" data-datepicker="true" role="input" month="6" year="2017"><input maxlength="10" class="form-control" id="form_start" name="start" value="" type="text"><div class="input-group-addon"><i class="fa fa-calendar"></i></div></div><i class="material-icons" role="right-icon">event</i></div><span class="help-block"></span></div>
</div>
````

**Comment by atatanasov** [comment]
I'm not able to replicate this issue. Could you fork this codepen in order to replicate the issue. https://codepen.io/atatanasov/pen/XNwYaK

BTW: We are going to release gijgo datepicker in the new version that is comming soon.

**Comment by atatanasov** [comment]
I'm closing this ticket. Please reopen the ticket if the issue still exists and provide an example.
