### ISSUE TITLE
Check status doesn't work.

### ISSUE THREAD

**Issue by peteryangthinkgeo** [atatanasov/gijgo#116]
Hi Supports,

Today I find an issue. I try to check a node which has only one child under it, it seems that the check operation doesn't work. Althrough the node is checked but the child node is still in uncheck state. Attached is the sample I work on, hope can help you to recreate this issue.

[demo.zip](https://github.com/atatanasov/gijgo/files/1176062/demo.zip)

Thanks,
Peter

**Comment by atatanasov** [comment]
Hello,
This is already fixed by https://github.com/atatanasov/gijgo/issues/113. You just need to use the latest development builds from https://github.com/atatanasov/gijgo/tree/master/dist. They are pretty stable and we are going to release the new version pretty soon.
