### ISSUE TITLE
How to know if it is subitem?

### ISSUE THREAD

**Issue by MarlonSi** [atatanasov/gijgo#117]
I would like to know how to differentiate an item from the subitem in the Bootstrap TreeView with Checkboxes, since I have the following output:

CheckedIds []: 1 --item
CheckedIds []: 2 --subitem
CheckedIds []: 3 --subitem
CheckedIds []: 4 --subitem

Thank you

**Comment by atatanasov** [comment]
If you download https://github.com/atatanasov/gijgo-asp-net-examples you can see how we are doing that  in C# and ASP.NET
