### ISSUE TITLE
Show Image in grid

### ISSUE THREAD

**Issue by girishk55** [atatanasov/gijgo#12]
Hi,

I am not able to show image in this grid.

I am using 

 { field: "Picture", tmpl: '<img src={Picture} />' },

like this.

Please help where I am wrong.

Thanks Girish
![111](https://cloud.githubusercontent.com/assets/3206017/15463907/d645dd50-20e9-11e6-810e-bb6bf4efacfb.png)

**Comment by atatanasov** [comment]
I think that you are using an old version of the grid plugin. If you use 0.6.2 everything should be working fine.
You can see my example at http://gijgo.com/Temp/fbbc108d-fa2c-45bf-855b-9728de156923.html

If you want to use the older version you can do that with the cellDataBound event. You can see example at http://gijgo.com/Grid/Events/cellDataBound
