### ISSUE TITLE
Datepicker could not create Date

### ISSUE THREAD

**Issue by morgli** [atatanasov/gijgo#121]
Calling 
`date = new Date(year + '-' + (month + 1) + '-' + day);`
could result in "Invalid Date" (perhaps depending on Settings of dateTime Format of OS).
It doesn't work (at least) for German (Switzerland) if the month is lower than 9 (month + 1 lower than 10) because it is single-digit.

The result of this is, that always "NaN-NaN-NaN" will be displayed as selected Date (also other functions as Navigation, etc. do not work). 

Perhaps it would work better like this:
`date = new Date(year, month, day);`

**Comment by atatanasov** [comment]
This is fixed in the new development version that is going to be released soon. Thanks for the feedback.
You can see the latest dev builds at https://github.com/atatanasov/gijgo/tree/master/dist
