### ISSUE TITLE
Option: Tree node always selected

### ISSUE THREAD

**Issue by omsiqveland** [atatanasov/gijgo#122]
I am using your tree for navigation in my page, where the selected node decides which data to show in the "main view". Hence, a node should always be selected, or else the user gets confused as to what is showing in the "main view". 

Could you add an option to the tree for enabling / disabling deselection of treenode (when not in multiselect mode)?

**Comment by atatanasov** [comment]
Thanks for the feedback. We are going to improve this in the new version that is comming soon.

**Comment by atatanasov** [comment]
After new review of your issue we think that we not need to change the plugin. You just need use selectionType=multiple and add some more logic in the select event that control your main screen.
