### ISSUE TITLE
jQuery Grid Bootstrap

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#123]
The dropdown list in the pager don't work.
There are no errors & no XHR-Requests in Firebug.

Sample: http://gijgo.com/grid/demos/jquery-grid-bootstrap

**Comment by stvowi** [comment]
Don't work with Firefox , IE 11... the outfit for the dropdown in IE isn't nice

**Comment by stvowi** [comment]
...don't also not work in Iron Browser (Chrome engine)

**Comment by atatanasov** [comment]
I will fix that soon. I promise. Thanks for the feedback.

**Comment by stvowi** [comment]
Thanks, there are also problems with the outfit in the Safari Browser.

**Comment by atatanasov** [comment]
This fix is going to be available in the new build

**Comment by stvowi** [comment]
thanks

**Comment by stvowi** [comment]
This bug exist yet unter IE 11 / FF... pls visit your demo page.
In the 1.5.1 Version is only to see a normal select field by me in FF under Ubuntu but the XHR-Stuff works again.
