### ISSUE TITLE
Problem with checkAll / uncheckAll methods

### ISSUE THREAD

**Issue by halarik** [atatanasov/gijgo#126]
Hi,
I have more than 1 tree in a page and I notice that the methods **checkAll()** and **uncheckAll()** do not work if I build dinamically the related tree. I took the related tree from an data attribute on button:

        $('.ma-btn').on('click', function(e) {
            var target = $(e.target),
                action = target.data('action');
                var tree = $('#'+target.data('relatedto')).tree();
            if (action === 'expand-all') {
                tree.expandAll();
            }
            if (action === 'collapse-all') {
                tree.collapseAll();
            }
            if (action === 'check-all') {
                tree.checkAll();
            }
            if (action === 'uncheck-all') {
                tree.uncheckAll();
            }            
        }); 

On click i got this error: **TypeError: tree.checkAll is not a function**
While for **expandAll()** and **collapseAll()** no problem.

**Comment by halarik** [comment]
same problem with **getCheckedNodes()** method.

TypeError: tree.getCheckedNodes is not a function

when:

        /*
         * Save 
         */
        $('#abilSave').on('click', function(e) {
            e.preventDefault();
            $('.abilTree').each(function() {
                var id = $(this).attr('id'); 
                var tree = $('#'+id).tree();
                var checkedIds = tree.getCheckedNodes();
            });  
        });

**Comment by atatanasov** [comment]
Hello,

You have this issue, because you call tree methods before the completion of the initialization process.
You need to use events like initialized and dataBound in order to make it work.

Here is one working example: http://localhost:59034/Temp/ba13f12b-45ed-4f76-ae00-a6839f7e785f.html
You can see all events at http://localhost:59034/tree/events

**Comment by halarik** [comment]
i cannot see the example

**Comment by atatanasov** [comment]
sorry. My bad.

These are the correct links:
http://gijgo.com/Temp/c7393b57-68bd-4810-a2aa-61b7a6acfbd5.html
http://gijgo.com/tree/events

This is the sample code
```
<html>
<head>
    <meta charset="utf-8" />
    <title>Treeview Example</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="http://code.gijgo.com/1.5.1/js/gijgo.js" type="text/javascript"></script>
    <link href="http://code.gijgo.com/1.5.1/css/gijgo.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css" />
</head>
<body>
  <button class="ma-btn">click</button>
    <div id="tree1"></div>
    <div id="tree2"></div>
    <script>
        var tree1 = $('#tree1').tree({
            primaryKey: 'id',
            dataSource: '/Locations/Get',
            checkboxes: true
        });
   $('.ma-btn').on('click', function(e) {
        var tree2 = $('#tree2').tree({
            primaryKey: 'id',
            dataSource: '/Locations/Get',
            checkboxes: true
        });
        tree2.on('dataBound', function() {
            tree2.checkAll();        
        });
    }); 
    </script>
</body>
</html>
```

**Comment by halarik** [comment]
thaks for the example but it seems that it do not work for me


after i have inserted the 'databoud' event no more error are tacken
but nothing work 

On Tue, 05 Sep 2017 22:47:43 -0700, Atanas Atanasov
wrote: 

> sorry. My bad. 
> 
> These are the correct links:
>
http://gijgo.com/Temp/c7393b57-68bd-4810-a2aa-61b7a6acfbd5.html [1]
>
http://gijgo.com/tree/events [2] 
> 
> This is the sample code 
> 
>
Treeview Example
> 
> click
> 
> --
> You are receiving this because you
authored the thread.
> Reply to this email directly, view it on GitHub
[3], or mute the thread [4].
 

Links:
------
[1]
http://gijgo.com/Temp/c7393b57-68bd-4810-a2aa-61b7a6acfbd5.html
[2]
http://gijgo.com/tree/events
[3]
https://github.com/atatanasov/gijgo/issues/126#issuecomment-327381449
[4]
