### ISSUE TITLE
dropdown preview

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#127]
...don't work - no list will displayed

see: http://gijgo.com/dropdown

**Comment by atatanasov** [comment]
It works for me. I'm using Chrome. What is your web browser?

**Comment by stvowi** [comment]
Firefox 54.0.1...the newest

**Comment by stvowi** [comment]
IE 11 is okay

**Comment by atatanasov** [comment]
This is fixed already in the new development version that is going to be released soon
