### ISSUE TITLE
grid and ajax json result

### ISSUE THREAD

**Issue by YangBration** [atatanasov/gijgo#132]
I have a button called a javascript function to request json data Part of the thousands, total record num and page index ; but i can not run currect by reload function.

ex:
$.getJSON('/controller/action', { get_param: 'value' }, function(data) {
    //data.records will caculate and modify (it is important step)...
    grid.data().dataSource = data.records;
    grid.reload({ total: data.total , page: data.pagenumber });	
});

when reload function parameter is empty, it's work ,but just one page, 
i hope set total records and page index...

can you help me 
how can i transfer custom json data to grid ??
thanks ...

**Comment by atatanasov** [comment]
I think that would be best if you use render method in your case. You can see an example at 
http://gijgo.com/grid/methods/render

**Comment by YangBration** [comment]
Thanks for your answer, i will try it!!

**Comment by atatanasov** [comment]
closing... let me know if it doesn't work and I will reopen it.
