### ISSUE TITLE
gj is not defined

### ISSUE THREAD

**Issue by XingdaLee** [atatanasov/gijgo#133]
Hi,
 use "gijgo/dist/modular/js/" Only use tree.js and checkbox.js error, I should do it？
Thanks

**Comment by atatanasov** [comment]
Hi,

You need to include core.js and core.css when you use modular build.
You can see an example at https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Checkboxes.checkboxes.Bootstrap.html

**Comment by sahilchopra** [comment]
+1

**Comment by sahilchopra** [comment]
@atatanasov  
I am trying to import

import gj from 'gijgo/modular/js/core.min.js';
require('gijgo/modular/js/datepicker.min.js')(gj);

bundle.js:143620 Uncaught ReferenceError: gj is not defined

Any idea about this?

Thanks

**Comment by atatanasov** [comment]
I don't think that this is an issue with gijgo. Probably you are trying to use gijgo before it is loaded. Please double check your configuration.
