### ISSUE TITLE
Lazy Loading with Tree component and AJAX

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#134]
Is that possible with Gijgo tree? Is there an example?

Here is the background for this feature... https://mtyka.github.io/code/2012/10/02/lazy-loading-with-jstree-and-ajax.html

**Comment by atatanasov** [comment]
not yet, but this is planned to the future version.

**Comment by stvowi** [comment]
Thanks, I think this feature is important for big trees

**Comment by atatanasov** [comment]
We added support for lazy loading in our new development version. You can see an example at https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.LazyLoading.lazyLoading.Material.Design.html

Let us know if you have any questions. Please use the latest development build from https://github.com/atatanasov/gijgo/tree/master/dist

**Comment by bahmansh** [comment]
Thanks atatanasov.
Has it special documentation?
Can i expand a node with individual query? (I wanna have a tree that first level show organisation, second level show organisation buildings, third level show building peoples.

**Comment by atatanasov** [comment]
This is new feature and the documentation is going to be available after the official release.
I think that you have to create something like this example with our new development build:
https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Base.hasChildrenField.Custom.FieldName.html

You can also see another example with C# where the tree structure is in one table at https://github.com/atatanasov/gijgo-asp-net-examples
