### ISSUE TITLE
How do I disable $ ('<span data-role = "expander" data-mode = "close"> </ span>') events?

### ISSUE THREAD

**Issue by XingdaLee** [atatanasov/gijgo#135]
Hi:
  I would like to disable the click to start the node's events, what should I do?
Thanks!!
![qq 20170907112432](https://user-images.githubusercontent.com/12740778/30144690-4ceb66b6-93bf-11e7-92c4-9e00d865f8c4.png)

**Comment by XingdaLee** [comment]
Can be enabled and disabled

**Comment by XingdaLee** [comment]
I have found a solution, if you have a better way？
`document.getElementById('tree').style.pointerEvents = 'auto';
document.getElementById('tree').style.pointerEvents = 'none';`

**Comment by atatanasov** [comment]
This is not supported yet. Your work arrounds seems to work fine. We may add this feature in some future version.

**Comment by atatanasov** [comment]
We added disable and enable methods for the tree in the new development version.
Here is the example: https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Base.disable.Sample.html
https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Base.disable.Enable.Disable.All.html
