### ISSUE TITLE
Bootstrap Grid Inline Edit - new option

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#143]
I think it would be good to have a option to toggle between button with only icon & with the description text in the title attribut (tooltip) of the button (... see also [103](https://github.com/atatanasov/gijgo/issues/103)) and buttons with icons & text in the action column .

Only icon buttons could save space in the table and can prevent problems with the witdh of the texts (...Display of buttons on one another) through the translations.

You can see here what I mean: https://markcell.github.io/jquery-tabledit/#examples

The width of the action column should be also an option.

It should not be necessary to rewrite parts of the grid for basic cases.

**Comment by atatanasov** [comment]
You have a full control on the buttons during inline editing and you can control everything.
You can check the following example:
http://gijgo.com/Temp/a31f0862-7d61-4e79-91ce-32c4deed252b.html

You can use the following methods to manage the editing:
http://gijgo.com/grid/methods#InlineEditing

**Comment by stvowi** [comment]
Thanks for the answer.
