### ISSUE TITLE
Tree select

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#145]
There are also no jquery plugin in the www to select one tree item to get the id in a form.
The selction shoult show the path to the tree item (e.g. : 'item 1 > item 1.1 > item 1.1.3').

I could find only...http://www.jqueryscript.net/demo/Treeview-Style-Multi-Select-Plugin-For-Bootstrap-Treeselect/

So it is a idea for a new Gijgo component, isn't it?

**Comment by atatanasov** [comment]
Thanks for the idea! We are going to add this in our backlog and review it at some point in the future.
Thanks again!

**Comment by stvowi** [comment]
... this https://neofusion.github.io/hierarchy-select/ combined with Gijgo tree and the the path of the selected item as tooltip would be great
