### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#146]
There are any Material Design CSS Frameworks in the Net.

Would you please publish the link for the Material Design Framework which will supported from Gijgo?

**Comment by atatanasov** [comment]
Probably the most popular Material Design cc framework is https://getmdl.io/. Gijgo is not dependent on this library and you can use it with and without it. Gijgo with Material Design theme is only dependent on material icons provided by google at https://fonts.googleapis.com/icon?family=Material+Icons
