### ISSUE TITLE
Grid - selectAll method sends incorrect rowSelect event signature

### ISSUE THREAD

**Issue by marcbonner** [atatanasov/gijgo#148]
When selectAll (and unSelectAll) method is run, it's calling gj.grid.methods.selectRow($grid, data, $row, $grid.get($row.data('position')));

The event signature calls for (e, $row, id, record).  It's returning the 'record' object as 'id'.

I've modified the method for myself, but fear it will be lost on your next update:
    selectAll: function ($grid) {
        var data = $grid.data();
        $grid.find('tbody tr[data-role="row"]').each(function () {
            var $row = $(this);
            var $data = $grid.get($row.data('position'));
            gj.grid.methods.selectRow($grid, data, $row, $data.ID, $data);
        });
        $grid.find('thead input[data-role="selectAll"]').prop('checked', true);
        return $grid;
    },

**Comment by atatanasov** [comment]
We fixed that in the new development version. Thanks for the contribution.
