### ISSUE TITLE
Tree - new method...getSelectedNodeData()

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#151]
It is cumbersome to determine the data of a selected entry.

**Comment by atatanasov** [comment]
In order to do the you have to get the id of the selected element(s) with http://gijgo.com/tree/methods/getSelections or http://gijgo.com/tree/events/select and the use http://gijgo.com/tree/methods/getDataById in order to get the data.

**Comment by irajchardoli** [comment]
is it possible get data on select event like this:

            $('#tree').tree({
                uiLibrary: 'bootstrap',
                dataSource: treeDataResult , //'/Locations/Get',
                primaryKey: 'id',
                select: function (e, node, id) {
                    var obj = getDataById(id);

                }
            });
