### ISSUE TITLE
Tree - new method ... selectNodeById

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#152]
If I reload the tree than no item / node is selected.
If I add a node without parent id than I would like select the first item of the tree after relaod.
It should be possible to select a node/ item programmatically...not only with mouse/ keyboard.

**Comment by atatanasov** [comment]
We are going to add select and unselect methods in the next version.

**Comment by stvowi** [comment]
Thanks...please as soon as possible

**Comment by atatanasov** [comment]
We added this methods to the new development version. You can see an example at https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Base.select.sample.html
