### ISSUE TITLE
getAll(true) not working

### ISSUE THREAD

**Issue by webcliq** [atatanasov/gijgo#153]
Regrettably getAll(true) is not working as expected with a fitered recordset. Only returns filtered records not all records.
This was true in 1.5 and is still true in 1.6.
I think I can see where the problem is in the source code but have no time to fix it.

**Comment by atatanasov** [comment]
We are going to fix that in the new version.

**Comment by atatanasov** [comment]
This is already fixed. Thanks for the contribution.
