### ISSUE TITLE
Tree - nodeDrop - missing parameter

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#158]
I missing the content of the text field as parameter ('text') by [nodeDrop](http://gijgo.com/tree/events/nodeDrop).
It's not possible to check for dublicate without this information server side before saving the changed data, isn't it?

**Comment by atatanasov** [comment]
You can use the id parameter in nodeDrop and http://gijgo.com/tree/methods/getDataById method in order to get the text.

**Comment by stvowi** [comment]
Thanks...I've seen this solution after my post.
