### ISSUE TITLE
Editor - missing option - maxlength 

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#159]
I miss a maxlength option that allows to specify the maximum length of a text in the editor.

you can see here what I mean: http://www.jqueryscript.net/form/Textarea-Maxlength-Plugin-jQuery-maxlength.html

**Comment by atatanasov** [comment]
We are going to add that soon. Thanks for the feedback.

**Comment by stvowi** [comment]
..with maxlength and fullscreen mode is the editor perfect for the most use cases.

**Comment by atatanasov** [comment]
We decided to not implement maxlength for now as part of the plugin for editor. You can use the change event and our content method in order to control the size of the text inside the editor. You should be able to control that with few lines of code. Let us know if you have any issues with that.

**Comment by stvowi** [comment]
Would you please show your solution in one of your demo/ documentaion files?

**Comment by stvowi** [comment]
You code snippets are a treasure!

**Comment by atatanasov** [comment]
You can see an example about that at https://github.com/atatanasov/gijgo/blob/master/examples/editor/Editor.Base.changing.MaxLength.html

You have to use the new development build. I just added changing event to the editor that is going to allow you to do that.
