### ISSUE TITLE
Grid - display issue (resizableColumns: true, column.sortable=true)

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#165]
I would say there is a problem with the position of the sort up/ down icons.
They will placed ever under the titel of the colums even if there is enough space at the right side of the title.

The user would expect the sort icon on the right side of the title after the resize of the colmn and the width of the colum is big enough.

Drag & Drop should not lead to a sort of the column.

Sample:

```
<script>
     $('#grid').grid({
         uiLibrary: 'bootstrap4', // same problem with Bootrap 3
         iconsLibrary: 'fontawesome',
         resizableColumns: true,
         dataSource: '/Players/Get',
         columns: [
             { field: 'ID', width: 42 },
             { field: 'Name', sortable: true },
             { field: 'PlaceOfBirth', sortable: true}
         ]
     });
 </script>
```

I'm tested with FF.

**Comment by atatanasov** [comment]
We fixed that in the new development version. Thanks for reporting this issue.

**Comment by stvowi** [comment]
thanks for the fix
