### ISSUE TITLE
Inline editable dropdown issue with Bootstrap

### ISSUE THREAD

**Issue by metacube-shivang** [atatanasov/gijgo#166]
When doing inline editing on the grid with bootstrap theme, on a column of type 'dropdown', a JS error is thrown. Here's an example: https://jsfiddle.net/ShivangGupta/cb6sodL0/

The error is: 
![error](https://user-images.githubusercontent.com/13678651/30962904-30ba01e0-a469-11e7-8a17-b08efcec316b.png)

I'm new to this library. So, perhaps I'm doing something wrong. But I've looked at many examples, and it seems like a bug. If not, can you please let me know what changes I can do to make it work?

Thanks!

**Comment by atatanasov** [comment]
We don't support https at code.gijgo.com. https://code.gijgo.com/1.5.1/js/gijgo.js is invalid url, http://code.gijgo.com/1.5.1/js/gijgo.js is valid. I'm using https://cdn.rawgit.com/atatanasov/gijgo/master/dist/combined/js/gijgo.min.js in my jsfuddle examples which is the latest dev build.

https://jsfiddle.net/user/atatanasov/fiddles/

**Comment by metacube-shivang** [comment]
I'm not sure if the issue is due to the use of HTTPS. On my local machine, I'm using just HTTP, and still getting the same error. Unfortunately, jsFiddle doesn't support resources over HTTP, so I couldn't create the example with HTTP.

I've also tried out the latest dev build that you pointed out (https://cdn.rawgit.com/atatanasov/gijgo/master/dist/combined/js/gijgo.min.js), and it's still not working for me.
