### ISSUE TITLE
Issues with Calendar in grid

### ISSUE THREAD

**Issue by Kberg81** [atatanasov/gijgo#169]
I noticed two things about the calendar control in the grid.

1.  If you save the record while the calendar is displaying, the calendar is not removed and you CAN'T remove it.
2. If your grid extends down to the bottom of your browser window, the calendar will bleed off the bottom of the window.

**Comment by atatanasov** [comment]
We are going to fix that soon in the new development version.

**Comment by atatanasov** [comment]
1.) is fixed. We are going to address 2.) in the next release.

**Comment by atatanasov** [comment]
The second issue is fixed in the new development version. You can find the new build in the dist folder at github.
