### ISSUE TITLE
Grid Local DataSource Sort Algorithm

### ISSUE THREAD

**Issue by rfreedman** [atatanasov/gijgo#17]
The grid is a really nice component - thanks!

Feature request:
 It would be nice to be able to provide a custom function for sorting - a single default one would be good, and being able to provide it on a per-column basis would be even better.

Likely uses:
 1. Ability to specify a case-insensitve sort
 2. Ability to specify a sort that deals with alternative collation sequences.
 3. Ability to sort based on an attribute other than the collation of the content

Thanks!

**Comment by atatanasov** [comment]
Hi Rich,

I added option for custom sorting in the new development version.
You can see an example at https://github.com/atatanasov/gijgo/blob/development/examples/grid/Grid.Base.column.sortable.Local.CustomSorting.html
You can find the latest development build at https://github.com/atatanasov/gijgo/tree/development/dist/combined

**Comment by rfreedman** [comment]
That's great, thanks!
I'll try it out shortly.

Thanks for the quick response.

**Comment by rfreedman** [comment]
Works well, thank you!
