### ISSUE TITLE
Calendar does not support a common date format dd mmm yyyy (ex. 10 OCT 2017)

### ISSUE THREAD

**Issue by Kberg81** [atatanasov/gijgo#170]
dd mmm yyyy is a common format used by the U.S. Government. I was surprised that the grid did not handle that. I modified your code to address that format and would be happy to share it with you.

**Comment by atatanasov** [comment]
We are going to support that in the new version. Thanks for the feedback.

**Comment by atatanasov** [comment]
This is already available in the latest development build at https://github.com/atatanasov/gijgo/tree/master/dist

**Comment by stvowi** [comment]
Yepp, it works - thanks
