### ISSUE TITLE
library conflicts

### ISSUE THREAD

**Issue by pentexsoft** [atatanasov/gijgo#172]
when including the bootstrap.js in the same project, the drop down editor throws error .
when including jquery-ui.js in the same project the date editor throws the same error.

Object doesn't support property or method 'value'

appears there is naming conflicts with these libraries.

**Comment by atatanasov** [comment]
We fixed that in the following maner in the new development version (1.6.0)
1. If gijgo.js is the last included js in the page we override previous implementations like dropdown, datepicker.
2. If you want to use widget implementations from other libraries like bootstrap.js or jquery-ui you need to include them after gijgo.js and they are going to override gijgo widgets implementations.
