### ISSUE TITLE
Inline Edit - DatePicker does not close

### ISSUE THREAD

**Issue by pentexsoft** [atatanasov/gijgo#173]
when inline editing and clicking on the calendar to open, there is no way to close the calendar except to select a date. there should be a close button and it should also close on another column receiving focus

**Comment by atatanasov** [comment]
We are going to address that in the next release. Thank for the feedback.

**Comment by atatanasov** [comment]
This is fixed in the new development version located at https://github.com/atatanasov/gijgo/tree/master/dist
We will hide the calendar when another column receive focus.
