### ISSUE TITLE
Paging doesn't work

### ISSUE THREAD

**Issue by sikippy** [atatanasov/gijgo#175]
Dear Atatanasov,

I use this source in my local directory
    <script src="~/Scripts/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/gijgo/combined/gijgo.js" type="text/javascript"></script>
    <script src="~/Scripts/gijgo/modular/grid/core.js" type="text/javascript"></script>
    <link href="~/Content/gijgo/combined/core.css" rel="stylesheet" type="text/css">
    <link href="~/Content/gijgo/combined/gijgo.css" rel="stylesheet" type="text/css" />

when i am running my web apps in my localhost, gijgo grid all loaded perfectly but not the same when i tried to running it from my IIS server, and when i inspect element, i found an error like this Uncaught ReferenceError: gj is not defined
    at gijgo.js:8 . What am i doing wrong?please help. Thank you

**Comment by atatanasov** [comment]
Please use our asp.net example in order to see how to configure the paging. You can find them at https://github.com/atatanasov/gijgo-asp-net-examples

**Comment by sikippy** [comment]
![gijgoerror](https://user-images.githubusercontent.com/28854236/31485751-1ab34c84-af5f-11e7-98bd-68ad9c9bb0ed.png)

Dear Atatanasov, i would like to ask about paging in gijgo grid.
Here is my code, i use it with 3 different id of grid -> grid, grid1, grid2.

I need to hide all right control and some left control, so i do customize on this code:

$.ajax({
                        url: '@Url.RouteUrl("getDataGrid2")',
                        method: 'POST',
                        success: function e(result) {
                            grid2 = $('#grid2').grid({
                                // dataSource: data,
                                responsive: true,
                                columns: [
                               { title: '', field: 'Delete', width: 34, type: 'icon', icon: 'glyphicon-remove', tooltip: 'Delete', events: { 'click': Delete } },
                               { field: 'NoForm', title: 'Form No', width: 60, sortable: true },
                               { field: 'TransNo', width: 60, title: 'Trans No', sortable: true },
                               { field: 'Type', width: 34, title: 'Type', sortable: true },
                               { field: 'Price', width: 60, title: 'Price', sortable: true },
                                ],
                                uiLibrary: 'bootstrap',
                                pager: {
                                    limit: 20, sizes: [20],
                                    leftControls: [
                                     /* $('<button type="button" class="btn btn-primary btn-sm icon-disabled" title="First Page" data-role="page-first" disabled=""><span class="glyphicon glyphicon-step-backward"></span></button>'),*/
                                      $('<button type="button" class="btn btn-primary btn-xs icon-disabled" title="Previous Page" data-role="page-previous" disabled=""><span class="glyphicon glyphicon-backward"></span></button>'),
                                      $('<div>Page</div>'),
                                      $('<div></div>').append($('<input data-role="page-number" class="form-control input-sm" style="width: 40px; text-align: right;" type="text" value="0">')),
                                      $('<div>Of</div>'),
                                      $('<div data-role="page-label-last">0</div>'),
                                      $('<button type="button" class="btn btn-primary btn-xs icon-disabled" title="Next Page" data-role="page-next" disabled=""><span class="glyphicon glyphicon-forward"></span></button>'),
                                     /* $('<button type="button" class="btn btn-primary btn-sm icon-disabled" title="Last Page" data-role="page-last" disabled=""><span class="glyphicon glyphicon-step-forward"></span></button>'),
                                      $('<div></div>').append($('<select data-role="page-size" class="form-control input-sm"></select></div>'))*/
                                    ],
                                    rightControls: []
                                },
                                cellDataBound: function (e, $wrapper, id, column, record) {
                                    $('.gj-checkbox-bootstrap input[type="checkbox"][disabled]').removeAttr('disabled');
                                }
                            });
                            grid2.reload({ NoForm: result.NoForm, TransNo: result.TransNo, Type: result.Type, Price: result.Price, total: 0 });
                        }
                    });

And the paging doesn't work, do something going wrong here?

Thank you for your help.

**Comment by vsile** [comment]
Pager doesn't work after grid render.

Try this code:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Example</title>
  <script src="/Areas/Development/dist/libraries/jquery/jquery.js"></script>
  <script src="/Areas/Development/dist/modular/js/core.js" type="text/javascript"></script>
  <link href="/Areas/Development/dist/modular/css/core.css" rel="stylesheet" type="text/css">
  <link href="/Areas/Development/dist/modular/css/grid.css" rel="stylesheet" type="text/css">
  <script src="/Areas/Development/dist/modular/js/grid.js"></script>
</head>
<body style="padding: 8px;">
 <table id="grid"></table>
 <script>
     var grid, onSuccessFunc;
     onSuccessFunc = function () {
         //you can modify the response here if needed
       	 var data = [{"ID":1,"Name":"Hristo Stoichkov","PlaceOfBirth":"Plovdiv, Bulgaria"},{"ID":2,"Name":"Ronaldo Luís Nazário de Lima","PlaceOfBirth":"Rio de Janeiro, Brazil"},{"ID":3,"Name":"David Platt","PlaceOfBirth":"Chadderton, United Kingdom",},{"ID":4,"Name":"Manuel Neuer","PlaceOfBirth":"Gelsenkirchen, West Germany"},{"ID":5,"Name":"James Rodríguez","PlaceOfBirth":"Cúcuta, Colombia"},{"ID":6,"Name":"Dimitar Berbatov","PlaceOfBirth":"Blagoevgrad, Bulgaria"},{"ID":7,"Name":"Robert Lewandowski","PlaceOfBirth":"Warsaw, Poland"}];
        grid.render(data);
     };
     grid = $('#grid').grid({
         dataSource: { success: onSuccessFunc },
         columns: [ { field: 'Name' }, { field: 'PlaceOfBirth' } ],
         pager: { limit: 5 }
     });
 </script>
</body>
</html>
```

How to fix it?

**Comment by vsile** [comment]
Or just add pager to your example.. http://gijgo.com/grid/methods/render
Pager doesn't work...
