### ISSUE TITLE
Tree Reload method is invalid

### ISSUE THREAD

**Issue by hwubin5** [atatanasov/gijgo#176]
Tree  with parameter reload method is invalid.  Or Whether can give a demo？

**Comment by atatanasov** [comment]
We fixed that in the new development version. Thanks for finding this. You can see a sample code at:
https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Base.reload.Search.html

**Comment by hwubin5** [comment]
Thank you for your efforts and hope for better functional products.
