### ISSUE TITLE
toolbarTemplate on reload

### ISSUE THREAD

**Issue by pentexsoft** [atatanasov/gijgo#177]
it appears the toolbar template once set, is not getting reset on destroy/reload.
steps
1. load the grid with a toolbar template based on a condition
2. change the condition to show different toolbar 
3. call destroy, call reload, call refresh

original template remains on the grid even though the new condition is satisfied.
row template is properly working, just the toolbar is not changed out.

**Comment by atatanasov** [comment]
We fixed that in the new development version. The new build is at https://github.com/atatanasov/gijgo/tree/master/dist

Thanks for finding and reporting this issue.
