### ISSUE TITLE
Responsive : detailTemplate : Hangs When record edited 

### ISSUE THREAD

**Issue by PulkitChoudhary** [atatanasov/gijgo#18]
Steps to reproduce ->

1. Resize screen to small view so that columns can move to detail template view - 
**
![image](https://cloud.githubusercontent.com/assets/20884367/17461200/418ce070-5ca1-11e6-9542-7f06bfcf12eb.png)
**
2. Expend to see hidden columns in detail view/DetailTemplate - 
![image](https://cloud.githubusercontent.com/assets/20884367/17461201/8f4dd4d6-5ca1-11e6-95b9-0109ea58b106.png)

3. Click on edit for same row for which detail template is visible and save to update the new values -
![image](https://cloud.githubusercontent.com/assets/20884367/17461205/e388c36c-5ca1-11e6-84ad-bcda57b906f8.png)

4. Try to collapse to hide detialView/DetailTemplate and you have the issue -
![image](https://cloud.githubusercontent.com/assets/20884367/17461210/4653c7ee-5ca2-11e6-9ff3-4c8c554238a2.png)

For your reference here you get the imp files & Screens - 

1. Index.cshtml : [Index.txt](https://github.com/atatanasov/gijgo/files/405357/Index.txt)
2. HomeController : [HomeController.txt](https://github.com/atatanasov/gijgo/files/405358/HomeController.txt)

Scripts & CSS File Used - 
![image](https://cloud.githubusercontent.com/assets/20884367/17461264/c95cc2a2-5ca3-11e6-8f0f-d26abdf24e9e.png)

Note - No change to GridModel.cs, Player.cs, SortHelper.cs files.

**Comment by atatanasov** [comment]
We fixed that issue in the latest development version. You can find the latest build at https://github.com/atatanasov/gijgo/tree/development/dist/combined

Thanks for the feedback.
