### ISSUE TITLE
Grid edit mode is not turned off when page is changed

### ISSUE THREAD

**Issue by salgadonikka** [atatanasov/gijgo#180]
Grid with inline editing and has pagination

If a row is in edit mode and then the page is changed, the fields in edit mode is retained even if the data is updated to the next page's data. Can anyone assist in manually turning off edit mode when page index is changed? Thanks!

**Comment by salgadonikka** [comment]
I already found a workaround for this. Thanks!

**Comment by atatanasov** [comment]
This is fixed in the new development version.
