### ISSUE TITLE
module: grid; request: styling column width

### ISSUE THREAD

**Issue by francescosaverio** [atatanasov/gijgo#181]
Hi, Mr. Atanasov.
While I'm congratulating with You for such a smart job, I wish I would submit the following request:

With current release (1.5.1) You can easily set-up a row made up of input text box controls in order to define search arguments, prodiving the proper styling (e.g.: bootstrap column width, @class = "form-control col-md-2", using razor).
I wonder it it would be possible to implement a parameter to set-up "grid" control (I mean directives like:
                    { field: 'ID', title: 'Id.', sortable: true, width: 64 },
), 
in order to create an input search arguments line which is "in line" with the resulting grid full of data, I mean something like:
                    { field: 'ID', title: 'Id.', sortable: true, width: @class = "form-control col-md-2" },
according to my previous case-example.
My request could seem not that useful, still nowadays Users keep becoming more and more demanding in terms of UI smartness and elegance. I think this request is about meeting such trend.
I am rather novice of "gijgo", but already enthusiast.

Thank You for Your attention.

Francesco.

**Comment by atatanasov** [comment]
Hello,

Thanks for the feedback. I think that we already support that.
You can see this example for html configuration - http://gijgo.com/grid/demos/html-sourced-data

You can use the following config options to set css classes. They are going to work if you use them as data attributes as well.

http://gijgo.com/grid/configuration/column.cssClass
http://gijgo.com/grid/configuration/column.headerCssClass

**Comment by francescosaverio** [comment]
Hi, Mr. Atanasov!... 
...And thank You so much for Your kind and time-responsive answer.
So, You could actually verify I am quite new of Gijgo... And maybe a little bit lasy...)))
So I could accomplish my task.

Thank You again!
Francesco.

**Comment by atatanasov** [comment]
You are welcome. Thanks for using my open source library.
