### ISSUE TITLE
Grid - Bootstrap 3 - pager sizes

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#182]
Howdy, 

if I use the development version from yesterday and if I click to an item in the list with the page sizes... nothing happen in IE11/ FF. There is no XHR request since you replaced the select box with a bootstrap dropdown..

**Comment by atatanasov** [comment]
It works for me. Could you send me a sample code that I can use to relicate the issue

**Comment by stvowi** [comment]
You can see it also by your sample: http://gijgo.com/grid/demos/jquery-grid-bootstrap

It's my prototype.

**Comment by stvowi** [comment]
I'm tested with the Iron Browser (Chrome) and Gijgo Version from today....nothing happen.

I include in my Demo app...





  | <script type="text/javascript" src="../assets/widgets/bs/gijgo/combined/js/gijgo.min.js"></script> 
  | <script type="text/javascript" src="../assets/widgets/bs/gijgo/combined/js/messages/messages.de-de.js"></script>



--
  | <link href="../assets/widgets/bs/gijgo/combined/css/gijgo.min.css" rel="stylesheet">

I use JQuery 3.2.1 and a costumized Version of [Bootsrap 3.3.7](https://bootswatch.com/flatly/)


Could it be that you forgot dropdown.js ?

**Comment by stvowi** [comment]
http://gijgo.com/grid/configuration/uiLibrary the demos for Bootsrap 3/ 4 have also problems with the page sizer

**Comment by atatanasov** [comment]
It works for me on IE 11 and Firefox. What is your version of the browsers? Can you send me some video/gif file that shows the problem? You can use something like http://www.screencast.com/ to share it with me.

**Comment by stvowi** [comment]
I have Win7 and use actual Browsers. The problem is, I don't get javascript errors. If you have a LAMPS - Server than I would build and send you a demo via mail.

**Comment by stvowi** [comment]
Dear Mr. Atatanasov, I can't share things from my company.
Therefore I reference to the wonderful samples in the documentation.

You can see the "bug" also here:

http://gijgo.com/grid/configuration/pager.sizes
http://gijgo.com/Areas/Development/examples/grid/grid.Pagination.pager.sizes.Bootstrap.3.html

There is anyway a problem with the dropdown component.

**Comment by stvowi** [comment]
It works also not with Webkit-Browser (Ubuntu)
I tested it with Google Browser (Android 4) on a tablet with touch screen, there is all okay.

**Comment by atatanasov** [comment]
This should be resolved in the new development version.
