### ISSUE TITLE
Firefox: Warnings in console

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#185]
I got this warnings by http://gijgo.com/grid/demos/jquery-grid-bootstrap .

Message: Das nodeValue-Attribut von Attributen sollte nicht mehr verwendet werden. Verwenden Sie value stattdessen.  gijgo.js:131:8
... it means. nodeValue is depricated use value

- https://stackoverflow.com/questions/20330301/use-of-attributes-nodevalue-attribute-is-deprecated-use-value-instead-error-in
- https://developer.mozilla.org/en-US/docs/Web/API/Attr#Deprecated_properties_and_methods

**Comment by atatanasov** [comment]
I will fix that in the next version. Thanks for the feedback.
