### ISSUE TITLE
Dropdown - change

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#186]
...don't work in FF 56/ IE11/ Iron(Chrome)... there is no alert box if I click with the mouse to an list item.

you should see/ test it here:

http://gijgo.com/dropdown/events/change
http://gijgo.com/Areas/Development/examples/dropdown/dropdown.Base.change.sample.html

So the page size list in the grid can also not work.

**Comment by atatanasov** [comment]
We fixed that in the new development version. Please use the new development version.
