### ISSUE TITLE
Grid - createChangePageHandler

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#187]
Sorry, I have to say there is piece of code who ist not so great.

```

createChangePageHandler: function ($grid, currentPage, lastPage) {
            return function () {
                var data = $grid.data(),
                    newPage = parseInt(this.value, 10);
                if (newPage && !isNaN(newPage) && newPage <= lastPage) {
                    gj.grid.plugins.pagination.private.changePage($grid, newPage);
                } else {
                    this.value = currentPage;
                    alert('Please enter a valid number.');  
                }
            };
        },
```
Why?

- There is a native alert who breaks the design
- The message is only in English - not in the languge files

A possible solution could be a property in the grid config with a callback function.
I would like call in this function: [bootbox.alert("Bitte geben Sie eine gültige Zahl ein!");](http://bootboxjs.com/)  .

**Comment by atatanasov** [comment]
We improved that in the new development version. You can do that if you use the following example.
https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.Pagination.pageChanging.sample.html

**Comment by stvowi** [comment]
okay - thanks
