### ISSUE TITLE
How to get DropDown List Working in GijGo Grid

### ISSUE THREAD

**Issue by Ankitmane1512** [atatanasov/gijgo#19]
How to add dropdown list in a specified cell and also how to get value for selected item in dropdown.

**Comment by atatanasov** [comment]
You can see an example for inline editing at http://gijgo.com/Temp/dc86359e-b291-46d7-9260-5216ff7851c0.html

You can also use cellDataBound in order to do it. You can see a demo at http://gijgo.com/Grid/Events/cellDataBound

**Comment by Ankitmane1512** [comment]
If I add dropdown listitems dynamically then I am not getting the selected value of dropdown list.
Please help.


function edit($container, currentValue) {
                var ddlSupplier = "";
                //$container.append('<select><option>one</option><option>two</option></select>');
                $.ajax({
                    type: "GET",
                    url: "/Master/AllSupplier",
                    datatype: "Json",
                    success: function (data) {
                        $.each(data, function (index, value) {
                            ddlSupplier = ddlSupplier + "<option>" + value.Name + "</option>";
                        });                                                
                        $container.append('<select>' + ddlSupplier + '</select>');
                    }
                });
            }

**Comment by atatanasov** [comment]
I answered this question in https://github.com/atatanasov/gijgo/issues/20

**Comment by Ankitmane1512** [comment]
Thanks alot it is working now.

**Comment by Ankitmane1512** [comment]
Can i get more examples for same  Gijgo grid ?
Few things i remember
1. Opening Pop up on grid cell and updating value back to cell.

**Comment by atatanasov** [comment]
You can see such demo at http://gijgo.com/Grid/Demos/FormattingSample. This demo shows you how you can implement only the UI logic. You will need to implement the backend logic.
