### ISSUE TITLE
bootstrap responsive

### ISSUE THREAD

**Issue by pentexsoft** [atatanasov/gijgo#190]
I notice the bootstrap responsive examples are not in rows/columns for bootstrap
when I add the grid to a the bootstrap row and column class is does not resize according to the new width.

am I doing something wrong?

        <div class="row">
            <div class="col-xs-7 col-sm-7 col-md-6 col-lg-5">

                <table id="mygrid"></table>

            </div>
        </div>

**Comment by atatanasov** [comment]
I think that you have to set width=100% in order to achieve that.

```
$('#grid').grid({
    width: '100%'
});
```

**Comment by pentexsoft** [comment]
setting width to 100% has the same result. the header is in the same column layout as the grid and the grid does not resize.

![image](https://user-images.githubusercontent.com/32546238/32216718-128247ee-bdfc-11e7-89e8-5c0e43b7094e.png)

**Comment by atatanasov** [comment]
The grid is based on HTML table and you should be able to do everything with it. I recommend you to inspect the html dom tree in this case and apply appropriate css classes in order to achieve your desired design.

**Comment by pentexsoft** [comment]
was able to find the issue. 
one column needs to be set to '100%' in order for the grid to be responsive. 
thanks.
