### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by bahmansh** [atatanasov/gijgo#191]
Hi my friend
I need to load node's childs on expanding. I know that you are working on it.
So i wanna know when you will release new version including lazy loading?

I think that it's one of most important features in tree view.

**Comment by atatanasov** [comment]
Hello,

Yes. We are working on this. We are planning to release this with the next version (1.7.0) in early December.

Thanks for the feedback.

**Comment by atatanasov** [comment]
We added support for lazy loading in our new development version. You can see an example at https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.LazyLoading.lazyLoading.Material.Design.html

Let us know if you have any questions. Please use the latest development build from https://github.com/atatanasov/gijgo/tree/master/dist
