### ISSUE TITLE
Tree - NodeDrop - OrderNumber

### ISSUE THREAD

**Issue by clnst8** [atatanasov/gijgo#192]
When running the drag and drop sample, the order number being reported after a drop seems off.  For example, if I expand Europe and drag England to below Germany, Bulgaria, or Poland, the orderNumber returned is always 3.  I would expect the order number would be 2 if dropped after Germany, 3 if dropped after Bulgaria, and 4 if dropped after Poland.

**Comment by atatanasov** [comment]
We are going to check that and get back to you soon.

**Comment by atatanasov** [comment]
This is fixed in the new development version. You can find the latest dev build at https://github.com/atatanasov/gijgo/tree/master/dist
