### ISSUE TITLE
TreeView Drag And Drop - Order Number

### ISSUE THREAD

**Issue by Harwidner** [atatanasov/gijgo#194]
We are facing the issue, where we are getting wrong order number of the dropped node while dragging and dropping.

We already raised the issue (Ticket Ref: Tree - NodeDrop - OrderNumber #192)  which is actually closed, but even after taking latest JS(gijgo v1.7.0) and CSS file we are getting the same issue again.

**Comment by atatanasov** [comment]
Are you using the same replication steps as described in #192? I'm not able to replicate the issue again with the steps in #192. Could you double check for cached files

**Comment by Harwidner** [comment]
Yes, with same repro steps we are facing the issue. Even after cleaning the cached files we are facing the issue.

**Comment by Harwidner** [comment]
I have recorded video of the issue and uploaded it at https://www.screencast.com/t/3xRvfPkt4JR.
You can check the repro step. We modified the online example with gijgo.js v1.7.0  and gijgo.css v1.7.0. 

Please give a look and let us know if we are missing anything.

**Comment by Harwidner** [comment]
@atatanasov any update on this ????

**Comment by atatanasov** [comment]
I fixed the issue in the new development version. You should be able to see a working example at http://gijgo.com/Temp/4a929b30-1d08-4a1f-b4d5-847e171b6871.html

**Comment by Harwidner** [comment]
@atatanasov checked.... it's working now (Y)
