### ISSUE TITLE
Tree - Load Data Checked Status Problem

### ISSUE THREAD

**Issue by skylife77** [atatanasov/gijgo#196]
Hi,

When the parent item has checked value true, the children are checked too although in datasource children items has a value false as checked.

Thanks.

![image](https://user-images.githubusercontent.com/33703580/32862269-a423ed10-ca68-11e7-91e5-0b3732dde041.png)

Example DataSource:
[{"id":3,"text":"Management Settings","URL":null,"Icon":"fa fa-gears","Sequence":999,"ischecked":false,"children":[{"id":4,"text":"Configuration Settings","URL":null,"Icon":"fa fa-gear","Sequence":999,"ischecked":false,"children":[]},{"id":16,"text":"System Logs","URL":null,"Icon":"fa fa-text","Sequence":999,"ischecked":false,"children":[]}]},{"id":5,"text":"Assessments","URL":null,"Icon":"fa fa-check-square-o","Sequence":999,"ischecked":true,"children":[{"id":6,"text":"Assessment List","URL":null,"Icon":"fa fa-check-square","Sequence":999,"ischecked":true,"children":[{"id":7,"text":"Create Assessment","URL":null,"Icon":null,"Sequence":999,"ischecked":false,"children":[]},{"id":8,"text":"Update Assessment","URL":null,"Icon":null,"Sequence":999,"ischecked":false,"children":[]},{"id":9,"text":"Delete Assessment","URL":null,"Icon":null,"Sequence":999,"ischecked":false,"children":[]}]},{"id":10,"text":"Assessment Item List","URL":null,"Icon":null,"Sequence":999,"ischecked":false,"children":[{"id":11,"text":"Update Assessment Item","URL":null,"Icon":null,"Sequence":999,"ischecked":false,"children":[]},{"id":12,"text":"Create Assessment Item","URL":null,"Icon":null,"Sequence":999,"ischecked":false,"children":[]}]}]},{"id":13,"text":"User & Client","URL":null,"Icon":"fa fa-users","Sequence":999,"ischecked":false,"children":[{"id":14,"text":"User Client List","URL":null,"Icon":"fa fa-users","Sequence":999,"ischecked":false,"children":[]}]},{"id":15,"text":"Admin Dashboard","URL":null,"Icon":"fa fa-dashboard","Sequence":999,"ischecked":false,"children":[]},{"id":17,"text":"Feedback Module","URL":null,"Icon":"fa fa-reply","Sequence":999,"ischecked":false,"children":[{"id":18,"text":"Feedback List","URL":null,"Icon":"fa fa-reply","Sequence":999,"ischecked":false,"children":[{"id":19,"text":"Create Feedback","URL":null,"Icon":null,"Sequence":999,"ischecked":false,"children":[]},{"id":20,"text":"Update Feedback","URL":null,"Icon":null,"Sequence":999,"ischecked":false,"children":[]}]},{"id":21,"text":"Feedback Topic List","URL":null,"Icon":"fa fa-tag","Sequence":999,"ischecked":false,"children":[{"id":22,"text":"CRUD Feedback Topic","URL":null,"Icon":null,"Sequence":999,"ischecked":false,"children":[]}]}]},{"id":23,"text":"Articles","URL":null,"Icon":"fa fa-text","Sequence":999,"ischecked":false,"children":[{"id":24,"text":"Article List","URL":null,"Icon":"fa fa-text","Sequence":999,"ischecked":true,"children":[{"id":25,"text":"Article CRUD","URL":null,"Icon":null,"Sequence":999,"ischecked":false,"children":[]}]}]}]

**Comment by skylife77** [comment]
Editing like this, solved my problem:

![image](https://user-images.githubusercontent.com/33703580/32885077-7d35112e-cacd-11e7-93d3-2bd8c92faab4.png)

**Comment by atatanasov** [comment]
You just need to set cascadeCheck to false in order to do that. You can see an example at http://gijgo.com/tree/configuration/cascadeCheck

**Comment by atatanasov** [comment]
ok. I saw the issue and fix the issue in the new development version. Thanks for the contribution to the project.

**Comment by skylife77** [comment]
Thank you
