### ISSUE TITLE
Blank column

### ISSUE THREAD

**Issue by aimi617** [atatanasov/gijgo#197]
Is it possible to hide blank column in the grid and show one if any data will present using Ajax data source?

**Comment by atatanasov** [comment]
You can use http://gijgo.com/grid/methods/showColumn and http://gijgo.com/grid/methods/hideColumn methods in order to build your own logic that is doing that.

**Comment by aimi617** [comment]
Thank you, I reviewed those grit methods and will use ones in my logic.
