### ISSUE TITLE
getDataById will not work correctly without node type param

### ISSUE THREAD

**Issue by Hayko-1** [atatanasov/gijgo#199]
https://github.com/atatanasov/gijgo/blob/da0977ddc03d3c87507118a98e353611dc2e9a09/src/tree/js/tree.base.config.js#L170

**Comment by atatanasov** [comment]
I'm not able to understand what exactly you mean. Could you give me some code snippets that I can use to replicate the issue.

**Comment by atatanasov** [comment]
I will close this issue for now. Please reopen the issue if you can provide code snippet that could be in use for replication of the ticket
