### ISSUE TITLE
Gijgo Grid DropDown Problem

### ISSUE THREAD

**Issue by Ankitmane1512** [atatanasov/gijgo#20]
I have added dropdown list in grid.It is working fine for hardcoded values but,when i try to get values dynamically it is not  binding in dropdown.

Here is my code,

function edit($container, currentValue) {
var ddlSupplier = "";
$.ajax({
type: "GET",
url: "/Master/AllSupplier",
datatype: "Json",
success: function (data) {
$.each(data, function (index, value) {
ddlSupplier = ddlSupplier + "" + value.Name + "";
});
$container.append('' + ddlSupplier + '');
}
});
}

Please help.

**Comment by atatanasov** [comment]
You can see a working example at http://gijgo.com/Temp/92ec1eb5-df5b-49db-8be3-a218a5d96c5e.html.

You can see all changes when you click on the "Get Changes" button

**Comment by Prithiraj** [comment]
Hi Atatanasov,

I am trying to figure out the JSON returned from the GET method within the example you shared. Could you please fix the example as this isn't working anymore. I would like to have different controls inside the grid and dropdown is one important input control among these.

Many Thanks, :+1: 
Prith

**Comment by atatanasov** [comment]
Hi Prithiraj,

This is a link to the fixed demo -> http://gijgo.com/Temp/2ee6e09e-3cd7-48e3-85a1-8e931c081c91.html

The path to the dataSource is changed. That's why the old demo doesn't work.

**Comment by Prithiraj** [comment]
Hi Atatanasov,

Thank you for the reply. I have successfully implemented the dropdown in edit. On cellDataBound event I populated the column with a returned text.

Now once I go for editing, the currentvalue stays undefined. When I click on the cell a dropdown element is built within and it shows the top element. When clicked the user would expect to see that value selected in the dropdown. 

Question is once we click the field, how to get the item stay selected in the dropdown?

Regards,
Prith

**Comment by Prithiraj** [comment]
FYI, the above query is for custom dropdown columns. Means, it's a field where the values are added inside cellDataBound event.

**Comment by atatanasov** [comment]
Can you share the code? I can't help you without looking at the code.

**Comment by Prithiraj** [comment]
`     var grid;
     
     function edit($container, currentValue) {
	$container.append('<input type="text" value="' + currentValue + '"/>');
     }
     grid = $('#grid').grid({
         primaryKey: 'ID',
         dataSource: 'GetPlayers.json',
	 columns: [ { field: 'ID' }, { field: 'Name', editor: true }, { field: 'PlaceOfBirth', editor: edit }, { field: 'UniqueKey', editor: edit } ]

     });
     grid.on('rowDataBound', function (e, $row, id, record) {
	console.log(record.Name);    	
	if (record.Name === 'Hristo Stoichkov') {
        	$row.css('background-color',  '#AAAAAA');
    	}
     });
     grid.on('cellDataBound', function (e, $displayEl, id, column, record) {	   
	if ('UniqueKey' === column.field) {
		recId=record.ID;
		recName=record.Name;
		recBirth=record.PlaceOfBirth;
		$displayEl.text(recId+recName.substring(0,3)+recBirth.substring(0,3));
         }
     });`

Once you click on the custom field for editing, the value inside sets to "undefined". This wouldn't exist when the field value is from the server directly. But still I thought if this might be improved. Personally, not important right now, as I removed the custom field and placed the default field instead.

**Comment by atatanasov** [comment]
We fixed that issue in the new development version. You can find the builds at https://github.com/atatanasov/gijgo/tree/master/dist

You are having this issue with the current version, because this is not part of the dataSource that is received in the grid from the backend. You can resolve this if you build the UniqueKey column values on the server and not use javascript to assemble them. This is the only work arround if you don't want to upgrade to new version.
