### ISSUE TITLE
Firefox 57 Quantum

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#200]
There are "Warnings" in the web console by jquery3x and Gijgo.

**Comment by atatanasov** [comment]
I'm browsing through some gijgo examples for the tree, grid and datepicker and can't see these warnings. Could you give me more details how can I find them.

**Comment by stvowi** [comment]
I will send you you the messages if I see the warnings again. I have to try out your last development version yet.

**Comment by atatanasov** [comment]
ok. I will close the ticket for now. Could you reopen it if you see the message again.
