### ISSUE TITLE
config.checkedField conflict with cascadeCheck

### ISSUE THREAD

**Issue by rabbal** [atatanasov/gijgo#201]
Hi,
although I set cascadeCheck with false value, but when I use checkedField, all of nodes are selected.

` var $tree = $("#permissions").tree({
            primaryKey: 'Name',
            textField: 'DisplayName',
            childrenField: 'Children',
            checkedField:'Selected',
            uiLibrary: 'bootstrap',
            iconsLibrary: 'fontawesome',
            dataSource: @Html.Raw(Model.Permissions.ToJson()),
            checkboxes: true,
            cascadeCheck: false
        });`

dataSource is this:

`[{"Name":"Pages","DisplayName":"صفحات","Description":null,"Selected":true,"Parent":null,"Children":[{"Name":"Pages.Administration","DisplayName":"پنل مدیریت","Description":null,"Selected":true,"Children":[{"Name":"Pages.Administration.Roles","DisplayName":"مدیریت گروه های کاربری","Description":null,"Selected":true,"Children":[{"Name":"Pages.Administration.Roles.Create","DisplayName":"ثبت گروه کاربری جدید","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.Roles.Delete","DisplayName":"حذف گروه کاربری","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.Roles.Edit","DisplayName":"ویرایش گروه کاربری","Description":null,"Selected":false,"Children":[]}]},{"Name":"Pages.Administration.Users","DisplayName":"مدیریت کاربران","Description":null,"Selected":true,"Children":[{"Name":"Pages.Administration.Users.Create","DisplayName":"ثبت کاربر جدید","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.Users.Delete","DisplayName":"حذف کاربر","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.Users.Edit","DisplayName":"ویرایش کاربر","Description":null,"Selected":false,"Children":[]}]},{"Name":"Pages.Administration.Customers","DisplayName":"مدیریت مشتریان","Description":null,"Selected":true,"Children":[{"Name":"Pages.Administration.Customers.Create","DisplayName":"ثبت مشتری جدید","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.Customers.Delete","DisplayName":"حذف مشتری","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.Customers.Edit","DisplayName":"ویرایش مشتری","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.Customers.ModelingTemplates","DisplayName":"مشاهده لیست الگوهای مشتری","Description":null,"Selected":false,"Children":[]}]},{"Name":"Pages.Administration.ModelingTemplates","DisplayName":"مدیریت الگوهای مشتریان","Description":null,"Selected":true,"Children":[{"Name":"Pages.Administration.ModelingTemplates.Create","DisplayName":"ثبت الگو برای مشتری","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.ModelingTemplates.Delete","DisplayName":"حذف الگوی مشتری","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.ModelingTemplates.Edit","DisplayName":"ویرایش الگو مشتری","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.ModelingTemplates.Build","DisplayName":"ساخت الگوی مشتری","Description":null,"Selected":false,"Children":[]}]},{"Name":"Pages.Administration.PreMadeTemplates","DisplayName":"مدیریت الگوهای پیش ساخته","Description":null,"Selected":true,"Children":[{"Name":"Pages.Administration.PreMadeTemplates.Create","DisplayName":"ثبت الگوی پیش ساخته جدید","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.PreMadeTemplates.Delete","DisplayName":"حذف الگوی پیش ساخته","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.PreMadeTemplates.Edit","DisplayName":"ویرایش الگوی پیش ساخته","Description":null,"Selected":false,"Children":[]},{"Name":"Pages.Administration.PreMadeTemplates.Build","DisplayName":"ویرایش الگوی پیش ساخته","Description":null,"Selected":false,"Children":[]}]}]}]}]`

**Comment by atatanasov** [comment]
This issue is fixed in the development version. Please use the new development build that is located at https://github.com/atatanasov/gijgo/tree/master/dist

Other users found that problem a few days ago and we fixed that already https://github.com/atatanasov/gijgo/issues/196
