### ISSUE TITLE
Using this library breaks existing draggable div we use

### ISSUE THREAD

**Issue by cameronmolyneux** [atatanasov/gijgo#202]
since upgrading to 1.6.1 a movable toolbar we have in our solution that could be moved anywhere on the screen now seems to be restricted to the div its inside

![image](https://user-images.githubusercontent.com/5611345/33059462-34ebd66a-ce8c-11e7-84ac-af92e071ea4c.png)

any ideas why this might be

**Comment by atatanasov** [comment]
The names of some gijgo wigets/components is the same as in jqueryui. If you want to use jqueryui instead of gijgo for draggable and droppable, then our js file(s) needs to be placed before jqueryui.js
