### ISSUE TITLE
Firefox 57 Quantum error report - development version from yesterday

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#203]
...after loading of the js-files:

+ Modular version:

ReferenceError: reference to undefined property "rowHover"[Weitere Informationen](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Errors/Undefined_prop?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default) grid.js:748:13
ReferenceError: assignment to undeclared variable gj[Weitere Informationen](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Errors/Undeclared_var?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default) core.js:9:5
ReferenceError: assignment to undeclared variable plugin[Weitere Informationen] core.js:82:1
ReferenceError: reference to undefined property "params"[Weitere Informationen] core.js:173:5
ReferenceError: reference to undefined property "expandedRows"[Weitere Informationen] grid.js:1706:1

+ combined version:

ReferenceError: assignment to undeclared variable gj[Weitere Informationen] gijgo.js:9:5
ReferenceError: assignment to undeclared variable plugin[Weitere Informationen] gijgo.js:82:1
ReferenceError: reference to undefined property "cell" [Weitere Informationen] gijgo.js:3741:13
ReferenceError: reference to undefined property "params" [Weitere Informationen] gijgo.js:173:5
ReferenceError: reference to undefined property "rowHover" [Weitere Informationen] gijgo.js:3956:13
ReferenceError: reference to undefined property "field" [Weitere Informationen] gijgo.js:4058:13

**Comment by stvowi** [comment]
P.S.: It's only in the Firefox for Ubuntu - Firefox for Windows say nothing

**Comment by stvowi** [comment]
The messages will produced if  'javascript.options.strict': True, in the browser config.

The topic can be closed.

**Comment by atatanasov** [comment]
I fixed the most of these warnings in the new development version.
