### ISSUE TITLE
EnableAll breaks childs

### ISSUE THREAD

**Issue by SimonTod** [atatanasov/gijgo#204]
I have a multiple level tree which checkboxes
When dynamically loading which nodes should be checked from my backend, I disable the treeview using the next code line:
```javascript
$('#tree').tree().disableAll();
```
Once the data is loaded and all the nodes checked, I enable the tree back with the next code line:
```javascript
$('#tree').tree().enableAll();
```
Now the problem is that this last code line breaks the tree levels. I am still able to open top parents, but not their children.
I will find a way to make what I need work and put it in comments.

Cheers.

**Comment by SimonTod** [comment]
The easiest and fastest way to do this without having to loop inside of the tree is to only disable the checkboxes, This is the only thing I required. I acheived it with the next code lines:
```javascript
$('#tree input[type=checkbox]').prop('disabled', true);
$('#tree input[type=checkbox]').prop('disabled', false);
```
It would still be good it the methods from the plugin could work properly and recursively.

**Comment by samzalahi** [comment]
hi @SimonTod i'm new to programming and i'm using gijgo tree view if you can i have some questions, can u please give me your contact info

**Comment by SimonTod** [comment]
@samzalahi Feel free to ask your questions here. I will try my best to answer and it could halo someone else as well

**Comment by SimonTod** [comment]
What do you mean by `leaf node` ? Are you talking about child nodes ? So you have your treeview displaying, but when you click on a parent node, it doesn't expand to let you see the child nodes ? Am I right ?

**Comment by samzalahi** [comment]
leaf node means a node with no children, i can say last child nodes (final node) of last parent node, my tree is displaying nodes perfectly no problem, i have given a mysql query to not show the leaf nodes (means the files but it will show the folders on tree) on tree, because i wanted to display the leaf node (files) on the same page for example:- as thumbnail next to my tree side bar. (just as simple if we click final folder li it should show the files inside that folder on same page)

**Comment by SimonTod** [comment]
Ok thank you for detailing. So the thing is that your leaf nodes (files) are not in your json from which your treeview is beeing initialised.
What I suggest you do is try to understand how you can use dynamic queries to talk with your database. 
Here is a basic explanation of how it works : 
One the event of a click on a node (folder which you want to display the files), you will use ajax to call a php function
This php function will talk to your database to select what you desire (leaf nodes that have the clicked node as a parent) and will return it as json to your view.
Then back to your view, you will receive files as json, you can then use this to display the data as you want.
Ajax is very easy to use, and it will also help you get your treeview data without having to generate a json file first. I don't know what framework you are using, but any backend language will let you create a function that can be called from ajax.
If you need a more specific code exemple for exemple let me know I will try to help you when I have more time.

**Comment by samzalahi** [comment]
i can share my logic with you correct me if i am wrong, i have to get the selected li ID and i have to make a query to display like "SELECT * FROM table WHERE ID = PARENT_ID and TYPE = 'pdf' "; because the ID will be equal to parent_id of child, am i correct? and i have type column also in db to separate file and folder

**Comment by SimonTod** [comment]
I think it would be the contrary 
```sql
SELECT * FROM table WHERE PARENT_ID = ID and TYPE = 'pdf' 
```
but I am not sure I don't have the structure of your database in front of me.
In any case the query will not be the tricky part for you here

**Comment by samzalahi** [comment]
thank you very much, but the worst part now i could not get the ID of the li, i have made one jquery onclick function, its doing nothing, its not give me the alert is there any wring in my code?
        $(document).ready(function () {
            $('#tree  .list-group-item').on('click', function () {
                alert('Hi ');
            });
        });

**Comment by SimonTod** [comment]
Ok so you should the events given by the plugin.
first you have to initialize your tree inside a viariable, that way you can easily access the methods and events of the plugin.
```js
$(document).ready(function () {
    //initialise your tree in a variable
    var tree = var tree = $('#tree').tree({
        primaryKey: 'id',
        dataSource: //your json file
    });
    //create the event on the click of a node using the plugin events
    //e: event data / node: the node as jquery object / id: the id of the record
    tree.on('select', function (e, node, id) {
        console.log(id);
    });
});
```

**Comment by samzalahi** [comment]
wow its great 👍 , thank you very much for you help, please can u explain me what is happening in this line  tree.on('select', function (e, node, id), and how did u find this one, it is in the event tab i checked it but the way they explained different from that u wrote, sorry to ask like this question still i need more experience i'm just a beginner

**Comment by SimonTod** [comment]
I agree that this event is not well documented on the website
As we can see on [this page](http://gijgo.com/tree/events)
# Select
> Event fires after selection of tree node.

Then they give parameters : 

- e: event data
- node: the node as jquery object
- id: the id of the record

But in the code example, they don't even use it. The exemple of the event use is not there at all. But if it was there they would have done like I showed you. You can try `console.log([e, node, id])` to see how each parameter is returned.

**Comment by samzalahi** [comment]
please if u dont mind can u tell me what do u mean by this one you wrote me before, i did not get it,
"Ajax is very easy to use, and it will also help you get your treeview data without having to generate a json file first" and thank you very much for your support man it was very helpful you r great 👍

**Comment by SimonTod** [comment]
You explained to me that you could not get data from the database directly using the gijgo plugin.
Well if you point your `dataSource` parameter to a url that triggers a php function. This php function will be able to get your data from the database and then return your required json without having to create a file.

**Comment by samzalahi** [comment]
@SimonTod Thank you for that, ill try to do that like you said

**Comment by SimonTod** [comment]
This is what they do on the exemple on [this page](http://gijgo.com/tree)
```js
var tree = $('#tree').tree({
    primaryKey: 'id',
    dataSource: '/Locations/Get',
    imageUrlField: 'flagUrl'
});
```
the dataSource paramter is a url. If you go the [the url](http://gijgo.com/Locations/Get) you will see that it returns the json

**Comment by samzalahi** [comment]
@SimonTod do you have any idea how i can archive that in php?

**Comment by SimonTod** [comment]
A simple way to do this is to create a php file name `GetTree.php` for exemple and put it at the root of your web project. 
Then to connect to the database, make queries, and return the result, you should have a look at the [php pdo documentation](http://php.net/manual/en/book.pdo.php)
When your php file will be done, all you will have to do is change your `dataSource` property to this: `/GetTree.php`

**Comment by samzalahi** [comment]
Thank you very much @SimonTod ill work on that, it great to talk you mate 👍

**Comment by SimonTod** [comment]
My pleasure. Code safe ! 👍 =)

**Comment by samzalahi** [comment]
Hey @SimonTod  i have tried that it works, but its taking almost 1 min to fetch data from database, i have more 4000 rows in my database for tree, any solutions?

**Comment by SimonTod** [comment]
Ok I understand, the problem obviously is the amout of data in your table.
What you can do is use a json file like you did before.
But in case you have any modifications in your table, you should regenerate that file using the php file.
You could for exemple make a scheduled task (cron on linux) that will execute your php file every once in a while. Or find a way to execute that php file everytime there is a change in the table (I don't really know how to do that or if it is possible).

**Comment by samzalahi** [comment]
thats how i did for that json file, i have created php file to create json file from database, but i did not give that schedule things, ill try that thank you mate

**Comment by atatanasov** [comment]
We are going to improve the documentation for the select event. Thanks for the feedback.

**Comment by samzalahi** [comment]
@SimonTod, hi, i need to expand and collapse ul in one click in treeview, i was trying something like this ` tree.on('select', function (e, node, id) {
        var child = $(node).find("ul");
        if (!child.length) {
            getChild(id);
        } else {
            tree.expand(node);
        }
    });` but it is only giving me the expand not collapse, i know this code only work like this, but its hard to figure out to me, do u have any ideas about this?

**Comment by SimonTod** [comment]
Well normally you should use the expand button on the left of items that have children. And the select event should be used for something else that expand/collapse. There is no method given by the plugin to know if a parent node is expanded or not. So this is a little tricky. Sorry for not giving you the solution you want this time

**Comment by SimonTod** [comment]
![image](https://user-images.githubusercontent.com/12744731/33872937-523980e4-df19-11e7-9497-341056cc69cb.png)
See on this example, you have expand/collapse buttons on the select. And the user can select a node. The selection can be used for example if you have a submit button, it will retrieve the item(s) selected to use it one way or another.

**Comment by samzalahi** [comment]
i see, but normally users will click the li name only to expand and collapse not the icons right, i must fix this, anyway thank you very much for the reply mate. @atatanasov help me with this issue please

**Comment by atatanasov** [comment]
@SimonTod - I finally started to work on this issue and I'm not able to replicate the issue. Could you try with the latest stable release 1.8.0. Can you send me a code snippet that I can use for replication of the issue?

**Comment by atatanasov** [comment]
I will close the issue. Please reopen if you can provide a code snippet that I can use for replication of the issue.

**Comment by samzalahi** [comment]
@atatanasov hey, is there any way to expand or collapse the node by click the li instead of node icon?

**Comment by atatanasov** [comment]
@samzalahi - You can call the expand method (http://gijgo.com/tree/methods/expand) in the select event (http://gijgo.com/tree/events/select) in order to do that.

**Comment by aqsa7** [comment]
How to limit children's depth? I want only one level, a child should not have children.
