### ISSUE TITLE
Grid Error Local Data 

### ISSUE THREAD

**Issue by tanerkar** [atatanasov/gijgo#205]
Hi, 
I Used version 1.6

I get the error. Compatible with HTML headers. The area where the fault is received is below.

Error Line:
gj.widget.prototype.reload = function (params) {
    var ajaxOptions, result, data = this.data(), type = this.data('type');
    if (data.dataSource === undefined) {
this error -->       gj[type].methods.useHtmlDataSource(this, data);
    }

**Comment by tanerkar** [comment]
I solved the problem. 
I'm dealing with a different problem.

![getdata](https://user-images.githubusercontent.com/13457289/33133238-3701b0ec-cfad-11e7-984f-b1427194945e.gif)

**Comment by atatanasov** [comment]
Please follow our example at http://gijgo.com/grid/demos/html-sourced-data in order to fix your issue
