### ISSUE TITLE
您好，grid是否提供一个做合计的方法

### ISSUE THREAD

**Issue by tangwangcheng** [atatanasov/gijgo#206]
当我从服务端获取的数据展示在grid中时，我想要合计其中一个数字列的数值总和的时候，我不知道怎么解决，我使用您的grid将近半年啦，但我自己使用起来还有些困难，希望您能提供一些学习grid的方法，来提升我的技能，我特别想知道您是怎样做统计数字的总和？

**Comment by atatanasov** [comment]
Hello,
I don't know Chinese. Could you translate the title and description in English.

**Comment by atatanasov** [comment]
Please reopen it if you translate the description in english
