### ISSUE TITLE
DatePicker in a bootstrap4 dialog

### ISSUE THREAD

**Issue by geeknation** [atatanasov/gijgo#208]
the dates box seem to appear behind the dialog box overlay when you click on the calendar icon
![image](https://user-images.githubusercontent.com/1990373/33491288-c80ebc14-d6ca-11e7-90d9-660fcd3c741b.png)

**Comment by atatanasov** [comment]
You have to increase the z-index in order to fix that. You can control this index with the  .gj-calendar css class.

`
.gj-calendar {
        z-index: 999;
}
`

Here is the example http://gijgo.com/Temp/c8a6de26-08f8-43fd-8d0b-428e55548b93.html
