### ISSUE TITLE
how to set min/max date with specific time

### ISSUE THREAD

**Issue by nobutsta** [atatanasov/gijgo#209]
Hi,
According to the documentation. I only see the option of 'days' ahead. But no (or I can't see) where is the specific setting of dates.

```
        maxDate: function() {
            var date = new Date();
            date.setDate(date.getDate()+1);
            return new Date(date.getFullYear(), date.getMonth(), date.getDate());
        }
```

**Comment by atatanasov** [comment]
I'm not sure that I understand your goal. Could you give me an example.

**Comment by atatanasov** [comment]
I will close this issue. Please reopen it if you can provide more information about it.
