### ISSUE TITLE
Issue with grid paging and drop down inside form element

### ISSUE THREAD

**Issue by lafemme8** [atatanasov/gijgo#211]
Hi Atatanasov,

I have the grid working as expected with paging within my html page.  However if I add it inside of a form element, whenever I click on the page drop down to change size the whole page refreshes.  I'm using Bootstrap ui and referenced it correctly.  The drop down issue also occurs if it's within a form element.  When it is outside it doesn't happen.  

Here is snippet of my code:  
` <form>
    <div class="container-full">
        <div class="row">
            <div class="col-xs-8">
               
                    <div class="form-group">
                        <input id="txtTitle" type="text" placeholder="Title..." class="form-control" />
                    </div>
                    <button id="btnSearch" type="button" class="btn btn-default">Search</button>
                    <button id="btnClear" type="button" class="btn btn-default">Clear</button>
              
            </div>
            <div class="col-xs-4">
                <button id="btnAdd" type="button" class="btn btn-default pull-right">Add New Record</button>
            </div>
        </div>
        <div class="row" style="margin-top: 10px">
            <div class="col-xs-12">
                <table id="grid"></table>
            </div>
        </div>
    </div>
    </form>
<script type="text/javascript">
 $(document).ready(function () {
            grid = $('#grid').grid({
                primaryKey: 'ID',
                dataSource: '/Api/Test',
                uiLibrary: 'bootstrap',
                columns: [
                    { field: 'title', title: 'Title',  sortable: true },
                    { field: 'description', title: 'Description', sortable: true },
                    { field: 'publishdate', title: 'Issue Date', sortable: true },
                    { title: '', field: 'Edit', width: 34, type: 'icon', icon: 'glyphicon-pencil', tooltip: 'Edit', events: { 'click': Edit } },
                    { title: '', field: 'Delete', width: 34, type: 'icon', icon: 'glyphicon-remove', tooltip: 'Delete', events: { 'click': Delete } }
                ],
                pager: { limit: 20, sizes: [10, 20, 50, 100] }
            });
            grid.reload({title: ''})

`
Thanks.

**Comment by atatanasov** [comment]
We fixed that in the new development version. You can get the new development version from https://github.com/atatanasov/gijgo/tree/master/dist

**Comment by lafemme8** [comment]
Thanks very much works great now.

“Forgiveness simply means loving someone enough to pursue healing instead of punishment when they have wronged you.”― Dave Willis
 

    On Thursday, December 7, 2017, 2:35:05 AM EST, Atanas Atanasov <notifications@github.com> wrote:  
 
 
We fixed that in the new development version. You can get the new development version from https://github.com/atatanasov/gijgo/tree/master/dist

**Comment by ObadMahrous** [comment]
Hello, i need to set page number format is dropdown not text box

**Comment by ObadMahrous** [comment]
and need to make max limit for dropdown page number by total number of records divided by page rows count
