### ISSUE TITLE
Dropdown - missing properties "height" & "scrollable"

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#219]
I my opinion the widget can only manage little lists on the screen in forms, isn't it?
There should be the possibility to define the height of the list and to show a scrollbar or little [pager.](https://th3silverlining.com/2010/04/15/pajination-a-jquery-pagination-plugin/)

**Comment by atatanasov** [comment]
We added maxHeight configuration option in the new development version. You can see some examples at https://github.com/atatanasov/gijgo/blob/master/examples/dropdown/DropDown.Base.maxHeight.Fixed.html
https://github.com/atatanasov/gijgo/blob/master/examples/dropdown/DropDown.Base.maxHeight.Auto.html

This is going to resolve your issue. We are going to release the new version later today.

**Comment by stvowi** [comment]
thanks, be blessed
