### ISSUE TITLE
Feature Request : Add Inline Search - with data bound to controls - Drop Down, Calendar  & Etc

### ISSUE THREAD

**Issue by PulkitChoudhary** [atatanasov/gijgo#22]
How can we add a inline search in responsive grid and use different controls to filter/search data 

Features request  - 

- Can Search on column 1, Then further on Column 2(Kind of a filter on each column)

- Can use drop down control, calendar control to pick values for filtration.
- Also, if we can reorder columns by drag n drop will be awesome.

You can see a screen for reference here - 
![image](https://cloud.githubusercontent.com/assets/20884367/17896178/34d47324-696d-11e6-9162-f136f8f63cc6.png)

Can we achieve above defined functionality in responsive grid - 
![image](https://cloud.githubusercontent.com/assets/20884367/17896402/2457a628-696e-11e6-9263-3621bb826be8.png)

**Comment by atatanasov** [comment]
column reorder and filters in the header are not supported yet. This is planned for future versions.
You can use some of the free datepicker plugin from the web. You can see some of them at https://www.google.bg/?q=bootstrap%20datepicker
