### ISSUE TITLE
Server error while accessing documentation of "Configuration.column.events"

### ISSUE THREAD

**Issue by VivekHarikrishnan** [atatanasov/gijgo#223]
I am getting "Server Error/Compilation Error" while accessing the below URL,
http://gijgo.com/Grid/configuration/column.events

![image](https://user-images.githubusercontent.com/1921721/34336358-6bbd015e-e97c-11e7-8e3f-f2c4763771a8.png)

**Comment by atatanasov** [comment]
We just fixed that. Thanks for the feedback.
