### ISSUE TITLE
Grid check-boxes don't show correctly when 'uiLibrary' is 'bootstrap4'

### ISSUE THREAD

**Issue by mehrta** [atatanasov/gijgo#224]
Grid Checkboxes doesn't show correctly when 'uiLibrary' is bootstrap4
![err](https://user-images.githubusercontent.com/34556599/34402592-c1bfa6e6-ebb7-11e7-8295-51c4955ca9f1.PNG)

**Comment by atatanasov** [comment]
Could you recreate this issue in codepen.io or jsfiddle.net. Everything works fine in our example at http://gijgo.com/grid/demos/bootstrap-grid-inline-edit

**Comment by atatanasov** [comment]
I will close this issue. Please reopen it if you can provide replication steps
