### ISSUE TITLE
Bootstrap 4 beta 3 breaks the datepicker input-group

### ISSUE THREAD

**Issue by FrankGag** [atatanasov/gijgo#226]
Hi,

The new release of Bootstrap 4 beta 3 introduces a breaking changes in input-groups.
https://getbootstrap.com/docs/4.0/migration/#input-groups

TL;DR : 
`<div class="input-group-append"><span class="input-group-text"><i class='fa fa-calendar' aria-hidden="true"></i></span></div>`
instead of 
`<span class="input-group-addon"><i class='fa fa-calendar' aria-hidden="true"></i></span>`

Thanks,
Frank

**Comment by atatanasov** [comment]
Thanks for reporting this issue. We are working on this.

**Comment by atatanasov** [comment]
This is going to be fixed in the new version that is going to be released pretty soon
