### ISSUE TITLE
Row removal bug?

### ISSUE THREAD

**Issue by fbengo** [atatanasov/gijgo#227]
Gijgo keeps removing a row when the user clicks the inline 'delete' button and cancels it afterwards. How can I prevent Gijgo from removing this record from the grid, when users cancel row removal? I don't want to refetch the grid data, since nothing changed...

**Comment by atatanasov** [comment]
Could you give me an example. In the example below this is working fine. http://gijgo.com/grid/demos/ajax-sourced-data

**Comment by atatanasov** [comment]
I'm closing the issue. I will reopen it if you provide a link where I can replicate this issue.

**Comment by vsile** [comment]
I have the same problem!
