### ISSUE TITLE
New node of the current node, if the current node has no child nodes, error! Bug?

### ISSUE THREAD

**Issue by lzb66855024** [atatanasov/gijgo#229]
New node of the current node, if the current node has no child nodes, error!
New node of the current node, if the current node has no child nodes, error!

**Comment by lzb66855024** [comment]
New node of the current node, if the current node has no child nodes, error!
New node of the current node, if the current node has no child nodes, error!

**Comment by lzb66855024** [comment]
![default](https://user-images.githubusercontent.com/22442767/34557859-9483344e-f176-11e7-92b8-5001d264e5dc.png)

**Comment by lzb66855024** [comment]
![default](https://user-images.githubusercontent.com/22442767/34557891-b6c3ed00-f176-11e7-8eeb-ad8facb235a6.png)

**Comment by atatanasov** [comment]
We fixed that in the new development version. You can find the new build at https://github.com/atatanasov/gijgo/tree/master/dist
