### ISSUE TITLE
Formatting the button in gijgo grid

### ISSUE THREAD

**Issue by jefferyleo** [atatanasov/gijgo#23]
`var tblPackage = $("#tblPackage").grid({
            dataKey: "ID",
            url: '/Admin/GetPlan',
            uiLibrary: "bootstrap",
            columns: [
                { field: "PlanId", sortable: true, hidden: true },
                { field: "PlanName", title: "Plan Name", sortable: true },
                { field: "PlanDescription", title: "Description", sortable: true },
                { field: "StartTimeStamp", title: "Start Time", sortable: true },
                { field: "EndTimeStamp", title: "End Time", sortable: true },
                { field: "Status", title: "Status", sortable: true },
                { field: "Version", title: "Version", sortable: true },
                { title: "", field: "Submit", width: 34, type: "icon", icon: "glyphicon-upload", tooltip: "Submit", events: { "click": Submit } },
                { title: "", field: "Edit", width: 34, type: "icon", icon: "glyphicon-pencil", tooltip: "Edit", events: { "click": Edit } },
                { title: "", field: "Clone", width: 34, type: "icon", icon: "glyphicon-file", tooltip: "Clone", events: { "click": Clone } },
                { title: "", field: "Delete", width: 34, type: "icon", icon: "glyphicon-trash", tooltip: "Delete", events: { "click": Remove } },
                { title: "", field: "View", width: 34, type: "icon", icon: "glyphicon-book", tooltip: "View", events: { "click": View } }
            ],
            pager: { enable: true, limit: 10, sizes: [5,10, 20,50,100] }
        });`

Has anyone know on how to format the button like base on the status, either 'Complete' or 'Pending', then will disable / hide the button? I would appreciate if anyone can help on this.

**Comment by atatanasov** [comment]
You can use the cellDataBound event in order to do that.
You can see an example at http://gijgo.com/Grid/Events/cellDataBound

**Comment by jefferyleo** [comment]
@atatanasov Thanks dude, I did it with your way. Thanks a lot, appreciate.

**Comment by spaceknight** [comment]
@atatanasov 

Hello, can the same event be used for displaying a (Fontawesome) icon?

I have a field called "isFavorite" and would like to display a star icon (<i class="fa-solid fa-star"></i>) if the isFavorite == 1. How would I do that?
