### ISSUE TITLE
Inline editor example with custom edit function

### ISSUE THREAD

**Issue by iang0ld** [atatanasov/gijgo#230]
Can you provide this?

**Comment by atatanasov** [comment]
Here is the example http://gijgo.com/Temp/3205470b-59e7-4411-827f-a0bb3047b1b9.html

**Comment by iang0ld** [comment]
Thank you for this.  However, how is the entered value passed back?

**Comment by atatanasov** [comment]
You can get the updated information with some of the get methods like getAll, getById, etc.

$('#grid').grid('getAll')

You can see our c# examples at https://github.com/atatanasov/gijgo-asp-net-examples

**Comment by iang0ld** [comment]
Got it thank you.



Sent from my Samsung device


-------- Original message --------
