### ISSUE TITLE
Modular build for grid to work with the bootstrap paging fix

### ISSUE THREAD

**Issue by lafemme8** [atatanasov/gijgo#231]
Hi Atatanasov,

I commented on the original issue, but wanted to do a new question.  This is in reference to issue#211 the issue I had with grid paging refreshes.  This works fine when I use the fixed development version of the combined gijgo.js, but when I try to use it for the modular js the behavior remains. I am using the libraries in the following order and downloaded the development version of the dropdown.

<script src="Scripts/jquery-3.2.1.min.js" type="text/javascript"></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js" type="text/javascript"></script> <script src="Scripts/bootstrap.min.js" type="text/javascript"></script> <%-- <script src="Scripts/gijgo/combined/gijgo.min.js" type="text/javascript"> </script>--%> <script src="Scripts/gijgo/modular/core.min.js" type="text/javascript"></script> <script src="Scripts/gijgo/modular/grid.min.js" type="text/javascript"></script> <script src="Scripts/gijgo/modular/dropdown.min.js" type="text/javascript"></script> <script src="Scripts/webflow.js" type="text/javascript"></script>

Is this correct? I only want to utilize the grid from the library, no other widgets.

**Comment by atatanasov** [comment]
Yes. This looks the correct approach. You can try to open in edit mode some of our examples at http://gijgo.com/grid/configuration all of them are using modular build and you can use them as an example.
