### ISSUE TITLE
Local data with render column

### ISSUE THREAD

**Issue by pentexsoft** [atatanasov/gijgo#232]
when adding a row locally (grid.addRow(record);) the render column throws error when trying to access the added row.
I have to run a grid.reload() in order for render column to work on the added row.

I have a edit and delete button in the renderer
that are added this way on load:
....
$displayEl.empty();
$displayEl.append($editBtn).append($deleteBtn); 

{ width: 75, align: 'center', renderer: gridcol_renderer }

each has a click event, the event throws error on the added row locally.
bootstrap4, fontawesome format.

let me know if you need full format.

script error: 'Unable to get property 'children' of undefined or null reference'

**Comment by atatanasov** [comment]
Could you recreate the error in codepen.io or jsfiddle.net or just send me the code that I can use to replicate this error.

**Comment by atatanasov** [comment]
Closing the issue. Please reopen when you provide code sample that I can use for replication.
