### ISSUE TITLE
how to give name and id to each checkbox in tree?

### ISSUE THREAD

**Issue by seniorcandy** [atatanasov/gijgo#233]
the dataSource looks like this
`
{"text": "app", "id": 45, "checked": true, "children": [], "hasChildren": false, "paramNames": 45]}
`
and init the tree
```
$('#tree').tree({
            primaryKey: 'id',
            uiLibrary: 'bootstrap',
            dataSource: full_test_items_tree,
            checkboxes: true,
            lazyLoading: true
        });
```
but it does not give the checkbox any name.
 I read the doc but I'm not sure if I understand it
http://gijgo.com/tree/configuration/paramNames.parentId

**Comment by atatanasov** [comment]
The id is going to be the field name specified in the primaryKey setting.
You can use some of the get methods like getById in order to get the object that represent this tree node. You can specify a name or any other data in the object and use it when you get the node data.

**Comment by atatanasov** [comment]
I will close the issue. Please reopen it if you need more info.
