### ISSUE TITLE
Drag and drop style

### ISSUE THREAD

**Issue by sguedon** [atatanasov/gijgo#238]
I've got some strange behavior on the drag and drop: Not clear from user point of view. The 'drag' or 'drop' is not easy to see.
See attached video, please help.
[2018-01-16_01h42_40.zip](https://github.com/atatanasov/gijgo/files/1633294/2018-01-16_01h42_40.zip)

**Comment by atatanasov** [comment]
Are you using the latest version of the tree? The behaviour in 1.7.3 should be better.

**Comment by sguedon** [comment]
Drag and drop is better but selection not working anymore ...
See video before and after
[Gijgo Issue 238.zip](https://github.com/atatanasov/gijgo/files/1634105/Gijgo.Issue.238.zip)

**Comment by sguedon** [comment]
May I missed a doc update but seems the select event does not fire anymore ...

I'm quite embarrassed...

**Comment by atatanasov** [comment]
I will review the video later. The select event work as expected in the demo at http://gijgo.com/tree/events/select

**Comment by atatanasov** [comment]
I see what you mean. We are going to address this issue in the next release. Thanks for the contribution.

**Comment by atatanasov** [comment]
This is fixed and we are going to add this fix into the next release
