### ISSUE TITLE
Dynamically updated whole datasource

### ISSUE THREAD

**Issue by jubairmpower** [atatanasov/gijgo#239]
Is there any way to get whole datasource updated, after calling addNode() function ??

**Comment by bvmatt** [comment]
I am having an issue related to this also. I have code that adds nodes and then children to those nodes. 

```
if(response.folder.parent_id == -1){
    //Root folders
    masterStructureTree.addNode({ text: response.folder.folder_name, id: response.folder.folder_id });
}else{
    //Child folders
   masterStructureTree.addNode({ text: response.folder.folder_name, id: response.folder.folder_id }, masterStructureTree.getNodeById(getSelectedMasterNode()));
}
```
When adding to a node where the datasource has not been fully updated I get this error

**TypeError: gj.tree.methods.getById(...) is undefined Line 9790**

` gj.tree.methods.getById($tree, $parent.parent().data('id'), $tree.data('records')).children.push(newNodeData);`

Thanks for any help you can provide.

**Comment by atatanasov** [comment]
When you use addNode method you update the data model behind the tree. We are going to add getAll method in the new version where you can get the data model with method. For now you can use $tree.data().records in order to get this info.

**Comment by jubairmpower** [comment]
when I use getNodeById() for retrieving new node  after the operation of  adding nodes in the tree, it gives me this error 
Uncaught TypeError: Cannot read property 'find' of undefined
have you any idea how can i solve these problem ?

**Comment by atatanasov** [comment]
Make sure that you configure correct primaryKey and always pass this primary key when you add a new node. This is an example of how you can do this: http://gijgo.com/Temp/046f50db-b7ba-4126-a778-4107d18cb693.html

**Comment by atatanasov** [comment]
We added getAll method for the tree. You can find it in the new development version located in the dist folder at github.

**Comment by jubairmpower** [comment]
I check that.Its ok. Actually I call addNode() in a ajax call and outside the ajax call I use getNodeById(). I think thats why i did not get the newly added node.. Have you any solution to that??

**Comment by atatanasov** [comment]
getNodeById should work ourside the ajax call. Make sure that getNodeById is called after the addNode method and the primaryKey is added and configured correctly.
