### ISSUE TITLE
How can I dynamically update the text of a tree node

### ISSUE THREAD

**Issue by bvmatt** [atatanasov/gijgo#242]
I have a dialog that allows the user to change the text of a tree node. How can I "refresh" the nodes text without reloading the entire tree?

`var node = masterStructureTree.getNodeById(response.folder.folder_id);`

Something like this would be useful. 
`node.setText(response.folder.folder_name);`

Thanks!

**Comment by atatanasov** [comment]
We are going to add edit function in future version. For now you can use the following:
```
var node = masterStructureTree.getNodeById(response.folder.folder_id);
node.find('[data-role="display"]').text('New Name');
```

**Comment by rabbal** [comment]
this way dose not change data of node in tree.data().records

**Comment by atatanasov** [comment]
I'm going to add an edit method in the next version.

**Comment by atatanasov** [comment]
We added updateNode method in the new development version. For now you can find the new build only in the dist folder at github.

You can find an example at https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Base.updateNode.Method.Sample.html
