### ISSUE TITLE
Problem with event "select" from plagin druganddrop

### ISSUE THREAD

**Issue by kossfogot** [atatanasov/gijgo#243]
Hello! Your project is great! Thank you very much!
But I have problem. Perhaps you can give me the answer.
I see that  plugin  druganddrop (tree) event 'select' is not working.
Sorry. But I have question - why?
This is important event for each function very much.
 I will be happy if you ansver me

**Comment by atatanasov** [comment]
Yes. This is a bug in the latest version. I will close your issue, because this is already reported in https://github.com/atatanasov/gijgo/issues/238. We are going to fix that soon. Stay tuned!
