### ISSUE TITLE
Group by a boolean field: When change the row per page, the first group title disappear.

### ISSUE THREAD

**Issue by qvinh222** [atatanasov/gijgo#246]
Test the code below and try to change the row per page,  you will see the bug: 
var grid, data = [
         { 'ID': 1, 'Name': 'Hristo Stoichkov', 'PlaceOfBirth': 'Plovdiv, Bulgaria', Nationality: 'Bulgaria' , is:"true"},
         { 'ID': 2, 'Name': 'Ronaldo Luís Nazário de Lima', 'PlaceOfBirth': 'Rio de Janeiro, Brazil', Nationality: 'Brazil', is:"true" },
         { 'ID': 3, 'Name': 'David Platt', 'PlaceOfBirth': 'Chadderton, Lancashire, England', Nationality: 'England', is:"true" },
         { 'ID': 4, 'Name': 'Manuel Neuer', 'PlaceOfBirth': 'Gelsenkirchen, West Germany', Nationality: 'Germany', is:"false" },
         { 'ID': 5, 'Name': 'James Rodríguez', 'PlaceOfBirth': 'Cúcuta, Colombia', Nationality: 'Colombia', is:"true" },
         { 'ID': 6, 'Name': 'Dimitar Berbatov', 'PlaceOfBirth': 'Blagoevgrad, Bulgaria', Nationality: 'Bulgaria', is:"false" }
     ];
     $('#grid').grid({
         dataSource: data,
         grouping: { groupBy: 'is' },
         columns: [ { field: 'Name', sortable: true }, { field: 'PlaceOfBirth' } ],
       pager:{limit:2}
     });

**Comment by atatanasov** [comment]
We fixed that in the new development version. You can find the new build in our dist folder at github.
Thanks for the contribution.
