### ISSUE TITLE
selectionMethod: 'checkbox' & selectionType: 'multiple' can't work with grouping:{....}

### ISSUE THREAD

**Issue by qvinh222** [atatanasov/gijgo#247]
check the following code:
var grid, data = [
         { 'ID': 1, 'Name': 'Hristo Stoichkov', 'PlaceOfBirth': 'Plovdiv, Bulgaria', Nationality: 'Bulgaria' , is:"true"},
         { 'ID': 2, 'Name': 'Ronaldo Luís Nazário de Lima', 'PlaceOfBirth': 'Rio de Janeiro, Brazil', Nationality: 'Brazil', is:"true" },
         { 'ID': 3, 'Name': 'David Platt', 'PlaceOfBirth': 'Chadderton, Lancashire, England', Nationality: 'England', is:"true" },
         { 'ID': 4, 'Name': 'Manuel Neuer', 'PlaceOfBirth': 'Gelsenkirchen, West Germany', Nationality: 'Germany', is:"false" },
         { 'ID': 5, 'Name': 'James Rodríguez', 'PlaceOfBirth': 'Cúcuta, Colombia', Nationality: 'Colombia', is:"true" },
         { 'ID': 6, 'Name': 'Dimitar Berbatov', 'PlaceOfBirth': 'Blagoevgrad, Bulgaria', Nationality: 'Bulgaria', is:"false" }
       ,
         { 'ID': 6, 'Name': 'Dimitar Berbatov', 'PlaceOfBirth': 'Blagoevgrad, Bulgaria', Nationality: 'Bulgaria', is:"false" }
     ];
     $('#grid').grid({
        selectionMethod: 'checkbox',
            selectionType: 'multiple',
         dataSource: data,
         grouping: { groupBy: 'is' },
         columns: [ { field: 'Name', sortable: true }, { field: 'PlaceOfBirth' } ],
       pager:{limit:2}
     });

**Comment by atatanasov** [comment]
I can't see what is wrong with it. The select all option of the grid is design to select only the visible records on the page. This option can't select records from pages that are not opened. Is that your issue?

**Comment by atatanasov** [comment]
Closing for now. Please reopen if this is still an issue for you.
