### ISSUE TITLE
Bootstrap 4 datepicker addon calendar button doesn't display properly

### ISSUE THREAD

**Issue by FrankGag** [atatanasov/gijgo#248]
Hi,

The addon height is not right and it's not displayed properly. It seems like the position: absolute of this class breaks  '.gj-datepicker-bootstrap span[role=right-icon] .input-group-text .fa'. The padding also doesn't seem right once the display problem is fixed. The caldendar icon is too far to the right.

Thanks,
Frank

**Comment by atatanasov** [comment]
Could you send me a screenshot and tell me what is the gijgo version and bootstrap 4 version that is in use by you.

**Comment by atatanasov** [comment]
We released a new version earlier today where probably this issue is resolved. Please reopen it if the issue still exists.

**Comment by FrankGag** [comment]
The new version seems to fix the issue, thanks!
