### ISSUE TITLE
Draggable is not working on Android

### ISSUE THREAD

**Issue by centurianii** [atatanasov/gijgo#249]
Android version 4.4.2, kernel 3.4.67.
I don't know what library you use but there is a killer one out there and is called jquerypp. Go use it it's life saver!

PS: I just dropped you a msg for collaboration as Kostas

**Comment by atatanasov** [comment]
Hi,

Can you send me a link to the page that makes this trouble on Android devices. Android 4 is an old version that is not supported by google already and we don't test on it. We don't use nothing that should be a troublemaker for old Android versions.

p.s. I just get back to you on the personal message.

**Comment by atatanasov** [comment]
When I open http://gijgo.com/draggable and test the sample through Chrome on Android 4.4.2 everything looks good. Probably something else is causing your problem. Please double check the issue and reopen it if you can provide more details. 

Thanks you,
Atanas
