### ISSUE TITLE
Other Css Frameworks

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#251]
Is it possible toI use Gijgo controls together with other modern CSS Frameworks (e.g. [Bulma + Jquery + Font Awsome)](https://bulma.io/) than Bootstrap 3/ 4?

There are any pitfalls?

**Comment by atatanasov** [comment]
Hi Stefan,

Gijgo is never tested in combination with Bulma and I have no idea if this is going to work well. If one day Bulma become very popular I can add support for this framework as well, but for now no guarantees. I'm also planning to add in the future examples of how you can add custom styles to gijgo components.

**Comment by stvowi** [comment]
I will test it this year. What I mostly need is the grid component. Bulma have more than 20000 followers. Thanks for the answer.
