### ISSUE TITLE
.grid is not a function

### ISSUE THREAD

**Issue by GOBIBE** [atatanasov/gijgo#252]
Uncaught TypeError: $(...).grid is not a function
this section error will be occured

**Comment by atatanasov** [comment]
This is caused by incorrect inclusion of gijgo.js. Please try to include gijgo.js as the last js file included in this html page. You can also see that this issue doesn't exists in our demos at http://gijgo.com/grid/demos

**Comment by GingerSnap9** [comment]
I'm getting the same error from using *just the code from the example (here: http://gijgo.com/grid ).
I downloaded gijgo from NuGet, and am not sure where to get the gijgo.js file...
