### ISSUE TITLE
Error when i use 'pt-br' or other languages

### ISSUE THREAD

**Issue by brunovb91** [atatanasov/gijgo#253]
My code:

<script src="https://cdn.jsdelivr.net/gh/atatanasov/gijgo@1.8.0/dist/combined/js/gijgo.min.js" type="text/javascript"></script>
<script>
  $('#date').datepicker({
    uiLibrary: 'bootstrap4',
    locale: 'pt-br',
    format: 'dd mmm yyyy'
  });
</script>

This error apears on console at pageload and at click.

Uncaught TypeError: Cannot read property 'monthShortNames' of undefined
    at Object.parseDate (gijgo.min.js:1)
    at Object.createCalendar (gijgo.min.js:1)
    at Object.initialize (gijgo.min.js:1)
    at jQuery.fn.init.init (gijgo.min.js:1)
    at new gj.datepicker.widget (gijgo.min.js:1)
    at jQuery.fn.init.a.fn.datepicker (gijgo.min.js:1)
    at edit:113

**Comment by atatanasov** [comment]
You need to include the file with pt-br messages in order to get it working.
This is the link https://cdn.jsdelivr.net/gh/atatanasov/gijgo@1.8.0/dist/combined/js/messages/messages.pt-br.js

You can see an example at http://gijgo.com/datepicker/example/localization
