### ISSUE TITLE
Grid detail template checkbox check/uncheck not working

### ISSUE THREAD

**Issue by ravihanok** [atatanasov/gijgo#254]
<div class="container-full">
        <div class="row">
            <div class="col-md-12">
                <table id="grid"></table>
            </div>
        </div>
    </div>
 
      grid = $('#grid').grid({
                dataSource: '/Home/GetRisks',
                uiLibrary: 'bootstrap',
                primaryKey: 'Id',
                inlineEditing: { mode: 'command' },
                columns: [
                    { field: 'Id', },
                    { field: 'Name', editor: true },
                    { field: 'IsActive', title: 'Active?', type: 'checkbox', width:35, editor: true, align: 'center' }
                ],
                detailTemplate: '<div><table/></div>',
            });

            grid.on('detailExpand', function (e, $detailWrapper, id) {
                $detailWrapper.find('table').grid({
                    params: { RiskId: id },
                    dataSource: '/Home/GetRiskMitigations',
                    primaryKey: 'Id',
                    inlineEditing: { mode: 'command' },
                    columns: [
                    { field: 'Id' },
                    { field: 'Description', editor: true, },
                    { field: 'IsValid', title: 'IsValid?', type: 'checkbox', editor: false, align: 'center' }
                    ]
                });
            });
From the above code Detail grid is working fine but when i try to click on check box it is not turning to check state.

**Comment by atatanasov** [comment]
The editor option needs to be set to true in order to allow you to edit with the checkbox. Example:
`{ field: 'IsValid', title: 'IsValid?', type: 'checkbox', editor: true, align: 'center' }`

I found a bug with your example. When you expand the details and click edit on the parent my code crash. I fixed that in the new development version. Please use the new build located in the dist folder at github.

**Comment by ravihanok** [comment]
I have even checked with true but unable to check

**Comment by ravihanok** [comment]
I found myself the issue is i combined both bootstrap and MDL styles.Its working as i used only MDL
