### ISSUE TITLE
Grid as tree table

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#256]
There is a nice sample for [nested grids](http://gijgo.com/grid/demos/nested-jquery-grids).

Is it possible to define a detail template (third level rows) in the child table e.g. to show a N:M relationship in one view?

If yes than how?

**Comment by atatanasov** [comment]
Yes. You can enable the expand/collapse (detailTemplate) config option for the nested grid in order to achieve that. We  don't support tree structure for grids and the only way to achieve that is with detailTemplate for each nested level.
