### ISSUE TITLE
Interface Datepicker incorrectly extends interface JQuery<HTMLElement>

### ISSUE THREAD

**Issue by ohcibi** [atatanasov/gijgo#257]
I wanted to contribute the DefinitelyTyped types for gijgo's datepicker but it's interface is wrongly extending jquery. The conflict is on the `show` and `hide` methods which are used to show and hide the datepicker if `datepicker()` was called. I'd simply rename the methods to something like `showDatepicker` as there is indeed a confusion about hiding the element the datepicker has been called on vs hiding the actual datepicker. Afais hiding the original element isn't even possible anymore with the current interface.

If desired i'd be happy to pr the renamed methods.

**Comment by atatanasov** [comment]
You can rename show to showDatepicker for you project temporary. I see what you mean. I will think about it and I will get back to you with long term solution for that problem.

**Comment by atatanasov** [comment]
I renamed show and hide to open and close in the latest development build. You can find the build in my dist folder at github.

You can contribute to DefinitelyTyped at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gijgo
The types are not up to date and you can go ahead and add the datepicker
