### ISSUE TITLE
tree option: parent checkboxes checked automatically when at least one subnode checked

### ISSUE THREAD

**Issue by rabbal** [atatanasov/gijgo#258]
![capture](https://user-images.githubusercontent.com/6818642/36061547-ea18f8d2-0e70-11e8-81e5-6d6317e45a25.PNG)

![capture](https://user-images.githubusercontent.com/6818642/36061313-e1a60f26-0e6d-11e8-9d1e-f72fe46de7ca.PNG)

![capture](https://user-images.githubusercontent.com/6818642/36061527-bceff63a-0e70-11e8-9ff5-c1c507949da0.PNG)

when one of the descendants checked, then it's ancestors must be checked automatically. Eventually, when unchecked all descendants of each ancestor, must not be unchecked ancestor.
note: in this situation, checkboxes should not have indeterminate state.

**Comment by atatanasov** [comment]
You can do that if you set the cascadeCheck to false and control the selection manually through the checkboxChange event.

Here is an example http://gijgo.com/Temp/fb9b4b0f-e376-4a93-b896-f862c5ef8df4.html
