### ISSUE TITLE
Bootstrap Dropdown in the grid

### ISSUE THREAD

**Issue by mmanna3** [atatanasov/gijgo#259]
Hi! Thanks very much for Gijgo! I'm building some humble C# helpers so you can use the grid only with Razor, no need for Javascript in the views. Of course I'm going to share it when it's finished. 

I am having a problem when I try to add a Bootstrap dropdown menu in the rows. I see the button, but when I click on it, the menu doesn't display. There is no Javascript errors and the Bootstrap "dropdown" class changes to "dropdown-open" (as it should do).

This is the HTML and the Javascript generated.

![image](https://user-images.githubusercontent.com/23342135/36067099-2b00e57a-0e95-11e8-918d-efb8fdbeb4fb.png)

![image](https://user-images.githubusercontent.com/23342135/36067119-aa677c0c-0e95-11e8-989e-38e60708377e.png)

**Comment by atatanasov** [comment]
I guess that this issue is caused by small z-index on the dropdown. I think that would be best if you use our dropdown that works well with the grid. You can see a demo at http://gijgo.com/grid/demos/bootstrap-grid-inline-edit

**Comment by mmanna3** [comment]
Thank you very much! I checked all the examples but I didn't realize there was a dropdown in the grid of that one.
