### ISSUE TITLE
Grid column with date type - shows wrong date

### ISSUE THREAD

**Issue by oyvindvol** [atatanasov/gijgo#260]
Hi, I am creating a Gijgo grid, with config and columns like this:

```
var grid = $('#grid').grid({
  dataSource: '@Url.Action("Get")',
  uiLibrary: 'bootstrap',
  primaryKey: 'ExternalId',
  inlineEditing: { mode: 'command' },
  columns: [
    { field: 'ExternalId', hidden: true },
    { field: 'CaseNumber', editor: true },
    { field: 'CaseText', editor: true },
    { field: 'MainPoints', editor: true },
    { field: 'Reference', editor: true },
    { field: 'Deadline', title: 'Frist', type: 'date', format: 'dd.mm.yyyy', editor: true }
  ], 
  pager: { limit: 20 }
});
```

Server side is an ASP.NET Core MVC application. When inspecting the records with breakpoints on the server code, I see that the `Deadline` is `{28.02.2018 00:00:00}` (day, month, year).

When the grid renders, the display value is set to `10.08.1933`.  When I enter edit mode, and open the calendar, the selected date is 8th October 1933.

What am I missing here?

**Comment by atatanasov** [comment]
Could you send me the json response from the server in order to be able to see why the parsing of the date is incorrect.

**Comment by oyvindvol** [comment]
@atatanasov Can i get the json response client side somewhere?

**Comment by oyvindvol** [comment]
In this attachment I am inspecting the json result returning from my `Get` action method. The `records` json node contains 20 objects. I am inspecting the first one, with a `Deadline` field of `28.02.2018 00:00:00`.

But is there somehow I can see the actual json reponse client side, @atatanasov ?

![1](https://user-images.githubusercontent.com/259427/36194800-773166a8-116b-11e8-993b-2b999ea4905b.PNG)

**Comment by atatanasov** [comment]
Yes. You can use Chrome DevTools in order to do that. You can find the response in the network tab. Please send me the response from there. 

Here is the link with more info https://developers.google.com/web/tools/chrome-devtools/

**Comment by oyvindvol** [comment]
Ah, of course. Here`s the response:

```
{
	"records": [{
		"ExternalId": "...",
		"CaseNumber": "23",
		"CaseText": "23",
		"MainPoints": "Hovedpunkter",
		"Reference": "Ref",
		"Deadline": "2018-02-28T00:00:00",
		"Role": "...",
		"DelegeeComment": "..."
	}, {
		"ExternalId": "...",
		"CaseNumber": "22",
		"CaseText": "...",
		"MainPoints": null,
		"Reference": null,
		"Deadline": null,
		"Role": "...",
		"DelegeeComment": null
	}],
	"total": 2
}
```

**Comment by oyvindvol** [comment]
After updating my server code a bit, I now get a json response to the client looking more like the ones in the documentation examples; `"Deadline":"\/Date(1519772400000)\/"`. This now shows the correct date in display mode. But when I change to edit mode, the selected date in the calendar is wrong.

However, if I remove the format config of the column
`{ field: 'Deadline', title: 'Frist', width: 70, type: 'date', format: 'dd.mm.yyyy', editor: true },`
the date shows correctly in display mode (just not in my preferred format), and the correct date is selected in edit mode calendar. 

Should I not be able to change my preferred display format, and still get the correct date selected in calendar in edit mode?

**Comment by atatanasov** [comment]
You had the first issue, because you are trying to parse the yyyy-mm-dd (2018-02-28T00:00:00) format as 'dd.mm.yyyy'. This is posible only in custom renderer like in http://gijgo.com/grid/configuration/column.renderer

I fixed your second problem with inline editing in our new development version. You can find the new build in the dist folder at github. Thanks for the feedback. This was very helpful.

**Comment by oyvindvol** [comment]
@atatanasov Thanks! When will this be a release available at jsdelivr CDN?
