### ISSUE TITLE
Reload tree nodes don't work on IE

### ISSUE THREAD

**Issue by dgsmidt** [atatanasov/gijgo#262]
When reload method is called within internet explorer. Nothing happens.

**Comment by atatanasov** [comment]
Everything works fine on my IE11 when I play with the examples at http://gijgo.com/tree/methods/reload
Could you provide a code snippet that I can use for the replication of this issue.

**Comment by dgsmidt** [comment]
It’s very simple. After each reload of page I use reload() to update categories from database. In Chrome it’s OK, but on my IE11 nothing happens.


$(document).ready(function () {
    var url = $('#tree').data('url');
    var urlChangeNodePos = $('#tree').data('url1');

    var tree = $('#tree').tree({
        uiLibrary: 'bootstrap',
        //iconsLibrary: 'fontawesome',
        border: true,
        checkboxes: false,
        dataSource: url,       //'/Categories/Get',
        primaryKey: 'id',
        imageUrlField: 'imageUrl',
        dragAndDrop: true,
        //selectionType: 'multiple',
        autoLoad: false
    });

    tree.on('select', function (e, node, id) {
        $('#editNode').prop('disabled', false);
        $('#deleteNode').prop('disabled', false);
    });

    tree.on('nodeDrop', function (e, id, parentId, orderNumber) {
        var params = { id: id, parentId: parentId, orderNumber: orderNumber };
        $.ajax({ url: urlChangeNodePos, data: params, method: 'POST' })
            .fail(function () {
                alert('Failed to save.');
            });
    });

    tree.reload();
});

**Comment by atatanasov** [comment]
Your example works pretty good for me in IE 11. Could you compare my test at http://gijgo.com/Temp/c1678da4-d507-4728-bbd7-3d36d4598740.html with your code
Could you check in the IE11 console for some other javascript errors that affect the tree.

**Comment by dgsmidt** [comment]
If i delete temporary internet files (Tools->Options on IE) and refresh the page, it works. Whithout this, my controller action is hitted only once, at the first page load.

**Comment by atatanasov** [comment]
I don't think that this is related with the gijgo library. This seems to be an issue with caching on your server side.

I guess that you need to look for something like this resolution: https://stackoverflow.com/questions/10011780/prevent-caching-in-asp-net-mvc-for-specific-actions-using-an-attribute

**Comment by dgsmidt** [comment]
You're right! Thank you very much!
For the people having the same issue, here goes the solution for Asp.Net Core 2:

**Create a filter class:**

 public class NoCacheAttribute : ActionFilterAttribute
    {
        public override void OnResultExecuting(ResultExecutingContext filterContext)
        {
            filterContext.HttpContext.Response.Headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
            filterContext.HttpContext.Response.Headers["Expires"] = "-1";
            filterContext.HttpContext.Response.Headers["Pragma"] = "no-cache";

            base.OnResultExecuting(filterContext);
        }
    }

**And then decorate the Controller with [NoChache]:**

[NoCache]
    public class CategoriesController : Controller
    {
...
}
