### ISSUE TITLE
Bootstrap 4 datepicker right-icon does not adapt to input height

### ISSUE THREAD

**Issue by NoOorZ24** [atatanasov/gijgo#263]
Bootstrap 4 datepicker right-icon does not adapt to input height when using 

    class="form-control-sm" or class="form-control-lg"

**Comment by atatanasov** [comment]
Yes. This is something that we plan to improve in the next version. Thanks for the feedback. I will let you know once we improve that.

**Comment by atatanasov** [comment]
We added new configuration option for the datepicker called size, where you can specify the size. This is available only in the new development build located in the dist folder at github. We are planning to release this new version within a few days.

You can see some example at:
https://github.com/atatanasov/gijgo/blob/master/examples/datepicker/DatePicker.Base.size.Bootstrap.4.html
https://github.com/atatanasov/gijgo/blob/master/examples/datepicker/DatePicker.Base.size.Bootstrap.3.html
