### ISSUE TITLE
Bootstrap 4 calendar makes page wider when input is on right side

### ISSUE THREAD

**Issue by NoOorZ24** [atatanasov/gijgo#264]
I think it should detect if it's trying to get out of current page size

**Comment by atatanasov** [comment]
Could you send me a code snippet that I can use to replicate and fix the issue.

**Comment by NoOorZ24** [comment]
https://jsfiddle.net/nooorz24/8ssgfaeo/1/

**Comment by NoOorZ24** [comment]
It seems that calendar always starts at same position from left as input ad when input is smaller than calendar it just pushes page further. I know I could just make input wider, but I have to or them to be able to select [from - to] dates and it's in navigation so I can't waste too much space

**Comment by atatanasov** [comment]
Thanks for the example. We are going to fix that in the new version that is comming soon. I will keep you posted.

**Comment by NoOorZ24** [comment]
Thank you :)

**Comment by atatanasov** [comment]
This is already fixed in the new development version. You can find the new build in the dist folder at github.
