### ISSUE TITLE
Dropdown in grid column - use select2

### ISSUE THREAD

**Issue by oyvindvol** [atatanasov/gijgo#265]
Hi,

Would it be possible to use a select2 dropdown within a Gijgo grid? Or maybe add a search field at the top of the current dropdown (gijgo dropdown) ?

**Comment by atatanasov** [comment]
Our gijgo dropdown don't support searching yet. This is going to be added in future versions.

Yes. You can use select2 for editing. Here is the example https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.InlineEditing.column.editor.Custom.With.Select2.html

**Comment by oyvindvol** [comment]
Using this example returns a javascript error in console when tapping "Edit" (inline) the first time:

```
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    at Object.editMode (gijgo.min.js:1)
```
And the inline edit command buttons doesn`t change to "Update and cancel", before tapping the edit button a second time.

The js-error points to this code in the gijgo.min.js-file:
```
, "INPUT" === g.prop("tagName").toUpperCase() && "TEXT" === g.prop("type").toUpperCase()
```

**Comment by atatanasov** [comment]
I fixed that issue. Could you use the latest development build located in the dist folder at github.

**Comment by oyvindvol** [comment]
@atatanasov Thanks that works.

Another problem I have now, is that the `select2editor()` function is only called the first time the edit button of the row is tapped. I am using the function to set the selected option (based on a record property), so that the value is sent to the server on save. 

After I tap edit the second time on the row, no value is selected (since `select2editor()` is not called) if I don`t change the value in the selectbox, and `null` is sent to the server the second time I edit the row.

**Comment by oyvindvol** [comment]
I found another place to trigger my selected values, in my own custom editManager, on the tap on edit button event.

**Comment by ObadMahrous** [comment]
I need to view select in grid but make it visible from first render not while inline editing

**Comment by atatanasov** [comment]
You have to use column mode about this.
http://gijgo.com/grid/configuration/column.mode

**Comment by Infinity-JMarks** [comment]
> Using this example returns a javascript error in console when tapping "Edit" (inline) the first time:
> 
> ```
> Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
>     at Object.editMode (gijgo.min.js:1)
> ```
> And the inline edit command buttons doesn`t change to "Update and cancel", before tapping the edit button a second time.
> 
> The js-error points to this code in the gijgo.min.js-file:
> 
> ```
> , "INPUT" === g.prop("tagName").toUpperCase() && "TEXT" === g.prop("type").toUpperCase()
> ```

I'm getting this error in the latest version (v1.9.11). The dropdown renders, but the call to `grid.edit(id)` fails with the `toUpperCase` error at some point later.
