### ISSUE TITLE
Inline editing dropdown in grid when using a renderer for the column doesn't select the correct value

### ISSUE THREAD

**Issue by AzerinnD** [atatanasov/gijgo#266]
I have a grid where I want to use in-line editing with a drop down for a column that uses a renderer to format the value.  When I try this combination, when I click to edit a row the dropdown's value always resets to the first value instead of the selected value.  It appears this is due to the dropdown databind handler getting the html of the cell to select the value and doesn't support overriding that.

So for example I have:

            var offsets = [
                {value: "1", text: "CET (GMT +1)"},
                {value: "0", text: "GMT"},
                {value: "-5", text: "EST (GMT -5)"},
                {value: "-6", text: "CST (GMT -6)"},
                {value: "-7", text: "MST (GMT -7)"},
                {value: "-8", text: "PST (GMT -8)"}
            ];

and a renderer that does this:
            var timeZoneRenderer = function (value, record, $cell, $displayEl, id) {
                var timezone = offsets.find(function(elem) { return elem.value == value});
                if(null != timezone)
                    $displayEl.text(timezone.text);
                else
                    $displayEl.text("");
            }

and the following column definition:
                    { field: 'offset', width: 140, title: 'Offset', type: 'int', type: 'dropdown', editor: { dataSource: offsets, valueField: "value", textField: "text"}, renderer: timeZoneRenderer },

When I click a row the dropdown value is always the first record instead of the actual value due to this line of code:

                    } else if ('dropdown' === column.type && gj.dropdown) {
                        $editorField = $('<select type="text" width="100%"/>');
                        $editorContainer.append($editorField);
                        config.dataBound = function (e) {
                            if ($editorField.value) {
                                **$editorField.value($displayContainer.html());**
                            }
                        };
                        $editorField = $editorField.dropdown(config);
                    } else {

since it is using the rendered html to try to find the value and since it is setting the "dataBound" property on the config there is no way for me to supply my own dataBound handler to try to override it

**Comment by atatanasov** [comment]
I just fixed a problem in the new development version that is going to resolve your issue. You can find the new development build in the dist folder at github.

You can also create a custom renderer for edit mode where you can control all details. You can see an example about this at https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.InlineEditing.column.editor.Custom.With.Select2.html

**Comment by ObadMahrous** [comment]
I need to add drop down in the grid and make it bind dynamically

**Comment by khatiwadat** [comment]
I'm not able to load data on dropdown on below code. 


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<link href="~/Content/gijgo/combined/gijgo.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
@*<script src="~/Scripts/bootstrap.min.js"></script>*@
@*<script src="~/Scripts/gijgo/combined/gijgo.min.js"></script>*@
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/gijgo/modular/core.js"></script>
<script src="~/Scripts/gijgo/modular/grid.js"></script>
<script src="~/Scripts/gijgo/modular/datepicker.js"></script>
<script src="~/Scripts/gijgo/modular/dropdown.js"></script>
<script src="~/Scripts/gijgo/modular/checkbox.js"></script>

<table id="grid"></table>
<script>
    var countries = ['Bulgaria', 'Brazil', 'England', 'Germany', 'Colombia', 'Poland'];
    var grid, data = [
    { 'ID': 1, 'Name': 'Hristo Stoichkov', 'PlaceOfBirth': 'Plovdiv, Bulgaria' },
    { 'ID': 2, 'Name': 'Ronaldo Luís Nazário de Lima', 'PlaceOfBirth': 'Rio de Janeiro, Brazil' },
    { 'ID': 3, 'Name': 'David Platt', 'PlaceOfBirth': 'Chadderton, Lancashire, England' },
    { 'ID': 4, 'Name': 'Manuel Neuer', 'PlaceOfBirth': 'Gelsenkirchen, West Germany' },
    { 'ID': 5, 'Name': 'James Rodríguez', 'PlaceOfBirth': 'Cúcuta, Colombia' },
    { 'ID': 6, 'Name': 'Dimitar Berbatov', 'PlaceOfBirth': 'Blagoevgrad, Bulgaria' }
    ];
     $('#grid').grid({
         uiLibrary: 'bootstrap',
         dataSource: data,
         columns: [
             { field: 'Name', editor: true },
             { field: 'PlaceOfBirth', type: 'dropdown', editor: { dataSource: countries } },
         ]
     });
</script>
