### ISSUE TITLE
How to add badge in tree

### ISSUE THREAD

**Issue by irajchardoli** [atatanasov/gijgo#268]
I want to show count as a badge in tree , my model:

    public class TreeDto
    {
        public Int64 id { get; set; }

        public Int64 parentId { get; set; }

        public string text { get; set; }

        public Int32 count { get; set; }

        public Decimal minValue { get; set; }

        public Decimal maxValue { get; set; }

        public int viewRank { get; set; }

        public bool hasChildren { get; set; }

        public virtual List<TreeDto> children { get; set; }
    }

![categorytree](https://user-images.githubusercontent.com/5341505/36416356-1880d5bc-163e-11e8-8bc1-bc47295e15af.jpg)

Please tell me how to do it?

**Comment by atatanasov** [comment]
We don't support this yet. We are going to add this feature in future version. Thanks for the feedback.

**Comment by irajchardoli** [comment]
@atatanasov how about this feature?
