### ISSUE TITLE
Editor: not resizing properly

### ISSUE THREAD

**Issue by duncan-qabana** [atatanasov/gijgo#269]
If you fill in a lot of text or a lot of lines, the content goes outside the box and even under other content.
The  [demo](http://gijgo.com/editor/example/bootstrap-4-wysiwyg) has the problem as well.
Just press enter a couple of times to reproduce.

**Comment by atatanasov** [comment]
We are going to address that issue in the next version. Thanks for the contribution!

**Comment by atatanasov** [comment]
We fixed that in the new development version. You can find the new divelopment build in the dist folder at github.
