### ISSUE TITLE
Pagination Refresh Error While using responsive

### ISSUE THREAD

**Issue by romiltonfdo** [atatanasov/gijgo#27]
First I say thanks to your grid. I really like this. My problem is if i use the responsive grid option, me expand a row and click the refresh button in pagination. The last row was disappeared. I tried so many times. If i continue the process means the whole record is removed from the grid.

**Comment by atatanasov** [comment]
Hello,

This is known issue in the current stable version of the grid (0.6.2). This is already fixed in the new version.
You can find the new version at https://github.com/atatanasov/gijgo/tree/development/dist/combined
