### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by NabeelMahmood2** [atatanasov/gijgo#272]
There should be a method to export to excel.

**Comment by atatanasov** [comment]
We don't support this yet. We are going to add this feature in future versions.

**Comment by NabeelMahmood2** [comment]
Thanks, but can you please guide me how to do this because, i have implemented every thing related to a project.

**Comment by atatanasov** [comment]
You can get all the data in the grid with the .getAll() method and convert the data to csv format that is readable by excel. Probably this is the easiest method that not require a lot of coding.

**Comment by NabeelMahmood2** [comment]
So using getAll() method i can get all the data and by using other opensource methods of jquerry grid to convert it all or pass it to the controller and then convert it to excel?

**Comment by NabeelMahmood2** [comment]
Thank you For your response, All is fixed. This gijgo grid is great. Only one thing that i think it should support is exporting to Excel,

I tried getAll function to get all the data in JSON and then convert it to excel, but its not that good.

**Comment by atatanasov** [comment]
We added getCSV and downloadCSV methods for the grid in the new development version. You can find the new development build only in the dist folder at github. I will close the issue, because the csv format is readable by excel.
