### ISSUE TITLE
Tree getSelections return checkboxes selections when true

### ISSUE THREAD

**Issue by ClaytonPeacock** [atatanasov/gijgo#273]
When checkboxes: true on the tree widget getSelections() should return the selected checkboxes and not the selected nodes.
 
  <button id="btnShowSelection" class="gj-button-md">Show Selections</button>
 
 <div id="tree"></div>
 <script>
     var tree = $('#tree').tree({
         dataSource: '/Locations/Get',
         checkboxes: true,
         uiLibrary: 'bootstrap4'
     });
   
       $('#btnShowSelection').on('click', function () {
         var selections = tree.getSelections();
         selections && selections.length && alert(selections.join());
     });

**Comment by atatanasov** [comment]
You have to use the getCheckedNodes if you want to get all the checked nodes. Here is the example: http://gijgo.com/tree/methods/getCheckedNodes
