### ISSUE TITLE
Displaying text in grid dropdown value,text dropdown

### ISSUE THREAD

**Issue by jwalker5006** [atatanasov/gijgo#274]
I have a grid with a value,text drop down. I am able to show the drop down with text and save the value. but the grid only displays the value. Want the grid to show the text.

## Here is a demo
![2018-02-22_14-37-30](https://user-images.githubusercontent.com/6217843/36563482-d00c978c-17df-11e8-9ae3-a09b64d693d1.gif)

## Here is my javascript
![image](https://user-images.githubusercontent.com/6217843/36563512-eeff28a8-17df-11e8-9db2-e64eff4ebf47.png)

**Comment by jwalker5006** [comment]
I think I have to use renderer.
http://gijgo.com/grid/configuration/column.renderer

I am guessing that I could pass back form the model the lookup value of 625 steve for example. But that will only solve the original display of the text instead of value. After an update, a reload would have to take place, at least I think. Will test it out.

**Comment by atatanasov** [comment]
We are going to fix that in the new version. You should be able to use column.renderer as temporary work around.

**Comment by jwalker5006** [comment]
I was able to get it to work, Below is what I had to do. It was a fun one.

![2018-02-23_16-24-41](https://user-images.githubusercontent.com/6217843/36619885-2954cdb0-18b6-11e8-96e1-ac62e14683fc.gif)

## Here is a summary of what I needed to do
1. Add destroy before grid is created and written too
1. turn autoload = false
1. add grid.reload at bottom to load data and filter
1. have a abstract inherited data model for view data, and normal model for saving
1. create array of value/text json data for dropdown

### Adding the Destroy 
Because I had a href trigger changing the data in the grid, I learned that I needed to destroy the grid before creating and reloading the grid on filter changes. If you change a grids filter doing a grid.reload({ groupID: groupIDvalue, page: 1 }); your edit button will not work. You will get a "f.edit" is undefined when clicking the edit button after the first grid build(second + data filter change or reload). Simply add a destroy before the grid is build.

### Turn autoload off
This makes it so the grid can be built, and in my case I was not sure how to add the filter value besides loading it in the URL which I did not want to do. I am using the URL.Page helper and had no luck with loading the query-string and value there.

### Add grid.reload to bottom
I used the end of the js function to load the actual data adding the filter. Seemed cleaner for me

### Abstract Model
Because my grid data was 3 columns of just ID's and no human friendly stuff. And the way I had my linq backend stuff. It was easier to add a second model class where I just added the drop down value as a public string, and inherited the data model for the grid reads. Then used the standard data model for the  saves.

### Create an array value/text for drop down
The format I had to use is:  
people = [{ value: "625", text: "person 1" }, { value: "484", text: "person 2" }];
obviously you can generate this on the back-end and feed it forward.

## Front End
```
<div class="col-lg-7">  
<a name="DetailsClick" href="javascript:void(0);" onclick="getDetails(@item.ContactId);">@Html.DisplayFor(modelItem => item.FullName)</a>
</div>
```

```
function getDetails(id) {  
//Load your details tab or other js stuff

//Load the Datagrid
 if (id!=0){gridLoad(id);}  
}  

function gridLoad(groupIDvalue) {
            //destroy grid during filter changes avoid f.edit error
            $('#grid').grid('destroy', true, true);
            //Just some safe keeping. Dont try and make a grid that will have no results
            if (groupIDvalue == 0) { return;}
            var grid, people;
            people = [{ value: "625", text: "Steve Vujnovich" }, { value: "484", text: "Susan Watson" }];
            var PageURL = "@Url.Page("Index", new { handler = "GetMembers" })";
                grid = $('#grid').grid({
                dataSource: PageURL,
                    uiLibrary: 'bootstrap',
                    primaryKey: 'id',inlineEditing: { mode: 'command' }, 
                    autoload: false, resizableColumns: true, responsive: true,
                    columns: [
                        { field: 'id', title: "ID", width: 45, sortable: true },
                        {
                            field: 'contactId', tmpl: '{groupContactName}',
                            type: 'dropdown', sortable: true ,
                            editor: { dataSource: people },
                            title: "Member Name", width: 150
                        }
                    ],
                    pager: { limit: 5 }
            });
            //Save a row Data
                grid.on('rowDataChanged', function (e, iD, record) {
                var SaveURL = "@Url.Page("Index",new {handler = "SaveMemberData" })";
                $.post(SaveURL,
                    {
                        record: record,
                        __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val()
                    })
                    .done(function () {//I had to reload the page to get the EF6 abstract value
                        grid.reload({ groupID: groupIDvalue, page: 1 });
                    })
                    .fail(function () {alert('Failed to save.');});
                });
            //Delete a row
                grid.on('rowRemoving', function (e, $row, iD, record) {
                if (confirm('Are you sure?')) {
                    var DeleteURL = "@Url.Page("Index",new {handler = "DeleteData" })";
                    $.post(DeleteURL,
                        {
                            record: record,
                            __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val()
                        })
                        .done(function () {grid.reload();})
                        .fail(function () { grid.reload();});
                }
                });

                grid.reload({ groupID: groupIDvalue, page: 1 });
        }
```
## Backend Reading Datagrid
![image](https://user-images.githubusercontent.com/6217843/36620772-428ead88-18ba-11e8-957d-fa0686ca573c.png)



## model
![image](https://user-images.githubusercontent.com/6217843/36620397-7ec60b18-18b8-11e8-97f0-0db9bdac4094.png)

**Comment by atatanasov** [comment]
I added column.editField configuration option in the new development version in order to usage of dropdown in inline editing more simple. editField is going to be the name of the field where we need to set the value from the dropdown. You can find the new build in the dist folder at github.

You can see the demo at:
https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.InlineEditing.column.editField.Bootstrap.4.html

**Comment by shubhamd** [comment]
@atatanasov , the editField approach works when we have table data as -

`players = [ { name: 'XYZ', countryName: 'India', countryId: '1'} ]`

and countries data as =
`countries = [ {name: 'India', id: '1'} ]`

So, the countryName has to be repeated in both the arrays. Is there any simpler which requires countryName only in `countries` and only `countryId` in `people`?

**Comment by shubhamd** [comment]
@atatanasov, the editField approach works when we have table data as -

`players = [ { name: 'XYZ', countryName: 'India', countryId: '1'} ]`

and countries data as =
`countries = [ {name: 'India', id: '1'} ]`

So, the countryName has to be repeated in both the arrays. Is there any simpler which requires countryName only in `countries` and only `countryId` in `people`?

**Comment by ObadMahrous** [comment]
i need to fire event after reorder rows to update the order value of both updated rows.
