### ISSUE TITLE
Rows Width

### ISSUE THREAD

**Issue by NabeelMahmood2** [atatanasov/gijgo#275]
Perfect Grid for modern day solutions but every thing needs improvement.
Rows Width should be adjustable like column width.
That's the thing i found while implementing it.

**Comment by atatanasov** [comment]
Could you give me some suggestions for algorithm for automatic adjustment of rows. What is your idea?

**Comment by NabeelMahmood2** [comment]
I guess it should be same as you have done for columns.

**Comment by NabeelMahmood2** [comment]
Btw i was having issue with row size so i used padding to adjust it, which is great.
But if rowsize is adjustable then it will be great for future adjustments,

**Comment by atatanasov** [comment]
I will reopen the issue and mark it as enhancement in order to implement some kind of adjustable row size/height

**Comment by atatanasov** [comment]
We added bodyRowHeight and headerRowHeight settings in the new development version.  We this settings you can fix the row height or make it scalable. If you want to set a custom row height (for example 50px for each row) you will need to override my css classes with your custom css.

You can find the new dev build in the dist folder at github.
You can see some examples in github at:
examples/grid/Grid.Base.bodyRowHeight.AutoGrow.html
examples/grid/Grid.Base.bodyRowHeight.Fixed.html
examples/grid/Grid.Base.headerRowHeight.AutoGrow.html
examples/grid/Grid.Base.headerRowHeight.Fixed.html
