### ISSUE TITLE
collapseAll() issue.

### ISSUE THREAD

**Issue by NabeelMahmood2** [atatanasov/gijgo#276]
This is what i have done but CollapseAll is not working. Can you please check?

var grid, dialog;
$(document).ready(function () {

    grid = $('#grid').grid({
        primaryKey: 'SNo',
        dataSource: '/OrderedChemicalss/GetOrderedChemicals',
        selectionType: 'multiple',
        resizableColumns: true,
        selectionMethod: 'checkbox',
        grouping: { groupBy: 'OrderNo' },
        columns: [
            { title: 'SNo', field: 'SNo', hidden: true },
            { title: 'Order No', hidden: true,field: 'OrderNo', sortable: false },
            { title: 'Order Date', field: 'OrderDate', sortable: true, type: 'date', format: 'dd/mm/yyyy' },
            { title: 'Staff Name', field: 'StaffName', sortable: true },
            { title: 'RefDocNo', field: 'RefDocNo', sortable: true },
            { title: 'Supplier Name', field: 'SupplierName', sortable: true },
            { title: 'Chemical Code', field: 'ChemicalCode', sortable: true },
            { title: 'Chemical Name', field: 'ChemicalName', sortable: true },
            { title: 'Suppliers Code', field: 'SupplierCode', sortable: true },
            { title: 'Quantity', field: 'Quantity', sortable: false },
            { title: 'UOM', field: 'UOM', sortable: false },
            { title: 'Price', field: 'Price', sortable: false },
            { title: 'Status', field: 'Status', sortable: true },
            { tmpl: '<span class="material-icons gj-cursor-pointer">edit</span>', align: 'center', events: { 'click': Edit } },
            { tmpl: '<span class="material-icons gj-cursor-pointer">delete</span>', align: 'center', events: { 'click': Delete } }

        ],
        pager: { limit: 5 }
    });

    grid.on('dataBound', function (e, records, totalRecords) {
        alert('dataBound is fired. ' + records.length + ' records are bound to the grid.');
        grid.collapseAll();
        alert('dataBound is fired. ' + records.length + ' records are bound to the gridsssssssss.');
    });

    grid.on('dataBinding', function () {
        grid.collapseAll();
    });

});

**Comment by atatanasov** [comment]
I think that you need to use .expandAll() instead of .collapseAll() in order to expand all rows on dataBound. Could you try that.

**Comment by NabeelMahmood2** [comment]
Yes, i am trying, I guess it takes primary key in java script as an argument.
Actually by default i want to collapse all instead of expand all.

**Comment by NabeelMahmood2** [comment]
No its not working.

**Comment by NabeelMahmood2** [comment]
By Default i want to display them like this
![image](https://user-images.githubusercontent.com/17666109/36671536-b88e76a2-1b1d-11e8-85a8-6ef0fe7bf993.png)

**Comment by atatanasov** [comment]
This problem is fixed in the new development build. You can find the new development build in the dist folder at github. You have to use dataBound event and collapseAll method in order to do that.

**Comment by NabeelMahmood2** [comment]
Thanks, its working fine, Can you please do this in https://cdnjs.cloudflare.com/ajax/libs/gijgo/1.7.0/combined/js ?
using this icons doesn't load up.
