### ISSUE TITLE
Razor 2.0 variable parameter issue

### ISSUE THREAD

**Issue by jwalker5006** [atatanasov/gijgo#278]
the word page isnt allowed or accepted with a .net razor 2.0 page  So each release I change the paramNames Page to currentPage. 

![image](https://user-images.githubusercontent.com/6217843/36741151-01d6aac8-1baa-11e8-8d1b-c571c105361d.png)

![image](https://user-images.githubusercontent.com/6217843/36741266-42e176f6-1baa-11e8-90cb-a0f278ac8b38.png)

**Comment by atatanasov** [comment]
I don't think that you need to overide this in each release. You just need to have a base configuration object for each grid where this is overwritten to 'currentPage'.

```
var baseGridConfig = { paramNames: { page: 'currentPage' }, uiLibrary: 'bootstrap' };
var localPageGridConfig = baseGridConfig;
localPageGridConfig.dataSource = '/PLayers/Get';
$('#grid').grid(localPageGridConfig);
```
