### ISSUE TITLE
Dialog z-index add request

### ISSUE THREAD

**Issue by jwalker5006** [atatanasov/gijgo#279]
The dialog when used with a grid gets covered up slightly.

I found if I copy the gijgo.css locally and add a z-index:9; to the .gj-dialog-md{...} the issue goes away
![image](https://user-images.githubusercontent.com/6217843/36854065-acf1b8e4-1d35-11e8-8775-e95ca9c80666.png)

## Before
![image](https://user-images.githubusercontent.com/6217843/36854090-c0dd499a-1d35-11e8-93e4-59437a95eb4c.png)

## After
![image](https://user-images.githubusercontent.com/6217843/36854140-d6293278-1d35-11e8-97b4-2ea045df86e5.png)

**Comment by atatanasov** [comment]
This is fixed in the new development version. You can find the new development build in the dist folder at github. Thanks for the contribution!

p.s. You have to set the uiLibrary: 'bootstrap' for your dialog in order to use bootstrap for the dialog as well.
