### ISSUE TITLE
Checkbox selection method should disable other selection methods

### ISSUE THREAD

**Issue by aamirMasood** [atatanasov/gijgo#28]
I have a scenario similar to the following:

```
    grid = $("#grid").grid({
        primaryKey: "Id",
        uiLibrary: "bootstrap",
        notFoundText: "No records found",
        selectionMethod: 'checkbox',
        selectionType: 'multiple',
        columns: [
            { field: "Name", title: "Name"},
            { field: "Description", title: "Description" },
            { title: "", icon:'fa fa-edit'  field: "Edit", width: 34, tooltip: "Edit", events:{click:clickEventHandler} },
        ],
        pager: { enable: true, limit: 5, sizes: [2, 5, 10, 20] }
    });
```

The selectionMethod is set to checkbox and that part is working fine but when I click on any field the row is still getting selected or unselected and eventually the checkbox changes. I think when the mode is set to checkbox only checkbox should be able to select/unselect the row. That way any click event inside the row will not be able to change the selection.

**Comment by atatanasov** [comment]
I agree. We are going to change that in future versions.

**Comment by atatanasov** [comment]
This is fixed in the new development version. You can find the new build at https://github.com/atatanasov/gijgo/tree/master/dist
