### ISSUE TITLE
dropdown in grid not loading values

### ISSUE THREAD

**Issue by ebs675** [atatanasov/gijgo#280]
Hello:

I have a very simple grid, but on inline edit, it will not load the dropdown values defined in a static variable. JavaScript below:

`var grid, btypes;
            btypes = ["positive" , "negative"];
            grid = $('#grid').grid({
                primaryKey: 'id',
                dataSource: '/BehaviorTypes/Get',
                inlineEditing: { mode: 'command' },
                uiLibrary: 'bootstrap',
                columns: [
                    { field: 'id', hidden: true },
                    { field: 'name', title: 'Name', width: 150, editor: true },
                    { field: 'type', title: 'Type', type: 'dropdown', editor: { dataSource: btypes }, width: 50 }
                ]
                });`

**Comment by atatanasov** [comment]
We made some changes recently about that and introduce a new column setting called editField. This is available only in the new development build at the dist folder in github.

Please use the following example: https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.InlineEditing.column.editField.Bootstrap.4.html

**Comment by ebs675** [comment]
Thank you. That fixed this issue. Are there any other items in the examples that are no longer correct? I am not able to get it to call my delete function upon the row_removing event. It is triggering the confirmation popup, but it never calls the actual delete function in my controller. I used the code in the inline edit example. Any thoughts.

**Comment by ebs675** [comment]
I was able to get it to call the delete function by turning off validateantiforgery, but now the grid will not update after the delete. I have to reload the application before the changes refresh. Is there some sort of caching issue perhaps?

**Comment by ebs675** [comment]
I found the solution. In my controller I needed to turn off caching.   I apologize for cluttering up the issues thread.

**Comment by atatanasov** [comment]
no problem! Thanks for the contribution.
