### ISSUE TITLE
Custom Field Names issue when dataSource is empty and we want to use addNode method to add nodes and thier children

### ISSUE THREAD

**Issue by rabbal** [atatanasov/gijgo#281]
Configuration
--------------------------
` var tree = $("#listItems").tree({
        primaryKey: 'Id',
        textField: 'Title',
        childrenField: 'Children',
        uiLibrary: 'bootstrap',
        iconsLibrary: 'fontawesome',
        checkboxes: true,
        border: true,
        dataSource: $("#listItems").data("items") || []
    });`

Add Node
---------------------
`
    tree.addNode({ Title: 'node1'});
    tree.addNode({ Title: 'node1-1' }, tree.getNodeByText('node1'));
`

Hint
-----------------
the problem is in this below code
` id = data.primaryKey ? response[i][data.primaryKey] : data.autoGenId++;`

**Comment by atatanasov** [comment]
What is the error message that you get in this case? What line of code?
Could you provide sample data for $("#listItems").data("items")  result in order to be able to replicate the isssue.

**Comment by rabbal** [comment]
when dataSource is empty, the id will be undefined.
![capture-01](https://user-images.githubusercontent.com/6818642/36941886-e319d1b2-1f7a-11e8-96b8-97f9f81eb49a.PNG)
![capture-02](https://user-images.githubusercontent.com/6818642/36941887-e33f8d80-1f7a-11e8-8c20-9a9344c036d5.PNG)
![capture-03](https://user-images.githubusercontent.com/6818642/36941888-e364921a-1f7a-11e8-9162-aa905c18da02.PNG)
![capture-04](https://user-images.githubusercontent.com/6818642/36941889-e388d242-1f7a-11e8-9619-9491f50e69df.PNG)

**Comment by atatanasov** [comment]
I'm not able to replicate your issue. Here is my example where everything works fine. http://gijgo.com/Temp/91b6e5e4-3700-4165-9f2b-d7e0790a1e75.html

Are you using version 1.8.1? 1.8.1 seems to be working fine.

**Comment by rabbal** [comment]
Thank you,
in your example if you add child node to 'node1' with below code:
`tree.addNode({Title:"Title"},tree.getNodeByText("node1"))`
you get an error like below:
![capture](https://user-images.githubusercontent.com/6818642/37083101-b5bbed96-2203-11e8-9587-7b611e324d33.PNG)


because the data-id attribute of 'node1' has undefined value

![capture](https://user-images.githubusercontent.com/6818642/37083499-f026a920-2204-11e8-95c3-18ab88913085.PNG)


so, in line 620 of tree.js file thrown up one exeption.
line 620: ` gj.tree.methods.getById($tree, $parent.parent().data('id'), $tree.data('records')).children.push(newNodeData);`

$tree, $parent.parent().data('id') is undefined, so the result of getById Method is undefined and we can not get children of it.

**Comment by atatanasov** [comment]
We fixed that in the new development version. You can find the new build in the dist folder at github. Thanks for finding this.
