### ISSUE TITLE
Sub grid paging stops working when open second time (no server call)

### ISSUE THREAD

**Issue by angelomiguelsantos** [atatanasov/gijgo#282]
hello 

the Sub grid paging stops working when open second time (no server call)
is that a way to force reload  when detailExpand event occurs ? 

thank you 

Angelo

**Comment by atatanasov** [comment]
Could you provide a code sample in order to  be able to replicate the issue

**Comment by angelomiguelsantos** [comment]
hello sorry for late response 

here is what i did 

  grid.on('detailCollapse', function (e, $detailWrapper, id) {
                $detailWrapper.find('table').grid('destroy', true, true);
            });

and it works now  :)
