### ISSUE TITLE
How to configure to sorting tree according to a property

### ISSUE THREAD

**Issue by irajchardoli** [atatanasov/gijgo#287]
I have a model for tree as below:

```
public class TreeDto
{
    public Int64 id { get; set; }

    public Int64 parentId { get; set; }

    public string text { get; set; }

    public Int32 count { get; set; }

    public Decimal minValue { get; set; }

    public Decimal maxValue { get; set; }

    public int viewRank { get; set; }

    public bool hasChildren { get; set; }

    public virtual List<TreeDto> children { get; set; }
}
```

Please tell me is it possible to configure tree to sort according to "viewRank"  property?

**Comment by atatanasov** [comment]
Yes. You can see it in our ASP.NET examples located at https://github.com/atatanasov/gijgo-asp-net-examples

In our example we sort by OrderNumber. You just need to modify the code and sort by viewRank. Here is code in the backend https://github.com/atatanasov/gijgo-asp-net-examples/blob/master/Gijgo.Asp.NET.Examples/Controllers/LocationsController.cs
