### ISSUE TITLE
grid.edit(id) not changes the buttons. 

### ISSUE THREAD

**Issue by evilripper** [atatanasov/gijgo#289]
Hi, congrats for gijgo, it's very useful! :+1:  
I'm trying to add a row to grid to INSERT new record directly in the grid without annoying popup, but I have a problem with the edit metod!

![error](https://user-images.githubusercontent.com/1646220/37153125-02c52f16-22dc-11e8-8c1a-5ed9d2e4c8c5.JPG)
 

When I set in edit a row the buttons don't change (is it a bug?), I made a spaghetti code for a stupid workaround! :) 

` $('#btnAddRecord').on('click', function () {
   var tempId =- 1;

   grid.addRow({ 'Id': tempId, 'Name': '', Nationality :'', Created:'' });
   var editButton = $("button[data-key='" + tempId + "']").find('span.glyphicon-pencil').parent();
   var cancelButton = $("button[data-key='" + tempId + "']").find('span.glyphicon-ban-circle').parent();
   var deleteButton = $("button[data-key='" + tempId + "']").find('span.glyphicon-remove').parent();
   var updateButton = $("button[data-key='" + tempId + "']").find('span.glyphicon-ok').parent();
   editButton.hide();
   deleteButton.hide();
   cancelButton.show();
   updateButton.show();
   grid.edit(tempId);
   //no workaround see the image
   grid.edit(10);
   });
`

**Comment by stvowi** [comment]
There should/ could be a new button in the thead area over the other command buttons to insert on new  row on the top of the table....

Inspiration:[https://demos.telerik.com/kendo-ui/grid/editing-inline](https://demos.telerik.com/kendo-ui/grid/editing-inline)

**Comment by atatanasov** [comment]
We fixed that in the new development build. You can find the new build in the dist folder at github.
