### ISSUE TITLE
Words are truncated in the column

### ISSUE THREAD

**Issue by jefferyleo** [atatanasov/gijgo#29]
![gijgo grid](https://cloud.githubusercontent.com/assets/6831609/19651786/e26f163e-9a40-11e6-8300-65ad7db03faa.png)

As you can see the email column data has been truncated, it works in Chrome, but not works in Microsoft Edge and Internet Explorer, any solution to help on this? Appreciate if any guy would help on it.

**Comment by aamirMasood** [comment]
A simple solution would be to set the width of the column. Checkout [this](http://gijgo.com/Grid/Configuration/column.width). 
It would be easy to understand the specific scenario if you post a code snippet as well.

**Comment by atatanasov** [comment]
Another solution could be to use the column.cssClass configuration option in order to customize the table cell. You can see an example at http://gijgo.com/Grid/Configuration/column.cssClass
