### ISSUE TITLE
Can't get multiple datepickers to work on the same form

### ISSUE THREAD

**Issue by dkh7m** [atatanasov/gijgo#290]
We have three text input fields with unique names and IDs in a web form. Using the code below we are able to get all three fields to display as date pickers. However, when we submit the form, only the first input data is coming through in the POST. The other two are not showing up in the form data. This is a ColdFusion page using standard HTML form. 

I also tried using a class to make all three datepickers display, but with the same results. First one posts, the other two do not.

``		/* DATE PICKERs WIDGET: */
		$('#patient_screening_9').datepicker({
		  uiLibrary: 'bootstrap4',
		  iconsLibrary: 'fontawesome',
		  format: 'mm-dd-yyyy'
      });
		 $('#consent_form_date').datepicker({
		   uiLibrary: 'bootstrap4',
		   iconsLibrary: 'fontawesome',
		   format: 'yyyy-mm-dd'
		 });
		 $('#mri_appointment_date').datepicker({
		   uiLibrary: 'bootstrap4',
		   iconsLibrary: 'fontawesome',
		   format: 'yyyy-mm-dd'
		 });
..

**Comment by atatanasov** [comment]
I guess that you miss to set names to your date inputs and that's why they are missing.
In the following example I set value in the name attributes and everything works fine: http://gijgo.com/Temp/da380ffb-e1f9-4cc2-a369-c40c53549ca4.html
