### ISSUE TITLE
Pager drop down style

### ISSUE THREAD

**Issue by pentexsoft** [atatanasov/gijgo#291]
I am trying to figure out why the Select is styling the height larger then it should be.
could you give me any assistance. 

![gijgo_pager](https://user-images.githubusercontent.com/32546238/37187442-4ef231d6-2318-11e8-8ee3-59616646bed7.png)

Thanks

**Comment by pentexsoft** [comment]
Bootstrap 4/Fontawesome.

**Comment by pentexsoft** [comment]
looking at your example, the pager is inline and padding is much less between buttons. not sure why my pager is styling so much different. only thing I see is I am on boot 4.0.0 alpha 6.


![image](https://user-images.githubusercontent.com/32546238/37187781-d447e866-2319-11e8-90c5-da8ccece3b86.png)

**Comment by atatanasov** [comment]
Yes. Everything works fine on my example at http://gijgo.com/grid/demos/bootstrap-4-table
Could you try to use the bootstrap version from my example to see if this is going to fix the issue.
You could have some other css classes that override my classes. Could you inspect the dropdown to see if this is true. Could you upgrade to gijgo 1.8.2 to see if this is going to help.

**Comment by pentexsoft** [comment]
was able to find the overriding issue on one of my classes. thanks a lot. 
2 other issues with the pager
1. the font size of the drop down limits does not scale with the font size of the grid
2. would be nice if the drop down would go up instead of down. most times it is at the bottom of the page. 

what was updated in 1.8.2?
fantastic control!

**Comment by atatanasov** [comment]
We are going to implement you suggestions in future versions. Thanks for suggesting improvements. We value that.

You can see what's new in 1.8 from http://gijgo.com/Blog/ChangeLog_Version_1_8

**Comment by atatanasov** [comment]
I will open a new issue about the fontSize scalling, because this is more complicated than it looks. The new issue is https://github.com/atatanasov/gijgo/issues/298
I will close this issue, because we already improved the positioning of the page size dropdown. You can find this improvement only in the new dev version that is located in the dist folder at github.

**Comment by pentexsoft** [comment]
thanks for the update. Those drop downs do have a tendency to be more complicated than they look.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
