### ISSUE TITLE
Remove mouse over

### ISSUE THREAD

**Issue by angelomiguelsantos** [atatanasov/gijgo#292]
Hello i set some colors in my  grid rows ...

how can i remove the mouse over effect in the grid rows ? 

thank you 

Angelo

**Comment by atatanasov** [comment]
In order to do that you have to override our css class for row:hover. for example our css selector for material design theme is:
```
.gj-grid-md tbody tr:hover {
    background-color: #EEEEEE;
}
```
You can override it with something like
```
table.gj-grid-md tbody tr:hover {
    background-color: unset;
}
```
