### ISSUE TITLE
Error 500 on Contact Us

### ISSUE THREAD

**Issue by Nestoter** [atatanasov/gijgo#294]
Hi, i know that this is not the correct place to write this but i can't reach gijgo owner.
http://gijgo.com/Home/ContactUs is not working, ir returns error 500.
I would like to share my spanish traduction messages.es-es.js for gijgo, but i cant send it through contac us because is not working.

**Comment by atatanasov** [comment]
Thanks for finding this issue. We just fixed the ContactUs page. The best way to share you spanish translation would be through pull request in GitHub. When I accept this pull requests you will be listed as official contributor of this project. You can also send me the spanish translation here or through the contact form, If the pull request take to much time for you. Thanks again!

**Comment by atatanasov** [comment]
Closing the issue. Please send me the Spanish translation when you are able to do it.
