### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by renardkabza** [atatanasov/gijgo#295]
Lazy Loading does not render properly the  Indeterminate status of the checkbox. 
I have added a checkbox element for the lazy loading.
1st step - the page load, all elements that have Pid = null
![image](https://user-images.githubusercontent.com/7165169/37245999-1ee2b7e0-2499-11e8-8e89-ccccbda8372b.png)
2nd - unfolding North America 
![image](https://user-images.githubusercontent.com/7165169/37246022-8eedb7c4-2499-11e8-8114-78d2e256afce.png)
3rd - unfolding the USA node, going backwards all its parents should have the indeterminate status.
![image](https://user-images.githubusercontent.com/7165169/37246038-bfdd5b3c-2499-11e8-9dc7-db96ac82e869.png)

**Comment by atatanasov** [comment]
We fixed that in the new development version. You can find the new build in the dist folder at github.
