### ISSUE TITLE
Grid widget: "rows" per page" selector

### ISSUE THREAD

**Issue by francescosaverio** [atatanasov/gijgo#303]
Hi, Mr. Atanasov.
It is for sure a secondary issue, but... Issue.
As in the subject, whenever selecting the dropdown to change the number of rows" per page,
the list get displayed left sided in the page. You can easily verify this in whatever the case example.
I guess this occurs since from 1.9.0 release. 
Not sure in 1.8.2. 
1,8.1 works fine.
Thank You for Your superbe widget set.

Francesco. 
Anzio - Italy

**Comment by atatanasov** [comment]
Could you send me a screenshot. Are you using Chrome or Internet Explorer?

**Comment by francescosaverio** [comment]
Yes, actually I am using Interner Explorer (ver.: 11.0.9600.18861).
Here follows the screenshot samples (before and after).
Regards.
Francesco.
![1](https://user-images.githubusercontent.com/12872609/37708643-617659a4-2cff-11e8-845c-d179e88bd595.jpg)
![2](https://user-images.githubusercontent.com/12872609/37708775-d0615c60-2cff-11e8-91d3-12be8599fd9d.jpg)

**Comment by francescosaverio** [comment]
p.s.: how could I send You the gijgo message file in italian Language (i.e.: messages.it-it.js, if useful of course)?
Let me know, pls.
Regards.
Francesco

**Comment by atatanasov** [comment]
The best way to send me the it-it.js is with pull request in github (https://help.github.com/articles/creating-a-pull-request/). If you create a pull request your name your be listed as contributor in this project in all sites that use github.

If you are new in git and github and this is very complicated for you, than you can send me the files as attachment to this ticket.

I fixed the issue with the dropdown in the new development version. You can find the new build only in the dist folder at github. I will submit an official release within a few days.

Thanks in advance for the Italian translation.

**Comment by francescosaverio** [comment]
To be faster, i decided to drop here the "messages.it-it.js" (the .txt extension is needed to do this).
If anything wrong, just let me know.
Thank You for fixing issue!

[messages.it-it.js.txt](https://github.com/atatanasov/gijgo/files/1833429/messages.it-it.js.txt)

**Comment by atatanasov** [comment]
The new version is released. I also added the Italian translation to the new release. You can check it at http://gijgo.com/datepicker/example/localization
