### ISSUE TITLE
Cannot restrict selectable period into DatePicker

### ISSUE THREAD

**Issue by bvn13** [atatanasov/gijgo#307]
Used code:
```javascript
(function($){

    $(document).ready(function() {
        $('#date-selector').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd',
            weekStartDay: 1,
            locale: $('#date-selector-locale').val(),
            minDate: $('#date-selector-start').val(),
            maxDate: $('#date-selector-end').val(),
        });
    });

})(jQuery);
```

Values are:
$('#date-selector-locale').val() = "ru-ru"
$('#date-selector-start').val() = "03/16/2018" 
$('#date-selector-end').val() = "03/23/2018"

I mean the period from 16th of March 2018 till 23th of March 2018 (Did I guess the format described into docs correctly?)

And it does not allow me to select any day.

![](https://i.imgur.com/Bp0sts1.png)

Where am I wrong?

**Comment by bvn13** [comment]
Seems I solve this issue. It was a wrong format I used. Please, fill the docs!

![](https://i.imgur.com/KGO1yUQ.png)

**Comment by atatanasov** [comment]
The minDate and maxDate needs to follow the specified format. In your case the configured format is 'yyyy-mm-dd', but the min and max dates are in different format.
The correct configuration in your case is:

```
     $('#date-selector').datepicker({
       	    uiLibrary: 'bootstrap4',
            format: 'yyyy-mm-dd',
            weekStartDay: 1,
            locale: 'ru-ru',
            minDate: "2018-03-16",
            maxDate: "2018-03-23"
     });
```

I will try to make this more clear in the documentation. Thanks for the feedback.
