### ISSUE TITLE
TimePicker does not work properly at all

### ISSUE THREAD

**Issue by bvn13** [atatanasov/gijgo#309]
Any mouse click becomes a missclick. Whereever I try to click.

[I recorded it and stored onto youtube](https://youtu.be/GJyPxXYor90)

**Comment by atatanasov** [comment]
Thanks for reporting this. I'm not able to replicate the issue. I tested this with several combinations but still no luck.
Can you replicate this issue with the following code: http://gijgo.com/Temp/8f3a5995-990a-4306-bcf6-b1b64c5d46f5.html?
Do you have any javascript errors in the console?
Do you have any customizations of our code for the timepicker?

**Comment by atatanasov** [comment]
We fixed that in the new development version that is going to be released as 1.9.4 later today.
