### ISSUE TITLE
[BUG] Datepicker and Timepicker not working properly when you have to scroll to get to them

### ISSUE THREAD

**Issue by oec-glados** [atatanasov/gijgo#310]
I am building a website, and I cannot get neither the date nor the timepicker to work properly. There's a table that takes up most of the screen, and when you click on a row, the both pickers show up at the bottom (among other elements). But when you have to scroll to get to the pickers, they start behaving erratically. The datepicker's popup appears at different places at random, and the timepicker's modal shows up, but wherever you click, it always picks the same time (6 AM).

I am using Bootstrap 4. At first I thought it was an issue with the table, because if I deleted it, the pickers behaved normally, but after a lot of debugging, I noticed that the bug only occurs when the pickers are displayed at a place you have to scroll to, regardless of what's above them. To test that, I created a container, made several rows with the letter A, set the font to 20em, so that they pushed the pickers downwards. The pickers stopped working when they were somewhere you had to scroll to. Deleting the As one by one, from the inspector, as soon as the pickers became visible without scrolling, they immediately started behaving normally again (without even refreshing the page), and when you push them down again, the bug returns.

Any thoughts on what could be causing the issue? If you need more info or screencaps, let me know!

[EDIT]: bvn13's reported bug is the same as mine. To replicate it, you might want to try what I described above. My timepicker behaves exactly as his. This bug affects the datepicker too.

[EDIT 2]: You can replicate bvn13's bug in the example page you provided by adding a margin-top of 1500px and pushing down the picker in the inspector.

**Comment by atatanasov** [comment]
Thanks for the additional information. I'm looking at this. I will keep you posted.

**Comment by atatanasov** [comment]
We fixed that in the new development version that is going to be released as 1.9.4 later today.
