### ISSUE TITLE
Gijgo grid not working for inline edit mode

### ISSUE THREAD

**Issue by Mayura-Medicity** [atatanasov/gijgo#311]
I have used the new version of gijgo for grid. But on initial load i am getting the following error
**Uncaught TypeError: Cannot read property 'children' of undefined** Line gijgo.js:6662 
Edit button click event is also not getting raised
Can you please help me out in fixing this issue

**Comment by atatanasov** [comment]
Everything looks good in our example at http://gijgo.com/grid/demos/bootstrap-grid-inline-edit
Could you check if you set correct value for the primaryKey configuration option as it is shown in our example.
Can you provide a code snippet that I can use for the replication of this issue?

**Comment by Mayura-Medicity** [comment]
Thanks for the reply Atatanasov. Issue was I did not set primary key for the grid. It is working fine for me. Thanks for the quick reply.

**Comment by atatanasov** [comment]
Can you give me a code sample that I can use to replicate your javascript error. I just want to prevent the javascript error in this case.

**Comment by Mayura-Medicity** [comment]
$(document).ready(function () {
            var grid, countries;
            grid = $('#grid').grid({
                dataSource: '/Test/Get',
                uiLibrary: 'bootstrap',
                
                inlineEditing: { mode: 'command' },
                columns: [
                 { field: 'ApplicationName', width: 44 },
                 { field: 'ReleaseName', editor: true },
                 { field: 'ProjectName', editor: true },
                 { field: 'CodeCoverage', title: 'Active?', editor: true, width: 90, align: 'center' }
                ],
                pager: { limit: 5 }
            });
            grid.on('rowDataChanged', function (e, id, record) {
                debugger;
                // Clone the record in new object where you can format the data to format that is supported by the backend.
                var data = $.extend(true, {}, record);
                var CodeCoverageViewModel = {
                   ProjectName: record.ProjectName,
                    ReleaseName: record.ReleaseName,
                    ApplicationName: record.ApplicationName,
                    CodeCoverage: record.CodeCoverage
                };
                // Post the data to the server
         
                $.ajax({ url: 'Save', data: JSON.stringify({ record: CodeCoverageViewModel }), type: 'POST', contentType: "application/json; charset=utf-8" })
                    .fail(function () {
                        alert('Failed to save.');
                    });
            });
            
        });

This is how my javascript was prior. Later based on your feedback I added ID column as primary in both my table and model
