### ISSUE TITLE
grid bind with conditional param

### ISSUE THREAD

**Issue by nikudale** [atatanasov/gijgo#313]
Hi,

I would like to bind grid data with conditional param, how we pass param explicitly to serverside.
like I need to pass type as hidden field param
tmpgrid = $('#tGrid').grid({
        primaryKey: 'ID',
        dataSource: '/admin/GetTDetails',
        uiLibrary: 'bootstrap',
        columns: [
            { field: 'ID', width: 100 },
            { title: '@Model.Title Description', field: 'Description', sortable: true },
            { title: '', field: 'Delete', width: 34, type: 'icon', icon: 'glyphicon-remove', tooltip: 'Delete', events: { 'click': TmpDelete } }
        ],
        pager: { limit: 10, sizes: [2, 5, 10, 20] }
    });

server side
public ActionResult GetTemplateDetails(int type = 1)
{
}

**Comment by atatanasov** [comment]
I think that would be best if you use our reload method about it. You can find an example at http://gijgo.com/grid/methods/reload
