### ISSUE TITLE
Datepicker - option to remove rightIcon

### ISSUE THREAD

**Issue by lepinse** [atatanasov/gijgo#314]
Would be great if, when rightIcon option is null, the icon is not added to the wrapper.

`icons: { rightIcon: null }`

Useful when displaying the datepicker on focus, no icon needed.

My Fork to acheive this:
https://github.com/lepinse/gijgo/commit/3474c6a45824d96a0fa7710d01358d7da4cd4d5b

**Comment by atatanasov** [comment]
We are going to add this in some of the future versions. I will keep you posted.

**Comment by theAlinux** [comment]
try this
```
$(document).on('focus', 'input.datetimepickerboost', function () {

        $(this).closest('div').find('span').remove(); //this add remove icon

        $(this).datetimepicker({
            uiLibrary: 'bootstrap4',
            footer: true,
            datepicker: {
                weekStartDay: 1
            },
            format: 'HH:MM dd/mm/yyyy'
        });
    });
```

**Comment by atatanasov** [comment]
This is already added. You can see an example at https://gijgo.com/datepicker/configuration/showRightIcon
