### ISSUE TITLE
Grid - "Page indicator box" partially hiding the "page number" (three digit case)

### ISSUE THREAD

**Issue by francescosaverio** [atatanasov/gijgo#315]
Hi, Mr. Atanasov.
This is just another secondary issue (...as always, from my cases...).
Issue subject and the attached picture tell the most.
Is there any chanche to enlarge the page indicator box (e.g.: by some supplementary .css) / is it auto resizing / what else?
Note I am using Gijgo ver. 1.9.6.
I don't remember i had same issue using previous versions of Your framework.
Still, I can verify if needed.

Thanks for Your attention. Regards,
Francesco.
![grid_currentpage](https://user-images.githubusercontent.com/12872609/38305375-39a85564-37fc-11e8-938d-f15a69cb9151.jpg)

**Comment by atatanasov** [comment]
The page number input is always fixed to 40px even in old versions.

You can use the following css in order to overide it:

```
.gj-grid-bootstrap-3 tfoot tr[data-role="pager"] th>div>input[data-role="page-number"] {
    width: 50px;
}
```

**Comment by francescosaverio** [comment]
Thanks a lot, Mr. Atanasov!!!

**Comment by francescosaverio** [comment]
p.s.: of course, I'd have analogue request for "total number of pages" indicator box....))))
Thanks a lot for Your huge patience...
