### ISSUE TITLE
Not Found Text not showing when grid cleared

### ISSUE THREAD

**Issue by MB34** [atatanasov/gijgo#317]
I'm clearing the grid and reloading it, when the ajax doesn't return any records, success is not called and thus no data is loaded. However, the NotFoundText is not showing.

I can't build a demo due to api and all my development being local.

    function GetInventory() {
        if(typeof invgrid !== 'undefined') {
            invgrid.clear();
        } 
        $.ajax({
            method: "GET",
            url: "API/GetInventory?ic=" + ic, 
            dataType: 'json',
            success: function( data ) {
                if(typeof invgrid !== 'undefined') {
                    invgrid.render(data);                             
                } 
                else 
                {
                    invgrid = $('#inv_grid').grid({
                             primaryKey: 'urgid',
                             dataSource: data,
                             uiLibrary: 'bootstrap4',
                             notFoundText: 'No records found',
                             bodyRowHeight: 'fixed',
                             columns: [
                                    { field: 'urgid', title: 'ID', sortable: true, headerCssClass: 'gridHeader' },
                                    { field: 'company', title: 'Company', sortable: true, headerCssClass: 'gridHeader' },
                                    { field: 'part', title: 'Part', headerCssClass: 'gridHeader' },
                                    { field: 'year', title: 'Year', sortable: true, headerCssClass: 'gridHeader' },
                                    { field: 'model', title: 'Model', sortable: true, headerCssClass: 'gridHeader' },
                                    { field: 'stocknum', title: 'Stock #', sortable: true, headerCssClass: 'gridHeader' },
                                    { field: 'ic', title: 'Interchange', width: 150, headerCssClass: 'gridHeader' },
                                    { field: 'vin', title: 'VIN', width: 160, headerCssClass: 'gridHeader' },
                                    { field: 'status', title: 'Status/Curr<br />Status', headerCssClass: 'gridHeader' },
                                    { field: 'bodycolor', title: 'Body', headerCssClass: 'gridHeader' },
                                    { field: 'condition', title: 'Condition', headerCssClass: 'gridHeader' },
                                    { field: 'comments', title: 'Comments', headerCssClass: 'gridHeader' },
                                    { field: 'miles', title: 'Miles', headerCssClass: 'gridHeader' },
                                    { field: 'price', title: 'Price', sortable: true, headerCssClass: 'gridHeader' },
                                    { field: 'quantity', title: 'Qty', sortable: true, headerCssClass: 'gridHeader' }                                     
                                ],
                             pager: { limit: 10 }
                         });    
                }
                invgrid.show();
            }
        });
    }

**Comment by atatanasov** [comment]
I think that would be best if you use our .reload() method in the following manner:
```
var invgrid;
function initialization () {
                      invgrid = $('#inv_grid').grid({
                         primaryKey: 'urgid',
                         dataSource: "API/GetInventory",
                         uiLibrary: 'bootstrap4',
                         notFoundText: 'No records found',
                         bodyRowHeight: 'fixed',
                         columns: [
                                { field: 'urgid', title: 'ID', sortable: true, headerCssClass: 'gridHeader' },
                                { field: 'company', title: 'Company', sortable: true, headerCssClass: 'gridHeader' },
                                { field: 'part', title: 'Part', headerCssClass: 'gridHeader' },
                                { field: 'year', title: 'Year', sortable: true, headerCssClass: 'gridHeader' },
                                { field: 'model', title: 'Model', sortable: true, headerCssClass: 'gridHeader' },
                                { field: 'stocknum', title: 'Stock #', sortable: true, headerCssClass: 'gridHeader' },
                                { field: 'ic', title: 'Interchange', width: 150, headerCssClass: 'gridHeader' },
                                { field: 'vin', title: 'VIN', width: 160, headerCssClass: 'gridHeader' },
                                { field: 'status', title: 'Status/Curr<br />Status', headerCssClass: 'gridHeader' },
                                { field: 'bodycolor', title: 'Body', headerCssClass: 'gridHeader' },
                                { field: 'condition', title: 'Condition', headerCssClass: 'gridHeader' },
                                { field: 'comments', title: 'Comments', headerCssClass: 'gridHeader' },
                                { field: 'miles', title: 'Miles', headerCssClass: 'gridHeader' },
                                { field: 'price', title: 'Price', sortable: true, headerCssClass: 'gridHeader' },
                                { field: 'quantity', title: 'Qty', sortable: true, headerCssClass: 'gridHeader' }                                     
                            ],
                         pager: { limit: 10 }
                     }); 
}
function reload(ic) {
    invgrid.reload({ ic: ic });
}
```

The reload function actually send parameters to the remote data source. You can see more details in our example at http://gijgo.com/grid/demos/ajax-sourced-data
