### ISSUE TITLE
CSV Download and multi-line Column Titles

### ISSUE THREAD

**Issue by MB34** [atatanasov/gijgo#318]
When configuring multi-line column titles such as `Status/Curr<br   />Status`, the CSV download returns it as the exact text. Is there a way to put an actual CRLF in the text to replace the `<br />`?
I'd rather see the column title in the CSV be like this:

    Status/Curr
    Status

**Comment by atatanasov** [comment]
We don't support that. If you need that would be best for you if you use out .getAll() and convert the json returned by this method in a CSV format that you would like.
