### ISSUE TITLE
Grid button click inside row.

### ISSUE THREAD

**Issue by Grey-Walker** [atatanasov/gijgo#320]
Hi Not really an issue as such, just posting here for visabilty. is there a way to get the button click event of a button added in the on cellDataBound event? I have a stackoverflow question pasted here showing what I mean, thanks

https://stackoverflow.com/questions/49638389/gijgo-grid-button-click-inside-row

**Comment by atatanasov** [comment]
I just answered the question. Please vote for my answer at stackoverflow, if you like it.
