### ISSUE TITLE
Grid with date in edit mode: A change from am to pm is not recognized.

### ISSUE THREAD

**Issue by ehamill** [atatanasov/gijgo#323]
When we have a grid with type: 'date', format: 'mm/dd/yyyy hh:MM TT', it will let the user change the AM to PM. But it always returns "AM", unless military time is used.

**Comment by atatanasov** [comment]
Could you give me a code sample, that can be in use for replication of this issue.

**Comment by ehamill** [comment]
var grid = $('#TimeTracker').grid({
                dataSource: "?handler=TimeTracker", 
                uiLibrary: 'bootstrap',
                primaryKey: 'id', 
                inlineEditing: { mode: 'command', managementColumn: false },
                autoload: false, resizableColumns: true, responsive: true,
                columns: [
                    { width: 90, align: 'center', renderer: editManager2},
                    { field: 'title', title: "Woid", editor: false, mode: 'editOnly', width: 160 },
                    { field: 'formatTimeStartBy', title: "FmtTimeStartBy", type: 'date', format: 'mm/dd/yyyy hh:MM TT', editor: true, width: 180 },
                    { field: 'formatTimeLogIn', title: "FmtLogin", type: 'date', format: 'mm/dd/yyyy hh:MM TT', editor: true, width: 180 },
                     { field: 'formatTimeLogOut', title: "LogOut", type: 'date', format: 'mm/dd/yyyy hh:MM TT', editor: true, width: 180 },

Have this with all time in AM:
![image](https://user-images.githubusercontent.com/6712158/38376024-4101eca0-38bd-11e8-9233-b381e94cc0e7.png)

You click Edit and change all to PM, hit Update, but everything returns AM:
![image](https://user-images.githubusercontent.com/6712158/38376046-51c6e27a-38bd-11e8-9599-f73f4d8eadde.png)
Returns this:
![image](https://user-images.githubusercontent.com/6712158/38376056-59516772-38bd-11e8-8bde-8748a52b5d7e.png)

Changes from PM to AM work great.

Thanks.

**Comment by ehamill** [comment]
I'm getting the data using 'record':
alert(JSON.stringify(record));
Just found that "newValue" works. 

grid.on('cellDataChanged', function (e, $cell, column, record, newValue) {
                alert('The value for "' + column.field + '" is changed to "' + newValue + '"'); //Works!!
                alert(JSON.stringify(record)); //Doesn't notice AM to PM change, only PM to AM

**Comment by atatanasov** [comment]
We improved the new development version to support this. In your case you should use type: 'datetime' instead of date in order to do that. You can see an example at https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.InlineEditing.inlineEditing.mode.DateTime.html

You can find the new development build only in github at https://github.com/atatanasov/gijgo/tree/master/dist
