### ISSUE TITLE
NPM out of date - please update

### ISSUE THREAD

**Issue by petewulf** [atatanasov/gijgo#324]
The NPM Repo is out of date, latest version is 1.80, on github its already 1.96.

Thanks :)

**Comment by atatanasov** [comment]
I updated https://www.npmjs.com/package/jquery-grid to 1.9.6. Please start using https://www.npmjs.com/package/gijgo as official package. We keep that package always up to date.

**Comment by petewulf** [comment]
Thanks much - but it would be neat if the single packages would also be up to date because i only need "datepicker-bootstrap" with about 14kb instead of the whole package with nearly 170kb.
