### ISSUE TITLE
ncaught TypeError: Cannot read property 'weekDaysShort' of undefined when using locale option

### ISSUE THREAD

**Issue by petewulf** [atatanasov/gijgo#325]
Hi again,

Used version: 1.96

Just encountered another bug:

When using the **locale** option on initializing like

```
$('#date').datepicker({
uiLibrary: 'bootstrap4',
iconsLibrary: 'fontawesome',
locale: 'en-en',
format: 'dd.mm.yyyy'
});
```

an uncaught error occurs:

> Uncaught TypeError: Cannot read property 'weekDaysShort' of undefined

It's no matter which locale setting i use.

Without setting this option, everything works fine.

Thanks

**Comment by atatanasov** [comment]
The locale should be en-us. We don't support en-en yet.

**Comment by edu526** [comment]
Hi. 

I have the same error:
Used version: 1.96

`$('#datepicker').datepicker({
        locale: 'es-es',
        format: 'dd/m/yyyy',
	keyboardNavigation: true,
	modal: true,
	header: true,
	footer: true,
	uiLibrary: 'bootstrap4'
});`

an uncaught error occurs:

> Uncaught  TypeError: Cannot read property 'weekDaysShort' of undefined

Thanks

**Comment by HumbertoEspinoza** [comment]
61/5000
I downloaded the project and added the language to the gj.core array in "gijgo.js" and that is all.
it looks like this.

gj.core = {
    messages: {
        'en-us': {
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            monthShortNames: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            weekDaysMin: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
            weekDaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
            weekDays: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            am: 'AM',
            pm: 'PM',
            ok: 'Ok',
            cancel: 'Cancel',
            titleFormat: 'mmmm yyyy'
        },
        'es-es': {
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthShortNames: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            weekDaysMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
            weekDaysShort: ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
            weekDays: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
            am: 'AM',
            pm: 'PM',
            ok: 'OK',
            cancel: 'Cancelar',
            titleFormat: 'mmmm yyyy'
        }
    },
