### ISSUE TITLE
grid with rowDataBound event on local data and ajax

### ISSUE THREAD

**Issue by nikudale** [atatanasov/gijgo#326]
Hi,

I am doing something wrong, I took examples from grid with ajax call data and local data. with ajax call, I am getting rowDataBound event and with local data its not calling.
as example, i just edit both examples and added below line.

 grid.on('rowDataBound', function (e, $row, id, record) {
         $row.on('click', function (e) { alert('dblclick is fired for row with id=' + !record.Active + '.');
                                        
                                       });
     });

Thanks
Nitin

**Comment by atatanasov** [comment]
You have to assign function to this event in the configuration of the grid like this http://gijgo.com/Temp/9225585c-8ec0-4e0f-9177-d5c644b92585.html

If you assign this function after the initialization like in your example the event is already fired and you never go into that function.

You can also use autoLoad: false and .reload() if you want to use this event configuration with your example above.
