### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [atatanasov/gijgo#329]
Greetings, 

I just made a logo for your project, hope you like it. Let me know if you want me to add/modify something, else if you liked it, I'll send the files in a pr (with more variations).

![](https://s9.postimg.org/podyc9my7/image.png)

**Comment by michaelizer** [comment]
I can't argue, that's a great-looking robot!. It was a pleasure, I'm getting into web design and I will be surely using your toolbox. Thanks for it and keep up the good work

**Comment by atatanasov** [comment]
Thank you!
