### ISSUE TITLE
TreeView Drag And Drop no work

### ISSUE THREAD

**Issue by hiwoei** [atatanasov/gijgo#330]
hi~
vs2015 asp.net mvc

when i use link to cdn.jsdelivr.net in view  page
<script src="https://cdn.jsdelivr.net/npm/gijgo@1.8.2/combined/js/gijgo.min.js" type="text/javascript"></script> 
  Drag And Drop work fine

but

when i download js and css to view 
 <script src="@Url.Content("~/Scripts/gijgo/combined/gijgo.js")" type="text/javascript"></script>

the Drag And Drop no work

and when i try 

 <script src="@Url.Content("~/Scripts/gijgo/combined/gijgo.js")" type="text/javascript"></script>

to web first layer view page , <script src="@Url.Content("~/Scripts/gijgo/combined/gijgo.js")" type="text/javascript"></script>

is work fine , but   jquery.ui.datepicker.js   will be no work

have any idea?

thank you~~~

**Comment by atatanasov** [comment]
1. I would recommend you to upgrade to version 1.9.6.
2. Could you tell me if you have any javascript errors when you use local js files. Can you check if the file is loaded correctly.
3. If you want to use jqueryui datepicker, then the jqueryui.js needs to be included after the gijgo.js. If gijgo.js is included after jqueryui.js, then gijgo datepicker override jqueryui datepicker and etc.

**Comment by hiwoei** [comment]
hi~
2.
when i use local js file , no error show in console , but when i  drag and drop item , the console show
Error: no such method 'isOver' for droppable widget instance

when i use https://cdn.jsdelivr.net/npm/gijgo@1.8.2/combined/js/gijgo.min.js , no error
and  jquery.ui.datepicker.js will be no  work

3. 
i try , if local  gijgo.js after  jqueryui.js , drag and drop is work , but jquery.ui.datepicker.js will be no work
   if   jqueryui.js  after  local gijgo.js , drag and drop no  work

**Comment by atatanasov** [comment]
I see. jqueryui doesn't work well with gijgo. I would recommend you to use just one of these libraries. just jqueryui or just gijgo. Sorry for the inconvenience.

**Comment by hiwoei** [comment]
Thank you for Help and gijgo :)
