### ISSUE TITLE
Grid widget: how to get dIfferent content alignment between grid-header and grid-body?

### ISSUE THREAD

**Issue by francescosaverio** [atatanasov/gijgo#331]
As for the subject, any hint to accomplish it?
Thank You.

**Comment by atatanasov** [comment]
You can use http://gijgo.com/grid/configuration/column.cssClass and http://gijgo.com/grid/configuration/column.headerCssClass about it.

**Comment by francescosaverio** [comment]
Actually that's what i tried, still I guess I missed the correct syntax info, i.e.:
I tried using:
1) headerCssClass: 'col-xs-1 text-align:center', cssClass: 'col-xs-1'
2) headerCssClass: 'col-xs-1 center', cssClass: 'col-xs-1'
3) maybe some further variant...
but unsuccessfully.
I mean: while 'col-xs-.....' column properties work fine, I couldn't succeed in aligning my header and body grid text according to my (syntactically wrong, I guess) specifications. 
Text alignment keeps getting left-sided.
Any hint? Thanks a lot!
