### ISSUE TITLE
DatePicker date moves backwards when clicking the calendar icon with custom format

### ISSUE THREAD

**Issue by Cpousson** [atatanasov/gijgo#333]
To reproduce:
- use a custom format:
`$('#datepicker').datepicker({ format: 'mmmm yyyy' });`

- Choose a date
- Click calendar icon one or many times

The date will walk backwards a month with each click of the calendar.

**Comment by atatanasov** [comment]
We fixed that in the new development build. You can find the new development build in the dist folder at github.
