### ISSUE TITLE
tree.addNode double entries

### ISSUE THREAD

**Issue by tbellembois** [atatanasov/gijgo#334]
hello,
I have an issue with tree.js v1.9.6 using the `addNode` method.
I have double node entries created (see screenshot "new folder" nodes).
![tbellembois](https://user-images.githubusercontent.com/18054222/39085482-23e2394a-4583-11e8-812c-57238f275d26.png)
 The first one is created under the `gj-list gj-list-bootstrap gj-hidden` ul, the second one under `gj-list gj-list-bootstrap` ul.
Here is my code:
```
var nodeId = tree.getSelections()[0];
...
var parent = tree.getNodeById(nodeId);
tree.expand(parent);
tree.addNode({ id: result.id, text: "new folder", url: "", hasChildren: true, lazy: true, icon: "" }, parent);
// result.id is returned from ajax
```
Have I missed something ?
Thanks.

**Comment by atatanasov** [comment]
I'm not able to replicate the issue. Everything seems to be working fine with with the following code sample:
```
<html>
<head>
    <meta charset="utf-8" />
    <title>Treeview Example</title>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/css/gijgo.min.css" rel="stylesheet" type="text/css">
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/js/gijgo.min.js"></script>
</head>
<body>
    <button onclick="add()">Add node1</button>
    <button onclick="tree.addNode({ Title: 'node1-1' }, tree.getNodeByText('node1'))">Add node1-1</button>
    <button onclick="alert(tree.getNodeByText('node1').html())">Get node1</button>
    <div id="tree"></div>
    <script>
        var tree;
        $(document).ready(function () {
            tree = $('#tree').tree({
                primaryKey: 'id',
                dataSource: '/Locations/Get'
            });
        });
        function add() {
            var nodeId = tree.getSelections()[0];
            var parent = tree.getNodeById(nodeId);
            tree.expand(parent);
            tree.addNode({ id: 77, text: "new folder", url: "", hasChildren: true, lazy: true, icon: "" }, parent);
        }

    </script>
</body>
</html>
```

Please reopen if you can provide code sample

**Comment by atatanasov** [comment]
Thanks for the additional details. I was able to replicate the issue and fix it. This is fixed just in the development version for now. You can find the development build in the dist folder at github.

**Comment by tbellembois** [comment]
Thanks a lot.

**Comment by stvowi** [comment]
It happen, wenn you insert a record via ajax call which will give back a new ID before you call the content of the ADD function. The sample alone without ajax is working.
