### ISSUE TITLE
Event not firing 2nd time

### ISSUE THREAD

**Issue by akberalikhan** [atatanasov/gijgo#336]
so i have a dropdown and on its change event i execute the following code and it works just fine
`$('#ddl-section').on("change", function () {
          //  grid.clear();
            $("#hidden-section-id").val($('#ddl-section :selected').val());
            var selectedSectionId = $('#ddl-section :selected').val();
            grid = "";
            grid = $('#grid').grid({
                primaryKey: 'Id',
                dataSource: rootUrl + "page/get1?Id=" + selectedSectionId,
                columns: [
                    { field: 'Id', width: 56 },
                    { field: 'Text', title: 'Text' },
                    { field: 'Url', title: 'Url' },
                    { field: 'Description', title: 'Description' },
                    { field: 'IsActive', title: 'IsActive', width:90 },
                    { field: 'DisplayOrder', title: 'Order', width:90 },
                     { width: 64, tmpl: '<span >edit</span>', align: 'center', events: { 'click': Edit } }

                ],
                pager: { limit: 5 }
            });

        });`

but it does not work the 2nd time when the change event is fired.

**Comment by atatanasov** [comment]
Can you send me a code sample that I can use for the replication of this issue. Everything seems to work fine with the change event in the following example: http://gijgo.com/dropdown/events/change

**Comment by atatanasov** [comment]
I will close the issue. Please reopen if you have replication steps with more details.

**Comment by akberalikhan** [comment]
sorry i was little busy with other tasks. Now I am back. 
`
 <script type="text/javascript">

    var gvar = 123;
    var rootUrl = "@Url.Content("~")";
    var grid;

$('#office-personnel').on("click", function () {
         alert('hmm:'+gvar);
         grid = "";
         //grid.reload();
         grid = $('#grid').grid({
             primaryKey: 'Id',
             //dataSource: rootUrl + "person/GetOfficeMembersForEditing?Id=" + gvar,
             dataSource: rootUrl + "Person/Get?Id=" + gvar,
             columns: [
                 { field: 'Id'},
                 { field: 'FirstName', title: 'First Name' },
                  { field: 'LastName', title: 'Last Name' },
                 { field: 'Designation', title: 'Designation' },
                 { field: 'IsActive', title: 'IsActive', width: 90 },
                 { width: 64, tmpl: '<span >Edit</span>', align: 'center', events: { 'click': Edit } }
             ],
             pager: { limit: 5 }
         });
     });`
if I put a break point on the controller method it is hit twice but still it populate the grid. Beside hitting twice the event is not making a call 2nd time to controller method. I put the alert statement just to verify and it does show me the message but the controller method is not called
