### ISSUE TITLE
restrict invalid input

### ISSUE THREAD

**Issue by goravbhootra** [atatanasov/gijgo#339]
If a user enters invalid input, lets say text, and then clicks on the calendar button, calendar shows NaN. After that, even if the input is removed and calendar button clicked again, it continues to show NaN. Is there a way to check valid value and reset the field to nil, if the input is invalid instead of calendar being stuck at NaN.

Thanks.

**Comment by atatanasov** [comment]
We fixed that in the new development version. You can find the new development version in the dist folder at Github
