### ISSUE TITLE
jqgrid is automatically chnaging dates as per timezone of local machine .

### ISSUE THREAD

**Issue by Nileshdcool** [atatanasov/gijgo#34]
Hi , 

I have used jqgrid from your plugin. But there is slightly issue with datecolumn as it is automatically chnaging the dates as per timezone . Please suggets

**Comment by atatanasov** [comment]
Hi,

Please user renderer function for your date column and format the date with library like moment.js.

```
 <table id="grid"></table>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.0/moment.min.js"></script>
 <script>
     $('#grid').grid({
         dataSource: '/DataSources/GetPlayers',
         columns: [
             { field: 'ID', width: 24 },
             { field: 'Name' },
             { field: 'DateOfBirth', title: 'Date',
               renderer: function (value) {
                   return moment(value).format('MM-DD-YYYY');
               }
             }
         ]
     });
 </script>
```

**Comment by Nileshdcool** [comment]
the above mentioned solution is not working .. Below is my code . I have tried for startime. It is not formating 

function ReportedCallLoadData() {
    grid = $("#grid").grid({
        dataKey: "ID",
        uiLibrary: "bootstrap",
        columns: [
            { field: "ClientName", title: "Client Name", sortable: true },
            {
                field: "StartTime", title: "Start Time", sortable: true, type: 'date', renderer: function (value) {
                    return moment(value).format("MM-DD-YYYY");
                    //return moment(value, 'DD/MM/YYYY hh:mm A');
                }
            },
            { field: "EndTime", title: "End Time", sortable: true, type: 'date', format: 'dd/mm/yyyy hh:MM TT' },
            { field: "ActualDate", title: "Actual Date", sortable: true, type: 'date', format: 'dd/mm/yyyy' },
            { field: "CreatedOn", title: "Created On", sortable: true, type: 'date', format: 'dd/mm/yyyy hh:MM TT' },
            { title: "", field: "Edit", width: 34, type: "icon", icon: "glyphicon-pencil", tooltip: "Edit", events: { "click": Edit } },
            { title: "", field: "Delete", width: 34, type: "icon", icon: "glyphicon-remove", tooltip: "Delete", events: { "click": DisplayDeleteCommentsBox } }
        ],
        pager: { enable: true, limit: 5, sizes: [2, 5, 10, 20] }
    });
}

**Comment by Nileshdcool** [comment]
I have also tried on your demo live compiler , with examples given . Its not at all working . this rendere implementation is nowhere mentioned in your documention as well. Please suggest for this

**Comment by atatanasov** [comment]
The renderer function is added in version 1.0. Probably you are using old version and that's why the renderer doesn't work. You can use http://gijgo.com/Grid/Events/cellDataBound as alternative if you can't upgrade to 1.0.

Actually you are having this issue, because that's how javascript works. It always convert the date to the current timezone.

If you want to have all dates in one timezone you can use http://momentjs.com/timezone/ or format the date on the server and display it in regular grid column.
