### ISSUE TITLE
Problem with used 'locale' property

### ISSUE THREAD

**Issue by Gertrido** [atatanasov/gijgo#342]
Good time of day. Faced with the problem, when I use the property 'locale' of objects: 'Datepicker, Editor'.
The use of the Datepicker:
```javascript
  $(`#inputExpStart-${currentIndex}`).datepicker({
    uiLibrary: 'bootstrap4',
    format: 'dd.mm.yyyy',
    weekStartDay: 1,
    locale: 'ru-ru',
  })
```
The error text:
![image](https://user-images.githubusercontent.com/7986550/39357031-3d96610e-4a1a-11e8-92b5-de509352dbfe.png)

The use of the Editor:
```javascript
    $("#js-editor-profSkills").editor({
      uiLibrary: 'bootstrap4',
      locale: 'ru-ru',
    })
```
![image](https://user-images.githubusercontent.com/7986550/39357249-fbaeaa66-4a1a-11e8-9c64-5499566d9429.png)

Without the locale everything works fine. Using version 1.9.6 from [https://yarnpkg.com/en/package/gijgo](url)

**Comment by atatanasov** [comment]
everything seems to be working fine with version 1.9.6. Here is an example: http://gijgo.com/Temp/d46f66c3-ae73-4a30-959b-f5020f4506d3.html

Could you check if you use the latest gijgo.js version with the latest messages.ru-ru.js file.

**Comment by Gertrido** [comment]
I'm sorry. Because of their negligence I have not connected the file with the language. I tried to do it and got the error: **'gj is not defined'**. I have read this issue: [https://github.com/atatanasov/gijgo/issues/133](https://github.com/atatanasov/gijgo/issues/133), but it hasn't helped.
I use es-2015 modules in my project. And I think the mistake is that gj is not export.
Use: 
``` javascript 
import 'gijgo/js/gijgo.min.js'
import 'gijgo/js/messages/messages.ru-ru.min.js'
```
I guess my only option is to abandon the package and and use the insertion of a cdn-links in an html -document?

**Comment by ruizbtoni** [comment]
This works:
https://gijgo.com/datepicker/example/localization
