### ISSUE TITLE
tree.getAll not detecting DragAndDrop changes

### ISSUE THREAD

**Issue by avondev** [atatanasov/gijgo#344]
Hi.

The tree component has been working pretty well for me except for one thing: tree.getAll() works correctly after addNode() and removeNode(), but not when using DragAndDrop to rearrange the order of nodes. The DragAndDrop functionality is visually correct, but calling getAll() returns the tree data as if nothing moved.

From what I can see in the code, it indeed looks like only the visuals are updated but the actual node data isn't getting updated.

In my application, I have a tree and the user is able to add, remove, and rearrange the tree. Then there's a "save changes" button that processes the data from getAll(), so it would be nice if the tree state would be updated along with D&D.

For now I can just remove nodes and re-add them, but there can be potentially hundreds of nodes in a single tree for my application so it would be much more convenient to D&D. I could also try to parse the tree HTML which will not be fun. Any other interim suggestions would be appreciated.

Thank you.

**Comment by pluempyx** [comment]
I tried the development version from you commit (70ba903). As far as i can tell this does not work correctly. If I have a list with 3 elements on the same level and i move the top one to the bottom the view works fine but getAll() is wrong. The former top element is represented as a child of the former middle element.

Initial situation (view and getAll):
> Dog
> Cat
> Parrot

View after Drag&Drop:
> Cat
> Parrot
> Dog

getAll after Drag&Drop:
> Cat
==> Dog
> Parrot
