### ISSUE TITLE
Multiple Delete not working

### ISSUE THREAD

**Issue by NabeelMahmood2** [atatanasov/gijgo#346]
After multiple select using check boxes in gijgo grid, i cannot delete multiple rows, only single row can be deleted.

**Comment by atatanasov** [comment]
Our .removeRow method is able to delete only 1 row. Could you try to use .getSelections() to get all selections and call .removeRow multiple times in order to do that. The code should be something like:

```
var selections = grid.getSelections();
for (var i = 0; i < selections.length; i++) {
  grid.removeRow(selections[i]);
}
```
