### ISSUE TITLE
Grid - allow customization of the management column

### ISSUE THREAD

**Issue by rsamp** [atatanasov/gijgo#348]
For example, I'm using the Grid widget with Bootstrap4 and the width of the management column overpowers the other columns in my grid.

Maybe `inlineEditing.managementColumn` can even accept an object rather than boolean and there could be additional configs to allow further customization, such as fontSize, cssClass, etc.?

**Comment by atatanasov** [comment]
You can build the management column as you want and call edit, update, cancel and delete methods from buttons inside that new custom column. Here is an example http://gijgo.com/grid/methods/edit

see also: http://gijgo.com/grid/methods#InlineEditing
