### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined     at gijgo.js:1080

### ISSUE THREAD

**Issue by vishalpatil14287** [atatanasov/gijgo#35]
I am facing this issue @ gijgo.js
Exception : Uncaught ReferenceError: jQuery is not defined at gijgo.js:1080

Please reply soon.
Its very argent

**Comment by atatanasov** [comment]
gijgo depends on jquery and in your case a reference to jquery library is missing. Please add jquery to your page/project.
