### ISSUE TITLE
Scrollable dialog with dropdown

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#353]
Workspace: Jquery 3.2.1, Bootsrap 3.3.7, newest Firefox

Nothing happen, if I click to the botton for the select field. 
The container for the list elements is behind the dialog or not visible if I set a little height.

```

dialog = $('#dialog').dialog({
    autoOpen: false,   
    scrollable: true,
    minWidth: 500, maxWidth: 850, height: 600, width: 820            
});


$('#form_category').dropdown({
	placeholder: 'Select One...',
	uiLibrary: 'bootstrap', 
	iconsLibrary: 'fontawesome', 
	maxHeight: 500, 
	width: '100%'
});

```

I dont use ajax - generate the full html-code for the select field.

Issue #340 is not solved in my eyes.

I need a bugfix for this control as soon as possible. Thanks a lot!

**Comment by atatanasov** [comment]
This is fixed in the new development version. Please check the latest build in github located in the dist folder.
