### ISSUE TITLE
Scrollable dialog with timepicker

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#354]
Workspace: Jquery 3.2.1, Bootsrap 3.3.7, newest Firefox

Nothing happen, if I click to the botton for the input field. 
The container for the clock element is behind the dialog - only visible if the dialog was closed.

```
dialog = $('#dialog').dialog({
    uiLibrary: 'bootstrap' ,
    autoOpen: false,
    scrollable: true,
    minWidth: 500, maxWidth: 850, height: 600, width: 820			     
});

$('#form_return_date').timepicker({ 			
	locale: 'de-de',			
	mode: '24hr',			
	uiLibrary: 'bootstrap' 
});


```

**Comment by atatanasov** [comment]
This is fixed in the new development version. Please check the latest build in github located in the dist folder.
