### ISSUE TITLE
Not an issue, just a help request about "grid" widget

### ISSUE THREAD

**Issue by francescosaverio** [atatanasov/gijgo#355]
Hi, Mr. Atanasov!

As in the subject, and being supported by the attached picture,
I would like to ask Your kind support to implement a simple "select all - toggle" function, by clicking the check box (red-circled ) in the "Input search arguments..." panel, thus getting all of the check boxes in the grid (red-rectangle bounded) as "all checked" (and vice-versa, of course). 

The check box column in the grid widget has been specified as follows:
- { field: 'SelectByCheckBox', title: 'Sel.', type: "checkbox", editor: true, mode: 'editOnly', align: 'center',  ..... }

The "select all" check box in the "Input search arguments..." panel has been specified as follows:
- ....<label for="chkb-checked"></label><input type="checkbox" id="txtSelect" />....

Thanks a lot in advance.
Francesco.
![selectallfeature](https://user-images.githubusercontent.com/12872609/39709809-6cd2594e-520a-11e8-9093-837d942d18bd.jpg)

**Comment by atatanasov** [comment]
We are not planning to support that in future version.

You can build a custom code that is doing that. You can use as an example the following sample:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Example</title>
  <script src="/Areas/Development/dist/libraries/jquery/jquery.js"></script>
  <script src="/Areas/Development/dist/combined/js/gijgo.js" type="text/javascript"></script>
  <link href="/Areas/Development/dist/combined/css/gijgo.css" rel="stylesheet" type="text/css">
</head>
<body style="padding: 8px;">
 <table id="grid"></table>
  <button onclick="grid.find('input').prop('checked', true)">Select All</button>
 <script>
     var grid = $('#grid').grid({
         dataSource: '/Players/Get',
         columns: [
             { field: 'ID', width: 56 },
             { field: 'SelectByCheckBox', title: 'Sel.', type: "checkbox", editor: true, mode: 'editOnly', align: 'center' },
             { field: 'PlaceOfBirth', editor: true, mode: 'readOnly' }
         ]
     });
 </script>
</body>
</html>
```

**Comment by francescosaverio** [comment]
Thank You so much, Mr. Atanasov.
It worked like a charm! 
In fact, trouble was my ignorance about the correct syntax to reference a column field belonging to the "grid" widget.
By the way, reading the line:
<button onclick="grid.find('input').prop('checked', true)">Select All</button>
I see You referenced the check-box column by means of the "input" notation; I wonder if could be possible to reference such column by its "field" property specification (i.e.: "SelectByCheckBox").
Also, You commented "We are not planning to support that in future version"... which function/property/... are You talking about? ... Or... Maybe did You mean no more support for silly questions like mine ones )))) ?
Thank You so much again. I believe Your widgets really gives an excellent trade-off among complexity, learning curve and industry standard requirements!!!

**Comment by francescosaverio** [comment]
p.s.: 
complementary  about above, and according to the attached picture, I got stuck in trying to find the way to check / uncheck a specific row checkbox as I select the corresponding row.
Of course I can intercept 'Rowselect' and 'Rowunselect' events and I can easily get the 'id' of the selected / unselected row (...me, the Genius...), but ... No way to make the corresponding checkbox as checked / unchecked .... 
Please, help!

![help](https://user-images.githubusercontent.com/12872609/39810429-811057ce-5374-11e8-8f59-4c3046056eea.jpg)
Thank You in advance.
Francesco

**Comment by atatanasov** [comment]
You can use our column.renderer config function to render the chechbox with id or attributes that you can use for selection of the element after that. I mean that we are not going to add new method about that. We are going to try to answer all questions (doesn't matter silly or not) added here as tickets

**Comment by francescosaverio** [comment]
Yes, using  "column.renderer" config function is actually what I tried to do at once.
Also, the example You addressed is perfect to understand how to change values / cell attributes / ... for all the cell in a specific column.
But I keep getting in trouble, for example, as I try to set the value of a specific cell (i.e.: row) of the selected column; quoting my previous post, I'd need to check / uncheck the single check-box defined by "Sel." column and row having "id" = 4.
Sure my troubles come from my uncapability to find out the right syntax as needed (or, more likely, from my lack of intuition...), anyway fact is:  so far I could not find the proper example / doc. reference to accomplish my goal.
Also, I know I'd intensively use such functionality, so.... I'd really appreciate Your help.

Thank You in advance.
Francesco.

**Comment by francescosaverio** [comment]
SOLVED.
![onrowselect](https://user-images.githubusercontent.com/12872609/39923757-7cbc2a58-5514-11e8-903b-cc8267c49bf0.jpg)

In attachment the code modules, based on the "grid.on('rowUnselect', ..." and "grid.on('rowSelect', ...".
Also, consistence between the select all /unselect all checkbox ('txtSelect') and the selected / unselected row in the grid is guaranteed, by means of counters for "total of selected rows" and "total of the grid rows". That was exactly I was striving for...))))
Thanks to completeness of "grid" widget, in terms of configuration paramaters, events and methods .
Francesco.
