### ISSUE TITLE
Add functionality to load children from multiple children fields

### ISSUE THREAD

**Issue by muhammad-akmal** [atatanasov/gijgo#356]
At the moment tree can be configured to load children from one field. My tree nodes have multiple children fields(lists). is it possible to define more then one children nodes? For Example:

var tree = $('#tree').tree({
         **childrenFields:  ['**childPages**','childControls', 'childOptions'],**
         dataSource: [ { text: 'InputPages', **childPages**: [ { text: 'Admin' } ],**childControls**: [ { text: 'textbox' }, { text: 'dropdown' } ],**childControlOptions**: [ { text: 'isRequired' },{ text: 'isRed' } ] } ]

     });

**Comment by atatanasov** [comment]
No. This is not an option right now. The only option that you have is to transform your server response to the tree with code manually on the server side.
