### ISSUE TITLE
Image not supported

### ISSUE THREAD

**Issue by NarenGummadi** [atatanasov/gijgo#36]
Is there a way to show an image per user?

**Comment by atatanasov** [comment]
You can use column.renderer function in order to do that.
You can find documentation about this function at http://gijgo.com/grid/Configuration/column.renderer

Here is an example:
```
<table id="grid" data-source="/Grid/GetPlayers"></table>
 <script>
     var imageRenderer = function (value, record, $cell, $displayEl) {
         $displayEl.append('<img src="https://lh4.ggpht.com/wKrDLLmmxjfRG2-E-k5L5BUuHWpCOe4lWRF7oVs1Gzdn5e5yvr8fj-ORTlBF43U47yI=w300" />');
     };
     $('#grid').grid({
         uiLibrary: 'jqueryui',
         columns: [
             { field: 'ID', width: 30 },
             { field: 'image', renderer: imageRenderer }
         ]
     });
 </script>
```

**Comment by NarenGummadi** [comment]
It loads image however, sorting any column adds new image again which makes the column hold same image repeatedly.
Tested here - http://gijgo.com/LiveEdit/Index/jquery-grid-bootstrap.html?component=grid and can reproduce the issue.

**Comment by atatanasov** [comment]
yes. You always need to clear the display element in the renderer function.
If you add $displayEl.empty(); in the renderer function everything is going to work fine
