### ISSUE TITLE
Issue with multiple datepicker in a single page

### ISSUE THREAD

**Issue by suvasishm** [atatanasov/gijgo#360]
`<body>
        <input id="d1" class="datepicker" width="270" />
  	<input id="d2" class="datepicker" width="270" />
  	<input id="d3" class="datepicker" width="270" />
    <script>
        $('.datepicker').datepicker({
            uiLibrary: 'bootstrap'
        });
    </script>
</body>`

With the above code, the datepicker isn't working. The date widget appears and disappears in a blink.

**Comment by atatanasov** [comment]
This is known issue and we are going to fix that in future versions. Please init all datepickers one by one as a temporary workarround.
