### ISSUE TITLE
how can i deal with custom response json

### ISSUE THREAD

**Issue by duwei54** [atatanasov/gijgo#363]
the platform defined the response json format like this:
`{
    "status": 1,
    "code": 200,
    "data": [
        {
            "checked": false,
            "disabled": false,
            "hasChildren": false,
            "id": 1,
            "parentId": null,
            "text": "TEXT1"
        },
        {
            "checked": false,
            "disabled": false,
            "hasChildren": true,
            "id": 2,
            "parentId": null,
            "text": "TEXT2"
        }
    ]
}`
I used lazyLoading.
And I try find an event name like responseHandle to convert this response,and the data is what we wanted,  but i failed. 
then. Is there a way to achieve mygoal ?
I am sorry to my worse English.

**Comment by atatanasov** [comment]
You can use our render method in order to do that. You can see an example at http://gijgo.com/tree/methods/render

**Comment by duwei54** [comment]
It's very careless of me.thank you very much! @atatanasov
