### ISSUE TITLE
Grid is not reloaded if I use remote data source

### ISSUE THREAD

**Issue by vsile** [atatanasov/gijgo#365]
My URL ('/tasks') returns next JSON:
[{"Id":1,"Task":"First task"},{"Id":2,"Task":"Second task"}]

If I use next code (with remote data):
```
var grid = $('#grid').grid({
                dataSource: '/tasks',
                columns: [ { field: 'Task'} ]
            });
grid.reload({ Task: "First" });
```
I get two strings in my grid! (I expect to get only one string with "First task")

If I use next code (with local data in variable):
```
var data = [{"Id":1,"Task":"First task"},{"Id":2,"Task":"Second task"}]
var grid = $('#grid').grid({
                dataSource: data,
                columns: [ { field: 'Task'} ]
            });
grid.reload({ Task: "First" });
```
I get one string in my grid with "First task" (as I expect)

I want to use remote data, but I can't use reload function correctly.
What's wrong?

**Comment by atatanasov** [comment]
Could you review our examples at https://github.com/atatanasov/gijgo-asp-net-examples. You can see how you can do it from there.

**Comment by vsile** [comment]
I use mongodb and golang to generate data.
I found the way to send the data from to variable in javascript (with "html/template"). So I get it work...
