### ISSUE TITLE
How to use hotkeys for grid editing?

### ISSUE THREAD

**Issue by vsile** [atatanasov/gijgo#366]
I would like to use Ctrl+Enter to update my row. But I can only click the button "Update"..

Is it possible to make hotkeys work for grid?

**Comment by atatanasov** [comment]
We don't support such features yet. We may add this as a feature in next versions.

**Comment by vsile** [comment]
To support this feature I just add in gijgo.js after
```
$editorField = $('<input type="text" value="' + value + '" class="gj-width-full"/>'); 
```
the next code:
```
$editorField.on('keyup input focus', function(e) {
    if (e.ctrlKey && e.keyCode == 13) { $grid.update(record.Id) }
    else if (e.keyCode == 27) { $grid.cancel(record.Id) }
});
```

**Comment by atatanasov** [comment]
You have to move this code outside of gijgo.js, because you are going to lose it after upgrade to new gijgo.js version
