### ISSUE TITLE
How to add new row in the beginning of rows?

### ISSUE THREAD

**Issue by vsile** [atatanasov/gijgo#367]
Is there a way to add new row in the beginning of rows in grid? (above all)

**Comment by vsile** [comment]
To get it I replace:
`$grid.children('tbody').append($row);`
to
`$grid.children('tbody').prepend($row);`
in renderRow method..
Now it works..

**Comment by vsile** [comment]
Ok. I've got it!
I just replace in gijgo.js in renderRow method:
```
$grid.children('tbody').append($row);
```
to:
```
$grid.children('tbody').prepend($row);
```

and (important!) replace this code in loadData method:
```
        for (i = 0; i < rowCount; i++) {
            if (i < recLen) {
                $row = $rows.eq(i);
                gj.grid.methods.renderRow($grid, $row, records[i], i);
            } else {
                $tbody.find('tr[data-role="row"]:gt(' + (i - 1) + ')').remove();
                break;
            }
        }
        for (i = rowCount; i < recLen; i++) {
            gj.grid.methods.renderRow($grid, null, records[i], i);
        }
```
to:
```
        $tbody.find('tr[data-role="row"]').remove();
        for (i = 0; i < recLen; i++) {
            gj.grid.methods.renderRow($grid, null, records[i], i); 
        }
```

Now it works!

**Comment by atatanasov** [comment]
We do not support this yet. I think that would be best if you place this code in a separate file, because you can lose it if you upgrade gijgo.js to new version.
