### ISSUE TITLE
Disabling checkbox in grid

### ISSUE THREAD

**Issue by shashiankam** [atatanasov/gijgo#37]
I am trying to disable a check box in a grid when the corresponding status of record is yes. Record status is one of the column in the grid. I didn't find any option to disable a checkbox based on a value in grid Row. Could you please me to provide a solution for this.

Thanks

**Comment by atatanasov** [comment]
You can use column.renderer in order to do that. You can find documentation about this option at http://gijgo.com/Grid/Configuration/column.renderer
Here is an example:
```
 <table id="grid" data-source="/Grid/GetPlayers"></table>
 <script>
     $('#grid').grid({
         columns: [
             { field: 'ID', width: 30 },
             { field: 'Name' },
             { field: 'PlaceOfBirth'},
             { title: 'IsBulgarian',  renderer: function (value, record) { return record.PlaceOfBirth.indexOf('Bulgaria') > -1 ? '<input type="checkbox" checked />' : '<input type="checkbox" />'; }  }
         ]
     });
 </script>
```

**Comment by shashiankam** [comment]
How can I use this if the selectiontype is multiple and selectionmethod is checkbox?

**Comment by atatanasov** [comment]
You have to remove the configuration for selectionMethod if you want to use custom checkboxes and everything should be fine.

**Comment by shashiankam** [comment]
Still I am not getting the checkbox if I use same like above. Could you please help me to resolve it.

 auditGrid = $("#tblRoutingActivityGrid").grid({
                dataSource: dataSet,
                uiLibrary: 'bootstrap',
                primaryKey: 'msdyn_Sequence',
                columns: [
                    { field: "msdyn_routingactivitiesId", title: "Routing Activity", width: 130, sortable: true, fontSize: 4, hidden: true },
                    { field: "msdyn_IsFirstActivity", title: "Is First Activity", width: 70, sortable: true, fontSize: 4, hidden: true },
                    { field: "msdyn_IsLastActivity", title: "Is Last Activity", width: 70, sortable: true, fontSize: 4, hidden: true },
                    { field: "msdyn_CaseWorkbench", title: "Case Workbench", width: 130, sortable: true, fontSize: 4, hidden: true },
                    { field: "msdyn_name", title: "Activity Name", width: 130, sortable: true, fontSize: 4, tmpl: "<a onclick=openRoutingActivity('{msdyn_routingactivitiesId}')>{msdyn_name}</a>" },
                    { field: "msdyn_taskstatus", title: "Magnum Status", width: 70, sortable: true, fontSize: 4, hidden: true },
                    { field: "statuscode", title: "Task Status", width: 70, sortable: true, fontSize: 4 },
                    { field: "msdyn_Sequence", title: "Sequence", width: 60, sortable: true, fontSize: 4 },
                    { field: "msdyn_ischecklist", title: "Is Checklist?", width: 70, sortable: true, fontSize: 4 },
                    { field: "msdyn_ismagnumtask", title: "Is Magnum?", width: 70, sortable: true, fontSize: 4 },
                    { field: "msdyn_checklisturl", title: "Checklist/Magnum URL", width: 110, sortable: false, fontSize: 4, tmpl: "<a onclick=openLink('{msdyn_checklisturl}')>click here</a>" },
                    { field: "msdyn_referenceurlid", title: "Work Instruction URL", width: 100, sortable: true, fontSize: 4, tmpl: "<a onclick=openLink('{msdyn_referenceurlid}')>click here</a>" },
                    { field: "", title: "", width: 20, sortable: true, renderer: function (value, record) { return record.msdyn_ismagnumtask == "Yes" ? "<input type=\"checkbox\" checked />" : "<input type=\"checkbox\" />"; } }

                ],
                pager: { enable: true, limit: 10, sizes: [10, 25, 50] }
            });

**Comment by atatanasov** [comment]
I'm not able to help you without having the whole project. You need to debug in order to see what is going on.
