### ISSUE TITLE
Search multiple columns in grid

### ISSUE THREAD

**Issue by kasbert** [atatanasov/gijgo#371]
It would be nice to be able to search single string from multiple columns.
Currently you have to give column,value pairs for filtering and all must match for row to pass.

**Comment by atatanasov** [comment]
Are you using javascript array as dataSource or your datasource is server based? We allow search by multi columns. Just want to understand more about your architecture in order to be able to help.

**Comment by kasbert** [comment]
I am trying to modify html sourced data example (http://gijgo.com/grid/demos/html-sourced-data)

**Comment by atatanasov** [comment]
You can try to use our .reload method and pass multiple parameters for the colums that needs to be involved as search criterias.
http://gijgo.com/grid/methods/reload

**Comment by kasbert** [comment]
But as I said, all must match for row to pass.

**Comment by atatanasov** [comment]
You have to control this on the backend. Just change your serverside code to do that.
