### ISSUE TITLE
Interface tree incorrectly extends interface JQuery<HTMLElement>

### ISSUE THREAD

**Issue by ManfredLange** [atatanasov/gijgo#378]
Using the following:

- @ types/jquery, version 3.3.2
- @ types/gijgo, version 1.9.0 (which installs a file with version 1.9.6 stated in it's comments)
- Typescript compiler version 2.8.3

Then compiling typescript results in error "Interface 'Tree' incorrectly extends interface JQuery<HTMLElement>".

I also tried https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/gijgo/index.d.ts, commit e1894fb but that didn't make a difference.

Do you happen to have a work around or perhaps even a fix?

**Update:** The "offending" functions seems to be `collapse(node: any, cascade: boolean): Tree;` and `select(node: any) : Tree;`. The file compiles fine when I comment these out. Obviously, that means that those methods are then not available in typescript...

**Comment by atatanasov** [comment]
You can use our example at http://gijgo.com/tree/demos/angular-treeview where in the config.js file you can see how to configure correct versions
