### ISSUE TITLE
Issue in getSelections when pager is enabled

### ISSUE THREAD

**Issue by shashiankam** [atatanasov/gijgo#38]
In below getSelections method, I enabled paging for limit 2 records on page. Then I go to next page and selected next record. but alert is giving as "1" instead of "3". Please check this out and provide me the solution.

<script>
     var grid = $('#grid').grid({
         dataSource: '/Grid/GetPlayers',
         pager: { limit: 2 },
         columns: [ { field: 'ID' }, { field: 'Name' }, { field: 'PlaceOfBirth' } ],
         selectionMethod: 'checkbox',
         selectionType: 'multiple'
     });
     $('#btnShowSelection').on('click', function () {
         var selections = grid.getSelections();
         $.each(selections, function() {
             alert(this);
         });
     });
 </script>

**Comment by atatanasov** [comment]
You need to specify primaryKey in order to be able to get the correct id of you record. In your case when primary key is not set getSelections return position.

You can see an example at http://gijgo.com/Grid/Configuration/primaryKey
