### ISSUE TITLE
showing no date makes datepicker to show on 01-01-0001

### ISSUE THREAD

**Issue by rickersilva** [atatanasov/gijgo#388]
Hi, I´m using this datepicker to select a date range for a search. So the initial value is either min date 01/01/0001 or no date at all.

if I let the 01/01/0001 value or clear the values of the textbx, when user picks on calendar button, it appears also on 0/01/0001 but I prefer it to appear in current month and current day.

Is there a way to set the date showin on the satepicker different than the date showing on the textbox?

**Comment by atatanasov** [comment]
This is fixed in the new development version.
