### ISSUE TITLE
locale: 'ru-ru', format: 'dd mmm yyyy' - TypeError

### ISSUE THREAD

**Issue by Damir-kz** [atatanasov/gijgo#405]
Hello, i am use datepicker bootstrap 4
 <input id="datepicker" width="276" />
 <script>
    $('#datepicker').datepicker({
        locale: 'ru-ru',
        format: 'dd mmm yyyy'
    });
 </script>

error:
Cannot read property 'weekDaysMin' of undefined

**Comment by marvpipe** [comment]
Same here with germany.
regards

**Comment by atatanasov** [comment]
This seems to works fine. You can see my example at
https://gijgo.com/Temp/906d7327-2101-427e-a5cc-d7b201494715.html

Did you include the files below?
<script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/js/messages/messages.de-de.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/js/messages/messages.ru-ru.js" type="text/javascript"></script>
