### ISSUE TITLE
 JavaScript runtime error: 'gj' is undefined

### ISSUE THREAD

**Issue by krisrajz** [atatanasov/gijgo#425]
Just installed the nuget package, added references to CSS and JS and created <table id="grid"></table> and ran the solution, getting error "JavaScript runtime error: 'gj' is undefined"

**Comment by atatanasov** [comment]
You can see our sample project at https://github.com/atatanasov/gijgo-asp-net-examples
Everything looks good. Probably something is not loading in your case.

**Comment by krisrajz** [comment]
Thanks, lemme check.
