### ISSUE TITLE
DatePicker Icon Not showing

### ISSUE THREAD

**Issue by sspost** [atatanasov/gijgo#427]
I am using datepicker v1.9.6 with bootstrap 4
 when I run Gijgo datepicker in Visual studio it works fine but then I deploy it on the server and run it on any browser, it showa the word 'event' instead of the calender icon 
![capture1](https://user-images.githubusercontent.com/43183001/45377414-67ca1000-b5af-11e8-8659-d21ea3dd5f2a.JPG)
![deplooyed 2](https://user-images.githubusercontent.com/43183001/45377419-6ac50080-b5af-11e8-8084-0f8b5d5c5ebd.JPG)

When I look at datepicker.js I see
icons: {
            /** datepicker icon definition.
             */
            rightIcon: '<i class="gj-icon"> event</i>',

            previousMonth: '<i class="gj-icon chevron-left"></i>',
            nextMonth: '<i class="gj-icon chevron-right"></i>'
        },

which I think should be 
icons: {
            /** datepicker icon definition.
             */
            rightIcon: '<i class="gj-icon event"></i>',

            previousMonth: '<i class="gj-icon chevron-left"></i>',
            nextMonth: '<i class="gj-icon chevron-right"></i>'
        },

But changing that doesnt help either. 

Any thoughts on how to fix it?

**Comment by atatanasov** [comment]
The fonts folder is missing on the server.

https://github.com/atatanasov/gijgo/tree/master/dist/combined/fonts
