### ISSUE TITLE
When field type is datetime, formatting does not consider seconds.

### ISSUE THREAD

**Issue by jaimestuardo** [atatanasov/gijgo#429]
I data type is a date time, and this format is applied to column: dd/mm/yyyy HH:MM:ss, the data appears with "0" seconds, for example,

If field contains "2018-09-11 20:57:34", the display value in the cell is "2018-09-11 20:57:00"

**Comment by jaimestuardo** [comment]
Finally, I have found that the problem is bigger than what I have thought before.

If a datetime data is returned from server side, the format is returned as a JSON object. Date format in that case is ISO format, so parseDate method is completely wrong in gijgo.

Finally, I have changed parseDate and formatText methods to use date-fns component. That way, I can deal with ISO date format and the formatting in the grid cell.

I think you should see this.

**Comment by atatanasov** [comment]
Could you send me your changes in that method to see if I can include them in the next release.

**Comment by jaimestuardo** [comment]
Hello, unfortunately I cannot send you now, since I removed your grid from my system as I started using other more functional grid, but as I wrote in the issue, I have changed parseDate and formatText methods.
