### ISSUE TITLE
treeview: addNode

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#433]
Dear Mr, Atatansov, I´m using the configuration of your addNode [Test](https://github.com/atatanasov/gijgo/blob/master/examples/tests/temptree.html) in a actual project.

There is a bug. addNode add ever 2 new nodes with the same internal data (e.g. id, text, parentId)

Please fix this problen as soon as possible!
Thanks for all!

**Comment by stvowi** [comment]
It happen, wenn you insert a record via ajax call which will give back a new ID before you call the content of the ADD function. The sample alone without ajax is working.

**Comment by stvowi** [comment]
Please publish an example with a ajax post (insert new record) in the database!?

**Comment by stvowi** [comment]
My configuration is ...
```
var tree = $('#tree').tree({
			primaryKey: 'id',
			uiLibrary: 'bootstrap',
			selectionType: 'single',
			dragAndDrop: true,
			dataSource: 'http://myserver/app/public/category/lazy',
			iconsLibrary: 'fontawesome',
			lazyLoading: true,
			parentId: 'pid',
			dataBound: function (e) {
				// do somewhat
			}

		});
```

**Comment by atatanasov** [comment]
Everything seems to work fine. You can see my example at https://gijgo.com/Temp/64a6aed3-cd98-44d3-b18c-22d55952f5fc.html

**Comment by atatanasov** [comment]
Closing. Please reopen if you can provide better replication steps.
