### ISSUE TITLE
Colspan on added on custom tfoot rows

### ISSUE THREAD

**Issue by atatanasov** [atatanasov/gijgo#44]
Example:

```
<html>
<head>
  <meta charset="utf-8" />
  <title>Example</title>
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <link href="/Areas/Development/dist/modular/grid/css/grid.css" rel="stylesheet" type="text/css">
  <script src="/Areas/Development/dist/modular/grid/js/grid.js"></script>
</head>
<body>
 <table id="grid"></table>
 <script>
     var grid = $('#grid').grid({
         dataSource: '/Grid/GetPlayers',
         columns: [ { field: 'ID', width: 36 }, { field: 'Name' }, { field: 'PlaceOfBirth' } ],
         pager: { limit: 5 },
         dataBound: function (e, records, totalRecords) {
            var total = 0,
                summary = grid.find('tfoot tr[data-role="summary"]');
            $.each(records, function() { total += parseInt(this.ID); });
            if (summary.length === 0) {
              summary = $('<tr data-role="summary" />');
              grid.find('tfoot').prepend(summary);
            }
            summary.empty().append('<th>'+total+'</th><th></th><th></th>');
       }
     });
 </script>
</body>
</html>
```

**Comment by nasrun163** [comment]
how to colspan in field?
example :
i will colspan data in here
 { title: "", field: "Edit", width: 34, type: "icon", icon: "glyphicon-eye-open", tooltip: "Detail", events: { "click": Detail } },
                { title: "", field: "Edit", width: 34, type: "icon", icon: "glyphicon-pencil", tooltip: "Edit", events: { "click": Edit } },
                { title: "", field: "Delete", width: 34, type: "icon", icon: "glyphicon-remove", tooltip: "Delete", events: { "click": Remove }

**Comment by code35net** [comment]
> Example:
> 
> ```
> <html>
> <head>
>   <meta charset="utf-8" />
>   <title>Example</title>
>   <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
>   <link href="/Areas/Development/dist/modular/grid/css/grid.css" rel="stylesheet" type="text/css">
>   <script src="/Areas/Development/dist/modular/grid/js/grid.js"></script>
> </head>
> <body>
>  <table id="grid"></table>
>  <script>
>      var grid = $('#grid').grid({
>          dataSource: '/Grid/GetPlayers',
>          columns: [ { field: 'ID', width: 36 }, { field: 'Name' }, { field: 'PlaceOfBirth' } ],
>          pager: { limit: 5 },
>          dataBound: function (e, records, totalRecords) {
>             var total = 0,
>                 summary = grid.find('tfoot tr[data-role="summary"]');
>             $.each(records, function() { total += parseInt(this.ID); });
>             if (summary.length === 0) {
>               summary = $('<tr data-role="summary" />');
>               grid.find('tfoot').prepend(summary);
>             }
>             summary.empty().append('<th>'+total+'</th><th></th><th></th>');
>        }
>      });
>  </script>
> </body>
> </html>
> ```

not working
