### ISSUE TITLE
Grid Reload does not work properly in Ajax call

### ISSUE THREAD

**Issue by juntjtang18** [atatanasov/gijgo#442]
I have a page using gijgo grid. As simple as it is, everything works perfect. And then I add event to one column, responding to a clicking, which will trigger a function, do a ajax call to update the data. In the .done() part, it calls the grid.reload(), but nothing happend, no refresh at all. I use a window.location.reload(false) instead, it works. 

I can verify the ajax call return successfully and the data has been changed and the window.location.reload works. But not grid.reload({...}). 

Can please take a look on this issue and try to fix it? 

Attach the codes I am using: 

<pre>
<script>
var querydata;
			var setPaid = function(e) {
				var parm = {  "${_csrf.parameterName}": "${_csrf.token}"};
				var resturl = '/rest/orders/' + e.data.record.id + '/paid';
				ajaxrequest1 = $.ajax(   { url: resturl, data: parm, method: 'post'  }  )
									.fail(function(req, status, err) {
						            	alertAjaxFailure2($('#alert-panel'), 'Failure', req, status, err);				
									});
				ajaxrequest1.done(function(data) {
					bootbox.alert('Successfully charged ' + (data.order_amount / 100).toFixed(2) + '. ');
					ordersgrid.reload(querydata);	
				});
				
			};

document.ready() {
    var querydata = { year_str: 2018 };
			ordersgrid = $('#ordersgrid').grid({
		         dataSource: '/rest/orders/query/bymonth',
		         uiLibrary: 'bootstrap',
		         responsive: true,
		         primaryKey: 'id',
		         columns: [
					{ title: 'ta',   field: 'vendor_name', width: '17%', minWidth: '120', priority: 4, events: {'click': rowClick}  },
					{ title: 'd1', field: 'checkin_date'   },
					{ title: 'd2', field: 'checkout_date', minWidth: 120, priority: 7 },
					{ title: 'detail',    width: '27%', renderer: rendererDetails  },
					{ title: 'amount', field: 'order_amount', align: 'right', width: '15%'      },
					{ title: 'charged',   field: 'paid', type: 'checkbox', align: 'center', events: { 'click': togglePaid } },
					{ title: '',        field: 'Update', width: 30, type: 'icon', icon: 'glyphicon glyphicon-pencil', tooltip: 'Charge', events: { 'click': togglePaid   } },
					{ title: '',        field: 'Edit',   width: 30, type: 'icon', icon: 'glyphicon glyphicon-pencil', tooltip: 'Edit',   events: { 'click': EditDetail   } },
					{ title: '',        field: 'Delete', width: 30, type: 'icon', icon: 'glyphicon glyphicon-remove', tooltip: 'Delete', events: { 'click': DeleteDetail } }
					//{ width: '8%', align: 'center', renderer: editManager }
		          ],
		         autoLoad: false
		     	});				
		    ordersgrid.reload(querydata);

}
</script>
</pre>

**Comment by juntjtang18** [comment]
sorry for the mix of code. don't find the way to make it in <pre>

**Comment by atatanasov** [comment]
This is not a bug in the grid. The ordersgrid variable is local var for document.ready and not exists outside of this method. Declare ordersgrid outside of the document.ready function.
