### ISSUE TITLE
When trying to update a node it does append an extra checkbox ?

### ISSUE THREAD

**Issue by rajmondburgaj** [atatanasov/gijgo#444]
Hi, 

When I try this code here to update a node:

https://gijgo.com/tree/methods/updateNode

It does append an extra checkbox to this node. 
The checkbox is added next to exisiting one.

Here is my code:

            var tree = $('#tree').tree({
                uiLibrary: 'bootstrap4',
                primaryKey: 'id',
                dataSource: '/Admin/MediaTree/GetDocuments',
                lazyLoading: true,
                checkboxes: true,
                dragAndDrop: true,
                border: true,
                hasChildrenField: 'hasChildrenCount',
                select: function (e, node, id) {
                }
            });

           node.text = data.Text;
           tree.updateNode(currentNodeId, node);

Does anybody know what might be the issue ?

**Comment by atatanasov** [comment]
This is fixed only in the new development version. You can find the new stable builds at https://github.com/atatanasov/gijgo/tree/1.9/dist
