### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by shreeram09** [atatanasov/gijgo#445]
using date range picker with bootstrap 4 ,tried to change default date format "dd/mm/yy" but it isn't .
` 
$('#toDate').datepicker({
         uiLibrary: 'bootstrap4',
         iconsLibrary: 'fontawesome',
         dateFormat:"dd-mm-yy",
         maxDate:today,
        minDate: function () {
             return $('#fromDate').val();
         }
     });
`

**Comment by atatanasov** [comment]
I'm not able to replicate that issue. You can see some examples at https://gijgo.com/datepicker/configuration/format
