### ISSUE TITLE
Datepicker does not show when clicking on input text area

### ISSUE THREAD

**Issue by shadabmalik** [atatanasov/gijgo#447]
It only shows when the calendar icon is clicked. How can I show it on both.. 
This is not working 
`showOn:"both`

**Comment by atatanasov** [comment]
We don't support this yet. We are going to add this feature soon.

**Comment by thevalo** [comment]
Any update upon this?

**Comment by atatanasov** [comment]
We added showOnFocus and showRIghtIcon as config options in the new development version. You can find the development build at https://github.com/atatanasov/gijgo/tree/1.9/dist
