### ISSUE TITLE
Dialog: Resizing corner/edges don't keep their position

### ISSUE THREAD

**Issue by brindosch** [atatanasov/gijgo#45]
Greetings and thank you for this nice piece of software!
I noticed that the corner and edges divs that are used for resizing change their position to a different one than the real dialog. So they are inside the dialog or outside (easily up to 100px and more).

Is there a good way to 'attach' them better to the corners and edges?

version 1.0.0
whole gijgo package
settings:
```
		uiLibrary: 'bootstrap',
		resizable: true,
		modal: false,
		minWidth: 500,
		width: 600,
		minHeight: 300,
		height: 400,
		closeOnEscape: true,
		autoOpen: false,
		title: 'A title here...',
```

Thank you for any hint!
brindosch

**Comment by atatanasov** [comment]
This is fixed in the new development version. You can find the new build only in github at https://github.com/atatanasov/gijgo/tree/master/dist until the release of 1.2.0

**Comment by brindosch** [comment]
Thank you!
lightning fast :)
