### ISSUE TITLE
Is there a way to set checkboxes only for some nodes and not for all nodes in the tree ?

### ISSUE THREAD

**Issue by rajmondburgaj** [atatanasov/gijgo#450]
Currently I want the user to delete only a set of nodes and not all of them. I was thinking if there is a way to remove checkboxes completely for the nodes that can not be deleted.
Is there any configuration to do so ?

**Comment by atatanasov** [comment]
Yes. You can use the following config option and methods in order to achieve that:
https://gijgo.com/tree/configuration/checkedField
https://gijgo.com/tree/methods/check
https://gijgo.com/tree/methods/uncheck

**Comment by rajmondburgaj** [comment]
Maybe I am missing something but the functions check/uncheck only work on the checkbox state, they dont remove the checkbox completely. I wanted something like in the image. SO, you can see disabled nodes do not have checkboxes and the same applies for folders as well. I could manage to do this in jquery but I was thinking if there is a fancies way by the configuration. So for example you could do something like this:

        nodeDataBound: function (e, node, id, record) {
            if (record.hasModifyPermission === false) {
                node.enableCheckBox = false;
            }
        },

![capture](https://user-images.githubusercontent.com/7545874/47496865-7404e680-d858-11e8-89c3-dd2667772edd.PNG)
