### ISSUE TITLE
How can I hide some checkbox when selectiontype is multiple?

### ISSUE THREAD

**Issue by LeoLu700729** [atatanasov/gijgo#456]
Dear Sir,

when I use selectiontype is multiple, the all record will have the checkbox,
but I want to hide or disable some checkbox by the condition.
How can I set up for this case?
btw, I still need the selectall function (except hide/disable items)
Thank you

**Comment by LeoLu700729** [comment]
Dear Sir,
I need your help, thank you

**Comment by atatanasov** [comment]
We don't support that. If you want to do that you need to write a custom code about it.
You can remove the setting for selectionType: checkbox and build the checkbox column by yourself.
You can use the following method to achive that:
https://gijgo.com/grid/configuration/column.renderer
https://gijgo.com/grid/configuration/column.type
