### ISSUE TITLE
getall not workin

### ISSUE THREAD

**Issue by jordansAz** [atatanasov/gijgo#458]
When I drag a node to a new position, "getAll ()" method does not return data from the dragged node

**Comment by atatanasov** [comment]
what is the version that you are using?

**Comment by atatanasov** [comment]
Can you give me a code snippet that I can use for the replication of this issue?

**Comment by jordansAz** [comment]
hi, in the link https://jsfiddle.net/jordanAz/8daf1jcb/16/ is my code block, when reordering the continents the getall () function does not bring all the data. press button "GET ALL DATA" and see the console in chrome.

**Comment by atatanasov** [comment]
It works fine in jsfiddle. We fixed that problem a few months ago. You can see that works fine in jsfiddle. Probably you need to upgrade the gijgo version in your project
