### ISSUE TITLE
Resizable Columns in Grid Don't Work if uiLibrary Set

### ISSUE THREAD

**Issue by dlussier** [atatanasov/gijgo#46]
Run the resizable columns example from the Gijgo site:

http://gijgo.com/LiveEdit/Index/grid.ResizableColumns.resizableColumns.sample.html#

If you run it, the columns can be resized.

Now add this line of code at line 15:

uiLibrary: "bootstrap",

Run the example again. The columns can no longer be resized. This occurs with jqueryui for the uiLibrary as well.

The expected functionality is to have resizable columns regardless of the uiLibrary value.

Thanks!

D'Arcy

**Comment by atatanasov** [comment]
This is fixed in the new development version. You can find the new build only in github at https://github.com/atatanasov/gijgo/tree/master/dist until the release of 1.2.0

**Comment by atatanasov** [comment]
I added one more additional fix for that in a commit from a minute ago.
