### ISSUE TITLE
How to use Chinese date format in DateTimePicker's header?

### ISSUE THREAD

**Issue by Measureless** [atatanasov/gijgo#460]
![image](https://user-images.githubusercontent.com/30423783/48828356-751f2a00-edaa-11e8-94c5-9a10ca0ead1a.png)
I like GIJGO's widgets very much because they are simple and useful.
I translated the messages.js to Chinese and I used akiotajima's calendar title (https://github.com/atatanasov/gijgo/pull/437/commits/ae32ee0888823ac054dec5deda87873383d550a5). Now I am wondering how to use Chinese date format in DatetimePicker's header. For example, November 21 is "11月21日" in Chinese. I don't know how to add "日" after date. Thank you very much!

**Comment by atatanasov** [comment]
Yes. This is going to be available in the new version. You can find the latest development build at:
https://github.com/atatanasov/gijgo/tree/1.9/dist
