### ISSUE TITLE
Headfilter on grid

### ISSUE THREAD

**Issue by vigrebec** [atatanasov/gijgo#462]
I activated the headfilter on the grid and I found that, when I set the filter values, the datasource (in remote mode) of the grid calls the controller twice.
This behavior sometimes generate an error message, especially when you leave the page to browse another pagee (even the example on your site goes wrong).

Thanks for your help.
Best regards.

**Comment by atatanasov** [comment]
I can't replicate the issue. Could you send me a code stippet that I can use for replication.
What is the version of the gijgo grid that you use?

**Comment by atatanasov** [comment]
I will close this ticket. Could you reopen the ticket if you can provide replication steps
