### ISSUE TITLE
Hidden field not working in grid

### ISSUE THREAD

**Issue by belfour** [atatanasov/gijgo#464]
When specifying a hidden field and minWidth in other fields in a responsive grid the hidden field will appear periodically.  In this example the id column still shows.  If I remove minWidth it hides but then responsive doesn't work.

`cdnjs.cloudflare.com/ajax/libs/gijgo/1.9.10/combined/css/gijgo.min.css`
`cdnjs.cloudflare.com/ajax/libs/gijgo/1.9.10/combined/js/gijgo.min.js`

`            <div class="row">
                <div class="col-12"> 
                    <table id="grid"></table>
                </div>
            </div>   `

  grid = $('#grid').grid({
        primaryKey: 'id',
        dataSource: '/list/' + _userId,
        uiLibrary: 'bootstrap4',
        iconsLibrary: 'fontawesome',
        responsive: true,
        columns: [
            { field: 'id', hidden: true},
            { field: 'user_id', hidden: true},
            { field: 'rank', title: 'Rank', renderer: rankRenderer, minWidth: 150, priority: 3 },
            { field: 'item', title: 'Item'},
            { field: 'price', title: 'Price'},
            { field: 'location', title: 'Location'},
            { field: 'picture_url', title: 'Picture', renderer: imageRenderer, minWidth: 100, priority: 3 },
            { field: 'update_date', title: 'Last Updated', minWidth: 150, priority: 2},
            { field: 'Edit', title: '', width: 42, type: 'icon', icon: 'fa fa-pencil', tooltip: 'Edit', events: { 'click': Edit } },
            { field: 'Delete', title: '', width: 42, type: 'icon', icon: 'fa fa-remove', tooltip: 'Delete', events: { 'click': Delete } }
        ]
    });

**Comment by atatanasov** [comment]
Can you remove these columns from the definition of the column. If you want to hide them you not need to be defined. You can use the values in these columns in your code, because if you return them from the server they stay as part of the record in the front end.

**Comment by paulofonsecajr** [comment]
I need these columns to sort the grid by these hidden columns. Ex: There is a column called "code" and other two columns named "number" and "year". The column that I need to show is "code" = "number" + "year" but the sort must be "year" and "number". Did you understand the issue?
