### ISSUE TITLE
weird behaviour DatePicker

### ISSUE THREAD

**Issue by kabetcha** [atatanasov/gijgo#465]
hi
i'm using bootstrap 4 and when i click a first time the year is correct but as soon as i re-click on the calendar icon the year decrease of 1 unit?Any idea
this is my code

<div class="row">
    	<div class="col-sm">
      	<label  for="giorno">Data</label>
  	 	   <input width="276" id="datepicker" class="form-control form-control-sm" value="<?php //echo strftime("%d %b %Y");?>"type="text" placeholder="day" >
    		<script>
    		
                $('#datepicker').datepicker({
                    locale: 'it-it',
                    format: 'dd mmm yyyy',
                    value: '<?php echo strftime("%d %b %Y");?>',
                    minDate: '<?php echo strftime("%d %B %Y");?>',
                    uiLibrary: 'bootstrap4'
                });
 			</script>
  	 	</div>

**Comment by kabetcha** [comment]
![ezgif-4-6f68b9ddcb4e](https://user-images.githubusercontent.com/45342883/49159675-54645080-f325-11e8-834b-e7772086ed9c.gif)

**Comment by atatanasov** [comment]
We fixed that in the new development version. The dot in the short name of the month was a troublemaker.

You can find the latest stable builds at https://github.com/atatanasov/gijgo/tree/1.9/dist

**Comment by atatanasov** [comment]
resolved for Spannish, but still an issue for French and Turkish
