### ISSUE TITLE
detailTemplate and downloadCSV not working together

### ISSUE THREAD

**Issue by IsaaacD** [atatanasov/gijgo#467]
When detailTemplate is added and you try to use the downloadCSV method, an exception is thrown on the first column because it's not hidden and it does not have either a title or field attribute. This should be a simple fix to add these attributes or exclude this column when a detailTemplate is present.

![image](https://user-images.githubusercontent.com/5303125/49247723-f64b7200-f3e5-11e8-8f10-19d42a8d0481.png)

**Comment by IsaaacD** [comment]
I was able to skirt the issue with these changes
![image](https://user-images.githubusercontent.com/5303125/49248658-43c8de80-f3e8-11e8-9080-59714ecc9124.png)

I could potentially create a PR but i'm just currently modifying a local copy for a project I'm working on

**Comment by IsaaacD** [comment]
Found a better solution that can be implemented to declared columns too (for action buttons and the like)
![image](https://user-images.githubusercontent.com/5303125/49250684-70332980-f3ed-11e8-9f62-aebb2a336bd4.png)

**Comment by atatanasov** [comment]
This is fixed in the new development version. You can find the new stable build at https://github.com/atatanasov/gijgo/tree/1.9/dist
