### ISSUE TITLE
Request: Dialog touch support

### ISSUE THREAD

**Issue by brindosch** [atatanasov/gijgo#48]
Greetings again,
I wonder if it's possible to add touch support to draggable (+resizing). I played around with the event listener but i had no luck.
ref: https://developer.mozilla.org/en-US/docs/Web/Events/touchstart

Would be nice!

Best wishes
brindosch

**Comment by atatanasov** [comment]
Hello,

We added this task to our backlog and we are going to add this feature as soon as we can.

Thanks for the feedback!

Best Regards,
Atanas

**Comment by atatanasov** [comment]
We added touch support in our new development version. You can find the build at https://github.com/atatanasov/gijgo/tree/master/dist

**Comment by brindosch** [comment]
Thank you, will test soon!

**Comment by atatanasov** [comment]
You can test it at https://rawgit.com/atatanasov/gijgo/master/examples/dialog/Dialog.Base.draggable.True.html

**Comment by brindosch** [comment]
There is an uncaught error, when dragging with a mouse. This is also noticable at your example at the browser console.
Thank you!

**Comment by atatanasov** [comment]
We fixed the error in this case. Thanks for finding this.
