### ISSUE TITLE
Date picker... Dont' get my date back with post method!

### ISSUE THREAD

**Issue by scombre** [atatanasov/gijgo#480]
Hello Everyone,

I have a smal issue, I have 2 datepicker in a form, i try to get back the information, see bellow code, all the other fields arrive correctly but nit the date picker info, any idea? The datepicker work perfectly! Just the post method return me nothing (please note that i make the post method on a other domain, can be the issue?).
Please note that if I disable the datepicker, and write in the field, i become the date....

Best 
Stéphane
`    	var today, datepicker1, datepicker2 ;
    	today = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());
    	datepicker1 = $('#arrival_date1').datepicker({
        	minDate: today,
			format: 'dd/mm/yyyy',
        	keyboardNavigation: true,        
			uiLibrary: 'bootstrap',
         	iconsLibrary: 'fontawesome',
			maxDate: function () {
                return $('#departure_date1').val();
            }
    	});
		
		datepicker2 = $('#departure_date1').datepicker({
			format: 'dd/mm/yyyy',
        	keyboardNavigation: true,        
			uiLibrary: 'bootstrap',
         	iconsLibrary: 'fontawesome',
            minDate: function () {
                return $('#arrival_date1').val();
            }
    	});

echo "xxxx".$_POST['arrival_date1'];  // Always empty!`

**Comment by scombre** [comment]
nobody????
As well the basic sample for this datepicker don't works!

**Comment by atatanasov** [comment]
You can't post to the other domains. Probably this is your issue. The gijgo datepicker is using simple input from type text and the posting should not be related with our widget.
