### ISSUE TITLE
locale:'tr-tr'  not working

### ISSUE THREAD

**Issue by MustafaYavuzz** [atatanasov/gijgo#482]
Today is Saturday 05.01.2019 (dd/mm/yyyy)  but i worked locale:'tr-tr' output is SUNDAY why??

i write locale:'en' no problem. it is working but turkish isn't work

screenshot: http://i68.tinypic.com/23hvnzo.jpg

**Comment by atatanasov** [comment]
This is fixed in our latest stable build that is not released yet. You can find the build at https://github.com/atatanasov/gijgo/tree/1.9/dist
We are going to release that soon.

You can also use https://gijgo.com/datepicker/configuration/weekStartDay to setup a start day.
