### ISSUE TITLE
Angular 7.1.0

### ISSUE THREAD

**Issue by loredanKon** [atatanasov/gijgo#492]
Has anyone tried this last version on Angular 7.1.0?

I have installed `gijgo-angular-wrappers` and `gijgo` packages.
Then I imported `TreeComponent` from `gijgo-angular-wrappers/tree.component` and added to `declarations` array in `@NgModule`.

This is the error I get:

`ERROR in ./node_modules/gijgo-angular-wrappers/tree.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: blabla\node_modules\gijgo-angular-wrappers\tree.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Packa
ge Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (blabla\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (blabla\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
i ｢wdm｣: Failed to compile.`

`ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/gijgo-angular-wrappers/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.`

**Comment by sanleong** [comment]
I have the same issue, but for Angular 7.2.3. Are we missing something here?

**Comment by atatanasov** [comment]
I upgraded https://github.com/atatanasov/gijgo-angular-wrappers to Angular 7 and everything looks good. Could you get my latest examples from there to see if everything works fine.

**Comment by bala41288** [comment]
I'm trying to install and use and I also have the same problems in the latest angular 7.3.4 version. Can you please help?

**Comment by atatanasov** [comment]
Please use the following example in order to run it: https://github.com/atatanasov/gijgo-angular-wrappers

**Comment by bluebaroncanada** [comment]
Same issue.  I've created a minimal example. 
 Feel free to clone it. 
 Here's the changes from a blank angular project to this error https://git.bluebaron.ca/james/dptest/commit/615fa79ed7886fccccb02a1a02f97e80da3cd311

**Comment by bluebaroncanada** [comment]
I think the problem could be solved by adding a Module, maybe?
