### ISSUE TITLE
Grid paging problem

### ISSUE THREAD

**Issue by ashiqullah** [atatanasov/gijgo#493]
locally everything is fine but when I deploy the application to the public domain when I click paging numbers it works but sometimes it takes extra time and after that, it shows 0 records and grid is null.
here is my code.

    var gridurl = "@Url.Action("GetTVETBenifaciary", "TEVT")";
            grid = $('#grid').grid({
                dataSource: gridurl + partialurl,
                uiLibrary: 'bootstrap4',
                primaryKey: 'ID',
                columns: [
                    { field: 'ID', hidden: true },
                    { field: 'ProjectCode', title: 'Training Code' },
                    { field: 'Province', title: 'Province' },
                    { field: 'FullName', title:'Full Name' },
                    { field: 'FatherName', title:'Father Name' },
                    { field: 'NationalID', title:'National ID' },
                    { field: 'ContactNo', title:'Contact#' },
                    { field: 'Age',width:70 },
                    { field: 'Gender', width: 70 },
                    { field: 'WorkStatus', title: 'Record Status', width: 100 },
                    { field: 'Edit', tmpl: '<button id="{ID}" title="Edit/Details" class="gj-button-md editbutton " ><i class="gj-icon pencil"></i></button>', width: 70, align: 'center' },

                ],
                pager: { limit: 5 }
            });

**Comment by atatanasov** [comment]
I guess that this is not an issue with the control. The paging should be done on the server side and something is wrong in there. You can see our examples at https://github.com/atatanasov/gijgo-asp-net-examples in order to see how the paging needs to be implemented.
