### ISSUE TITLE
On press enter in datepicker

### ISSUE THREAD

**Issue by EduardCerv** [atatanasov/gijgo#496]
When I press enter on datepicker the input display NaN/NaN/NaN I am using the version 1.9.11 
![image](https://user-images.githubusercontent.com/13474826/52382688-debee400-2a3b-11e9-8636-e5333088e1e8.png)

**Comment by atatanasov** [comment]
I can't replicate this on https://gijgo.com/datepicker/example/daterangepicker
Can you replicate this in https://gijgo.com/datepicker/example/daterangepicker?
Could you tell me what is the difference between your code and my example? Are you using localization in other language?

**Comment by atatanasov** [comment]
I will close this issue. Please reopen if you can provide more info
