### ISSUE TITLE
grid.reload() not working in IE 11 ( when using ajax)

### ISSUE THREAD

**Issue by aniltc-rails** [atatanasov/gijgo#499]
HI all

In my code, grid.reoload() not working in IE 11. I can even show in existing demo also.

please share your thoughts about this.

Thanks & Regards
Anil

**Comment by atatanasov** [comment]
You have a typo in the reload method. Should be reload() instead of reoload(). Everything works fine on IE11 in the demo page at https://gijgo.com/grid/Methods/reload

**Comment by aniltc-rails** [comment]
it is not working In IE 11, I used in ajax success function.Please see this demo https://gijgo.com/grid/demos/ajax-sourced-data. 

grid.reload() not working. I have tested above url and it's not working in IE 11 but its working in chrome latest version

**Comment by atatanasov** [comment]
Try on different computer. This demo works fine on my IE11. The javascript or something else could be disabled on your IE11
