### ISSUE TITLE
Header filter still visible when column set to hidden

### ISSUE THREAD

**Issue by tobybowers** [atatanasov/gijgo#50]
Hi,

When using headerFilter: true and setting a column to hidden 
columns: [ { field: 'id', hidden: true} ]

The column data and column header are both hidden but the column filter is still visible and taking up space in the table.
![2017-01-23 13_50_44-estate agent](https://cloud.githubusercontent.com/assets/9391549/22199127/09802140-e173-11e6-99c4-d6b36f9e3de8.png)

Any solution for this?

Thanks,
Toby

**Comment by tobybowers** [comment]
After checking the code i think i've found the reason.

In gj.grid.plugins.headerFilter:
There is no check to see if the column is hidden or not.

Updating the code to the following corrects this:
`$th.append($ctrl);
if (data.columns[i].hidden == true) {
$th.hide();
}
$filterTr.append($th);`


I've not tested this yet but i also think the hideColumn method will need to be updated as it is targeting the following to hide columns in the thead
`thead>tr>th:eq(' + position + ')`


Header Filters use td not th 

`thead>tr>td:eq(' + position + ')`

As such, adding the following line will hide the header filter when hiding a column after init 

`$grid.find('thead>tr>td:eq(' + position + ')').hide();`

Regards,
Toby

**Comment by atatanasov** [comment]
We fixed that issue in the new development version located in the master branch. You can find the new build in the dist folder.
