### ISSUE TITLE
dateTime picker

### ISSUE THREAD

**Issue by leedoma** [atatanasov/gijgo#500]
How do you disable the future dates starting from "tomorrow" on forward?

**Comment by atatanasov** [comment]
You can see an example about that at https://gijgo.com/datepicker/configuration/maxDate

**Comment by leedoma** [comment]
I revised the original css to match my requirements and maxDate messed up
my css. I did this instead and everything looks great. Thank you for your
reply and your help.I really appreciate it a lot....

<script>
var today, datepicker;
today = new Date(new Date().getFullYear(), new Date().getMonth(), new
Date().getDate());
datepicker = $('#datepicker').datepicker({ uiLibrary: 'bootstrap', modal:
true, header: true, footer: true, maxDate: today });
</script>
