### ISSUE TITLE
FIX YOUR SHITTY CONTACT PAGE

### ISSUE THREAD

**Issue by LJ9999** [atatanasov/gijgo#501]
It doesn't work and now I've wasted an entire evening trying to get your shitty control to work in the real world.

**Comment by atatanasov** [comment]
Don't use it in your shitty project if you don't like the controls :)

**Comment by webcliq** [comment]
I may get frustrated with a Developer, who's controls I use, but I would **never** use language of the sort above. Invariably it is my fault through lack of knowledge or problems of interaction with other Controls that I use. This has definitely been the case with Gijgo but Atatanasov has dealt with conflicts as quickly as possible.

In the future if you feel like you did at half past midnight, go and kick a can in the road (or the cat or a cushion) but please, don't insult the Developer who gives his time for little or no reward.
