### ISSUE TITLE
Persistent expanded row - feature request (maybe)?

### ISSUE THREAD

**Issue by aamirMasood** [atatanasov/gijgo#51]
If a row is expanded and grid is refreshed, the expanded row gets collapsed and has to be expanded again. Usual scenarios are fine but if grid is refreshed using `setInterval` it is a problem (at least for me). I understand that it is complicated but is it possible to make it persistent maybe with a configuration option.

**Comment by atatanasov** [comment]
We are going to include that in the next version. Stay tuned!!! :)

**Comment by atatanasov** [comment]
We implemented this feature in the latest development version. You can find the new build at https://github.com/atatanasov/gijgo/tree/master/dist/combined
