### ISSUE TITLE
Was working, now DatePicker button goes out to lunch

### ISSUE THREAD

**Issue by jrichview** [atatanasov/gijgo#515]
This is a simple form intended to demo a layout. It doesn't do anything. When I first added the datepicker to the form it worked like a charm. Now when you click the calendar button it goes out to lunch.

I've 99% certain I've only done cosmetic changes since then, so I am currently pretty puzzled what broke it, unless something got updated in the CDN?  I've tried disabling some other JS logic on the page but it exhibits the problem regardless.

DEMO: https://apalacheectrpoc20190312090704.azurewebsites.net/

**Comment by atatanasov** [comment]
This is not a problem with our library. I guess that you have infinite loop in your code that prevent our datepicker to work. Please check what's new in you latest version to find the issue.

**Comment by jrichview** [comment]
You obviously never even looked at [the page](https://localhost:44317/Home/CreateIncident). Below is the entire code on my page. The only purpose to this page is to demo layout of a proposed form. It has NO functionality, but we want to demonstrate that the date and time fields have date and time pickers.  

```
$(document).ready(function () {
    $('input.datepick').datepicker({
        uiLibrary: 'bootstrap4',
        iconslibrary: 'materialicons'
    });
    $('input.datepick-sm').datepicker({
        uiLibrary: 'bootstrap4',
        iconslibrary: 'materialicons',
        size: 'small'
    });
    $('input.timepick').timepicker({
        uiLibrary: 'bootstrap4',
        iconslibrary: 'materialicons'
    });
    $('input.timepick-sm').timepicker({
        uiLibrary: 'bootstrap4',
        iconslibrary: 'materialicons',
        size: 'small'
    });
});


```

**Comment by jrichview** [comment]
I've even tested with ONLY this code in the document.ready function:

`$('input.datepick-sm').datepicker({
        uiLibrary: 'bootstrap4',
        iconslibrary: 'materialicons'
    });`

**Comment by jrichview** [comment]
I uninstalled gijgo and installed Tempus Dominus date control.  Their control works and I no longer see the problem on my page. 100% certain the problem is in your library.
