### ISSUE TITLE
Support for Custom Icons

### ISSUE THREAD

**Issue by aamirMasood** [atatanasov/gijgo#52]
Hi there,
Since the grid uses glyphicon icons by default for bootstrap, using any other icon library like font awesome is a little bit complicated. Is it possible to use a configuration option to specify different icons used in the grid.

**Comment by atatanasov** [comment]
Yes. You can use pager.leftControls and pager.rightControls in order to do that. You can see an example at http://gijgo.com/Grid/Configuration/pager.leftControls
