### ISSUE TITLE
How to set Calendar Icon to left

### ISSUE THREAD

**Issue by NitinPrakash** [atatanasov/gijgo#522]
I could not find method to set the calendar icon to the right of the element.

**Comment by Nenrikido** [comment]
Which icon ? and to the right or the left ?

**Comment by NitinPrakash** [comment]
Thanks for reply.
I was looking if the Calendar icon can be placed to the left of the Input element, currently I was not able to find any references

![screenshot-gijgo com-2019 03 25-14-10-13](https://user-images.githubusercontent.com/1855981/54905779-d21d1f00-4f07-11e9-908a-c1d6f65bdf8c.png)

**Comment by Nenrikido** [comment]
Ok so, as you can see in the generated code, here's the css for this icon : 
```css
.gj-datepicker-md [role=right-icon] {
    position: absolute;
    right: 0;
    top: 0;
    font-size: 24px;
}```

So you can overwrite it with a `left: 0;` and it'll work as you want, as it doesn't seem to have an option in gijgo datepicker to do it

**Comment by NitinPrakash** [comment]
Thanks for reply
I hope you consider making it a setting, as in some cases it may be needed

**Comment by Nenrikido** [comment]
Actually i am not a gijgo developper, just someone using it, so i hope this will be seen by actual gijgo developpers. Or if you want you can make a PR

**Comment by atatanasov** [comment]
You can use showRightIcon (https://gijgo.com/datepicker/configuration/showRightIcon) to hide the icon and add it by yourself on the left side.

**Comment by stephiescastle** [comment]
When I add my own, it doesn't behave like the Right Icon that's added via the plugin. It's not contained in the wrapper (so my own prepend/appends are on separate lines) and I can't get my own button to trigger opening the datepicker. 

How can i add my own and still have it be integrated with what the plugin is doing?
