### ISSUE TITLE
Internationalization Support or Custom Messages

### ISSUE THREAD

**Issue by aamirMasood** [atatanasov/gijgo#53]
Hi there,
Some messages can be customized using configuration options but there are still some labels or messages displayed in English. 
Any plan to include support for multiple languages?

**Comment by atatanasov** [comment]
Yes. This is in our backlog. I will keep this ticket open until we implement internationalization. This is going to come soon. Stay tuned!

**Comment by stvowi** [comment]
It would great to have this feature as soon as possible. Your work is great.

**Comment by atatanasov** [comment]
This is already added to the new version (1.2.0). You can see a demo about it at http://gijgo.com/grid/demos/jquery-grid-localization
