### ISSUE TITLE
Custom ajax error handler?

### ISSUE THREAD

**Issue by aamirMasood** [atatanasov/gijgo#54]
Hi there,
I am using a global ajax error handler `$.ajaxSetup({ global: true, error: globalAjaxErrorHandler });` which among other things displays a message.
The grid overrides the error handler and creates its own error handler, which has an `alert` inside. 
It would be convenient if there are options to provide the additional callbacks (maybe with override option) for success and error conditions during the process of data loading.

**Comment by atatanasov** [comment]
Hello,

This is an example:
```
 <table id="grid"></table>
 <script>
     var grid, onErrorFunc = function (response) {
         alert('Server error.');
     };
     grid = $('#grid').grid({
         dataSource: { url: '/DataSources/InvalidUrl', error: onErrorFunc },
         columns: [ { field: 'Name' }, { field: 'PlaceOfBirth' } ]
     });
 </script>
```

You can find more examples at http://gijgo.com/Grid/Configuration/dataSource
