### ISSUE TITLE
Dialog + Ajax

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#55]
Would you please implement the possibility to load html forms via ajax calls in the modal body of an dialog? (I think to an dataSource option such like by Tree or Grid)

It would be also nice to have a easy way (shortcut methods) to build alert & confim dialogs such like by 
[Bootstrap3 Dialogs](https://nakupanda.github.io/bootstrap3-dialog/).

**Comment by atatanasov** [comment]
Thanks for the proposal. We added your proposal in our backlog. This is going to be added in future versions.

**Comment by stvowi** [comment]
Please let you also inspire from [EDialog](http://saribe.github.io/eModal/#demo).
That are basic things who me ever need.

**Comment by atatanasov** [comment]
Thanks for the feedback
