### ISSUE TITLE
In case you are useful

### ISSUE THREAD

**Issue by spammoogle** [atatanasov/gijgo#56]
For a job of its own I had to make a new method that would return all the ids of a particular property of the model that is passed to the tree. Returned ids will meet the criteria of a delegated role.

I send you this code in case you want to add it to your pluggin.

Sorry for my english and thank you very much for your work.

*******************************************************************************************
getIdsByOwnPropertyData: function ($tree, property, delegateFunction, records, returnCollection) {
        for (var i in records) {
            if (records[i].hasOwnProperty("children") && records[i].children.length > 0) {
                gj.tree.methods.getIdsByOwnPropertyData($tree, property, delegateFunction, records[i].children, returnCollection);
            }
            var node = records[i];
            if (node != undefined && node.hasOwnProperty("data") && delegateFunction(node.data[property])) {
                returnCollection.push(node.id);
            }
        }
        return returnCollection;
    },

 /**
     * Return ids by own property.
     * @method
     * @param {string} property - The property name of your own modelData
     * @param {delegateFunction(valueParam)} reference to delegate function - delegate function that receives the property value and it must return a boolean.
     * @return array[ids]
     * @example sample 
     * <button id="btnGetData">Get Data</button>
     * <br/><br/>
     * <div id="tree"></div>
     * <script>
     *     var tree = $('#tree').tree({
     *         dataSource: '/DataSources/GetCountries',
     *     });
     *     $('#btnGetData').on('click', function () {
     *         var ids = tree.getIdsByOwnPropertyData("population", delegateFunction)
     *         alert('The ids whose population > 1000 ' + ids);
     *     });
     *  function delegateFunction(valueParam){
            return ( valueParam > 1000 )
     *  }
     * </script>
     */

    self.getIdsByOwnPropertyData = function (property,delegateFunction) {
        return methods.getIdsByOwnPropertyData(this, property, delegateFunction, this.data('records'), new Array())
    };

**Comment by atatanasov** [comment]
Thanks for the proposal. I will think about adding this in new versions.
