### ISSUE TITLE
Next page icon causing postback on page

### ISSUE THREAD

**Issue by paulofonsecajr** [atatanasov/gijgo#573]
On my (aspx - asp.net webforms) page "next page icon" change correctly to next page (code behind is ok and event is firing ok) but after it causes postback on page and the grid object disapears. How can I stop the postback? Any help?

My Grid:
            var grid = $('#grid').grid({
                columns: [
                    { field: 'LGA_Id', sortable: true, title: 'Id' },
                    { field: 'LGA_AppVersion', sortable: true, title: 'Versão' }
                ],
                dataSource: {
                    data: { page: 1, limit: 3, sortBy: 'LGA_Id', direction: 'desc' },
                    url: '/webservices/Services.asmx/RecuperaLog'
                },
                pager: { limit: 3, sizes: [3, 10, 50, 100, 1000] },
                primaryKey: 'LGA_Id',
                uiLibrary: 'bootstrap4'
            });

Code behind:
        [WebMethod]
        [ScriptMethod(ResponseFormat = ResponseFormat.Json)]
        public void ResponseJson(int page, int limit, string sortBy, string direction)
        {
            JavaScriptSerializer js = new JavaScriptSerializer();
            Context.Response.Clear();
            Context.Response.ContentType = "application/json";

            ClassesSFI.AccessLog AccessLog = new ClassesSFI.AccessLog();
            var query = AccessLog.ToList();
            var total = query.Count;
            int start = ((int)page - 1) * (int)limit;
            query = AccessLog.ToList().Skip(start).Take((int)limit).ToList();
            var records = query.ToList();

            JavaScriptSerializer js = new JavaScriptSerializer();
            Context.Response.Clear();
            Context.Response.ContentType = "application/json";
            Context.Response.Write(js.Serialize(new { records, total }));
        }

Thanks in advanced!

**Comment by singsa** [comment]
Is the postback happening when you click on the pager buttons in the grid?

**Comment by paulofonsecajr** [comment]
Putting the grid outside form resolve it. Thanks very much!
