### ISSUE TITLE
Grid -  GroupView

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#59]
Could we have in one of the next versions an  GroupView?

Vou can see [here ](http://www.jeasyui.com/extension/datagridview.php) what I mean.

**Comment by atatanasov** [comment]
Yes. This already in our backlog. We are going to add that in future versions.
I will leave this ticket open, until we add this feature.

**Comment by atatanasov** [comment]
We released a new version where this feature is available. You can see a demo at http://gijgo.com/grid/demos/grouping
