### ISSUE TITLE
Sorting is not working

### ISSUE THREAD

**Issue by mbutler71** [atatanasov/gijgo#6]
grid = $("#viewGrid1").grid({
        //selectionType: "multiple",
        //selectionMethod: "checkbox",
        autoLoad: false, //absolutely necessary!
        loadonce:true,
        uiLibrary: "bootstrap",
        dataSource: { url: '/RepairOrderViews/GetRepairOrderByStatus', data: { statusCode: 'E' } },
        defaultColumnSettings: { headerCssClass: "bootstrapgridoverride center", sortable: true},
        //Non-Worked Repair Orders
        columns: [
                { field: "RepairOrderNumber", name: "RO", title: "RO", align: "right", },
                { field: "RepairOrderStatusDesc", title: "Status", type: "string"},

**Comment by atatanasov** [comment]
I'm not able to replicate this issue with your code sample. Can you see requests to the backend with correct sortBy and direction parameters, when you click on a column header?
What is the version of the grid that you are using?

**Comment by mbutler71** [comment]
What are the parameters I am supposed to be using, I didn't see any in the help pages?
Thanks for your help.Matt

**Comment by mbutler71** [comment]
I see in the Google debugger the parameters to send for sorting and paging... page-limit-sortBy-direction. 

Thanks.

**Comment by atatanasov** [comment]
Matt,

You can change the parameter name with the following configuration options if needed:
http://gijgo.com/Grid/Configuration/defaultParams.sortBy
http://gijgo.com/Grid/Configuration/defaultParams.direction
http://gijgo.com/Grid/Configuration/defaultParams.limit
http://gijgo.com/Grid/Configuration/defaultParams.page

**Comment by mbutler71** [comment]
Great. Thanks for your help.
