### ISSUE TITLE
browserify

### ISSUE THREAD

**Issue by paulgabronis** [atatanasov/gijgo#60]
how to properly use this library with browserify?

**Comment by atatanasov** [comment]
We answer only questions that are related to this library. We don't want to spend time to answer questions related to integrations with extenal libraries/frameworks.

**Comment by Inkata** [comment]
$ npm install --save gijgo
 then in your main file:

`require('gijgo/grid.min.js')`

then in your index.html 

`$('table').grid()`

that's it.

**Comment by onurkose** [comment]
@ghost,
Well, if you have the bundle named gijgo and have those folders named "combined" and "modular", I think you should first include the gijgo core and then use the _so called_ modular package as:

`require('gijgo/modular/js/core.min.js');
require('gijgo/modular/js/tree.min.js');`

or try to load all bunch of useless scripts combined:

`require('gijgo/combined/js/gijgo.min.js');`

I think there should be better documentation for this project.
