### ISSUE TITLE
Gijgo still active/supported?

### ISSUE THREAD

**Issue by oyvindvol** [atatanasov/gijgo#603]
Hi,

First of all, thanks for the great product you have made - I have been using gijgo grid now for several projects, and it is working perfectly!

My concern is, is it being supported still? I can see that there is a lot of unsolved issues on Github, but I can also see that the latest version is from february 2019. So it seems that the project is still active?

For example, if there is any issues in future browser versions, can I still expect such issues to be resolved?

**Comment by atatanasov** [comment]
Yes. I still support gijgo. I work on a new version that is planned for early 2020.
