### ISSUE TITLE
How to use deeply nested dataSource?

### ISSUE THREAD

**Issue by Inkata** [atatanasov/gijgo#61]
I'm working with geoJSON data (http://geojson.org/) Which is a JSON notation for geographic features.
I want to show a three-column table with the name, longitude and latitude of thousands of points.

The data is like this:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "marker-color": "#7e7e7e",
        "marker-size": "medium",
        "marker-symbol": "",
        "name": "point_two"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          85.4296875,
          60.930432202923335
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "marker-color": "#7e7e7e",
        "marker-size": "medium",
        "marker-symbol": "",
        "name": "point_one"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          117.0703125,
          61.60639637138628
        ]
      }
    }
  ]
}
```

How should I define the proper dataSource options, so that I can use the features[].properties.name field for column 1, features[].geometry.coordinates[0] for column 2 and features[].geometry.coordinates[1] for column 3 ?

I tried reading trough the docs, but all the examples use a flat data source; is using deeply nested dataSources supported?

Thanks!

**Comment by atatanasov** [comment]
We don't support such dataSources by default, but you can use column.renderer for each column to extract and display the needed info. You can read the documentation about this option at http://gijgo.com/Grid/Configuration/column.renderer.

Here is an example:
```
$('#grid').grid({
         dataSource: features
         columns: [
             { title: 'name', renderer: function (value, record) { return record.properties.name; } },
             { title: 'longitude ', renderer: function (value, record) { return record.geometry.coordinates[0]; } },
             { title: 'latitude ', renderer: function (value, record) { return record.geometry.coordinates[1]; }  }
         ]
     });
```
