### ISSUE TITLE
JQuery dependency

### ISSUE THREAD

**Issue by fanthomas** [atatanasov/gijgo#617]
Hello,

This is not an error, but I couldn’t find how to contact you (the contact feature on your website doesn't work).

It is possible to remove the jQuery dependency ?
1. Will it be difficult, time costing ?
2. How much money would it costs ? (I was thinking of becomming a patreon btw, or give you directly)

Thank you so much for the work, it is so useful for me and my project ! Very much appreciated !

**Comment by atatanasov** [comment]
Hello,

Yes. We can do that. Could you contact me at atanas.nk.atanasov@gmail.com. We are going to fix the contact form soon.

Regards,
Atanas
