### ISSUE TITLE
file to translate into Portuguese (pt-br)

### ISSUE THREAD

**Issue by luizAzevedo** [atatanasov/gijgo#62]
good evening,
I created the file to translate into Portuguese (pt-br).
See below:

if (typeof (gj.grid) === 'undefined') {
    gj.grid = {
        plugins: {},
        messages: []
    };
}

gj.grid.messages['pt-br'] = {
    First: 'Primeiro',
    Previous: 'Anterior',
    Next: 'Próximo',
    Last: 'Último',
    Page: 'Página',
    FirstPageTooltip: 'Primeira página',
    PreviousPageTooltip: 'Página anterior',
    NextPageTooltip: 'Próxima página',
    LastPageTooltip: 'Última Página',
    Refresh: 'Atualizar',
    Of: 'de',
    DisplayingRecords: 'Mostrando registros',
    Edit: 'Editar',
    Delete: 'Excluir',
    Update: 'Alterar',
    Cancel: 'Cancelar',
    NoRecordsFound: 'Nenhum registro encontrado.'
};

**Comment by atatanasov** [comment]
Thank you! We added you translation to our new development version.
