### ISSUE TITLE
Paging is not working properly (sending 11,111,1111 after reload) after reloading the grid with search parameters. 

### ISSUE THREAD

**Issue by koustubh** [atatanasov/gijgo#64]
I am using a Gijgo Grid v1.0.0, paging is working fine at first time but when I reload grid with search parameter paging is not working properly. a grid is sending 11,111,11111 etc. when I click on next page from a pager.

Please suggest me any solution for the same.
I am using following client-side code,
 grid.reload({  searchString: $("#search").val(), page: "1" });
and my server side json response is like,
 return Json(new { records, total }, JsonRequestBehavior.AllowGet);

**Comment by atatanasov** [comment]
Please pass the page as number instead of string in order to resolve this issue. In other words replace page: "1" with page: 1. We are going to fix this issue in the new version. Thanks for the feedback.
