### ISSUE TITLE
Bootstrap 4 Support

### ISSUE THREAD

**Issue by fuhquan** [atatanasov/gijgo#66]
This plugin could be really helpful in a Web App I'm currently developing, but we are going to use BS4. 

Are there any plans for BS4 support for the TreeView or any Info on how to make the current version work with current version?

**Comment by atatanasov** [comment]
I guess that the latest stable version works with BS4 without any issues. We are planning to release a new version later this week, which officially support BS4 for the treeview, grid and dialog.

**Comment by fuhquan** [comment]
Thanks for your quick reply. I'm trying to get it running with BS4 right now but as of now it won't work.
Before I invest too much time and energy on fixing this, I'll wait for your updated version.

Thank you for your work!

**Comment by atatanasov** [comment]
The new version with bootstrap 4 support is released. You can find an example at http://gijgo.com/tree/demos/bootstrap-4-treeview
