### ISSUE TITLE
Grid - build in editors

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#67]
I've seen some examples how we have to write editors.

How about it to implement/ offer a set of simple build in editors for fields with select, textarea, checkbox tags (controls) as cell editors where the tag attributes can be configured via grid parameters?

... for inspiration see also cell editors: http://www.editablegrid.net/en/

**Comment by atatanasov** [comment]
This is done in the new version. You can see the demo at http://gijgo.com/grid/demos/bootstrap-grid-inline-edit
