### ISSUE TITLE
locale setting for the datepicker does not seem to be working properly

### ISSUE THREAD

**Issue by Solarbytes** [atatanasov/gijgo#673]
The JavaScript:

         // formatted with YYYY-MM-DD format
         $('#datepicker3').datepicker(
         {
            locale: 'de-de',
            format: 'yyyy-mm-dd',
            showOtherMonths: true,
            selectOtherMonths: true
         });

(And it doesn't matter, I can leave out the format, and other settings and just use "locale" as shown, copied from the configuration documentation page, and the same thing happens.)

When I reload the page, and click the button or put focus on the control defined as:

            <input name="datepicker3" id="datepicker3" width="276" value="2021-01-15" />

(And again, it doesn't matter if there is a value there or not) I cannot get the control to open. In Firefox, if I click the control, nothing happens. So going to the menus and selecting "Web Developer", and then "Web Console", I see this:

Uncaught TypeError: gj.core.messages[(intermediate value)] is undefined
    formatDate file:///F:/Apache/htdocs/WebTutorial/js/gijgo.js:445
    updateHeader file:///F:/Apache/htdocs/WebTutorial/js/gijgo.js:14666
    selectDay file:///F:/Apache/htdocs/WebTutorial/js/gijgo.js:15096
    dayClickHandler file:///F:/Apache/htdocs/WebTutorial/js/gijgo.js:15067
    value file:///F:/Apache/htdocs/WebTutorial/js/gijgo.js:15264
    value file:///F:/Apache/htdocs/WebTutorial/js/gijgo.js:15402
    open file:///F:/Apache/htdocs/WebTutorial/js/gijgo.js:15128
    initialize file:///F:/Apache/htdocs/WebTutorial/js/gijgo.js:14558
    jQuery 2
gijgo.js:445:21

​If I remove the "locale:" option, everything else works exactly as it should, reloading the page I can open the calendar and all is good.

**Comment by Solarbytes** [comment]
Turns out there are specific language files that need to be loaded if using the localization. But the information about this is not where expected, and there's no reference to it in the main documentation.

**Comment by B5656** [comment]
For those who are stuck on this problem, here is a solution :
download your file langage https://github.com/atatanasov/gijgo/tree/master/dist/combined/js/messages
and then just add <script src="yourPath/fileName.js"></script> at the end of your header
