### ISSUE TITLE
inlineEditing.managementColumn

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#68]
I have a problem with the width of the column with the command buttons if I use uiLibrary: 'bootstrap' and the german translations. The buttons are displayed one above the other.
There should be the possibility to manually set the width of the button column.

It would be also nice / interesting to display the text of the command button as title/ tooltip - to show only the icons of the buttons.

see [Bootstrap sample](http://gijgo.com/grid/Configuration/inlineEditing.managementColumn)

**Comment by atatanasov** [comment]
Please use the following example in order to do that: http://gijgo.com/LiveEdit/Index/grid.InlineEditing.inlineEditing.managementColumn.False.html

**Comment by stvowi** [comment]
Thanks - it was helpful!
