### ISSUE TITLE
Incompatibility with Bootstrap version 5 

### ISSUE THREAD

**Issue by mortezafs** [atatanasov/gijgo#681]
Gijgo Datepicker, Datetime picker, and time picker need some review to compatibile with bootstrap v5.
There is some style bug when using gijgo  in this version of bootstrap.
Some classes like "input-group-append" was changed in this version of bootstrap and can not be used anymore.

Regards.

**Comment by atatanasov** [comment]
Bootstrap 5 is not supported yet. We are going to announce once this gets supported.

**Comment by atatanasov** [comment]
We just release a new version where we support Bootstrap 5. You can see an example at https://gijgo.com/datepicker/example/bootstrap-5
