### ISSUE TITLE
Grid Expanded by Default when using 'grouping' in Gijgo Grid options

### ISSUE THREAD

**Issue by vibs2006** [atatanasov/gijgo#69]
I'm unable to find any option to **collapse all** the groupings by default. 

Please see the attached snapshot 
![defaultexpandtrue](https://cloud.githubusercontent.com/assets/18658498/24862421/21687864-1e1a-11e7-9105-654a2b3fce4e.png)

Is there any option which can collapse all groupings by Default?

**Comment by atatanasov** [comment]
no. not yet. Do you need something like .collapseGroups() and .expandGroups() methods?

**Comment by NabeelMahmood2** [comment]
How to set Collapse All by default?

**Comment by atatanasov** [comment]
You can call the .collapseAll() method inside the dataBound event in order to do that. This is going to do it.

**Comment by NabeelMahmood2** [comment]
Thank you man !

**Comment by NabeelMahmood2** [comment]
This is what i have done:

var grid, dialog;
    $(document).ready(function () {

        grid = $('#grid').grid({
            primaryKey: 'ItemNo',
            dataSource: '/OrderedChemicalss/GetOrderedChemicals',
            selectionType: 'multiple',
            resizableColumns: true,
            selectionMethod: 'checkbox',
            grouping: { groupBy: 'OrderNo' },
            columns: [
                { title: 'SNo', field: 'SNo', hidden: true },
                { title: 'Order No', hidden: true,field: 'OrderNo', sortable: false },
                { title: 'Order Date', field: 'OrderDate', sortable: true, type: 'date', format: 'dd/mm/yyyy' },
                { title: 'Staff Name', field: 'StaffName', sortable: true },
                { title: 'RefDocNo', field: 'RefDocNo', sortable: true },
                { title: 'Supplier Name', field: 'SupplierName', sortable: true },
                { title: 'Chemical Code', field: 'ChemicalCode', sortable: true },
                { title: 'Chemical Name', field: 'ChemicalName', sortable: true },
                { title: 'Suppliers Code', field: 'SupplierCode', sortable: true },
                { title: 'Quantity', field: 'Quantity', sortable: false },
                { title: 'UOM', field: 'UOM', sortable: false },
                { title: 'Price', field: 'Price', sortable: false },
                { title: 'Status', field: 'Status', sortable: true },
                { tmpl: '<span class="material-icons gj-cursor-pointer">edit</span>', align: 'center', events: { 'click': Edit } },
                { tmpl: '<span class="material-icons gj-cursor-pointer">delete</span>', align: 'center', events: { 'click': Delete } }

            ],
            pager: { limit: 5 }
        });

        grid.on('dataBound', function (e, records, totalRecords) {
            alert('dataBound is fired. ' + records.length + ' records are bound to the grid.');
            grid.collapseAll();
            alert('dataBound is fired. ' + records.length + ' records are bound to the gridsssssssss.');
        });

        $grid.on('dataBinding', function () {
            $grid.collapseAll();
        });

    });

**Comment by atatanasov** [comment]
You have to remove the usage of dataBinding event in this case.
Are you using the latest build from https://github.com/atatanasov/gijgo/tree/master/dist/combined?
