### ISSUE TITLE
Remove Text Case Sensitivity of Search (Filter) and Customizing Search Filter

### ISSUE THREAD

**Issue by vibs2006** [atatanasov/gijgo#70]
I need to make Column Filtering Case **Insensitive**

At the moment if I'm searching then its text case is also being taken into consideration. 

Secondly is there any way by which I can customize Text Box for Filter ?

Can I get information about Handling Text Filtering Events?

**Comment by atatanasov** [comment]
We don't support this yet, but we are going to add this soon.
Stay tuned!

**Comment by atatanasov** [comment]
This enhancement is added to the new development version.
Example: https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.Base.column.filter.example.html
Builds: https://github.com/atatanasov/gijgo/tree/master/dist
