### ISSUE TITLE
Bootstrap5

### ISSUE THREAD

**Issue by Dadbod105** [atatanasov/gijgo#701]
Just wanted to reach out and see if there was an estimated date when the new version that works with bootstrap 5 will be rolled out? I saw a comment on a prior post that it was currently being worked on. We are worried we will be forced to upgrade to bootstrap 5 in the near future.

**Comment by atatanasov** [comment]
We are planning to release Bootstrap 5 integration yearly next year.

**Comment by atatanasov** [comment]
We just release a new version where we support Bootstrap 5. You can see an example at https://gijgo.com/datepicker/example/bootstrap-5
