### ISSUE TITLE
disable top level nodes option

### ISSUE THREAD

**Issue by catadedu** [atatanasov/gijgo#71]
Not really a bug, more of a feature, nice to have though.
I'm referring to the possibility of disabling selection on top level nodes.
Many other libraries have that.
Use case would be using more refined search criteria in a search page by checking more specific (non top level) .

**Comment by atatanasov** [comment]
Could you show me some examples from other libraries that support this option. We can add this in our future development plans if needed.

**Comment by atatanasov** [comment]
We added disable and enable methods for the tree in the new development version.
Here is the example: https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Base.disable.Sample.html
https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Base.disable.Enable.Disable.All.html
