### ISSUE TITLE
Tree Issues: What am I missing?

### ISSUE THREAD

**Issue by Mashiane** [atatanasov/gijgo#716]
Hi

I am getting this errow when using the modular files.

![image](https://user-images.githubusercontent.com/5799306/211312089-8cb0e80b-8f6c-44a6-b51f-c9757a91c43b.png)

I have includes these files on my webapp via the script tag.

core.min.css
checkbox.min.css
tree.min.css
core.min.js
draggable.min.js
droppable.min.js
checkbox.min.js
tree.min.js

Adding these files only there are no issues..

gijgo.min.js
gijgo.min.css

**Comment by atatanasov** [comment]
Hi,

Could you create a sample in jsfiddle.net or similar IDE where you can show me the problem.

Regards,
Atanas

**Comment by Mashiane** [comment]
Can you help with unpkg links fo the modular files please, the normal files work. I will reproduce from this..
https://jsfiddle.net/2n1vp954/

**Comment by atatanasov** [comment]
Your example works just with core.js and tree.js. You can find working version at https://jsfiddle.net/atatanasov/ecru6nbp/4/

**Comment by atatanasov** [comment]
I have no idea why we have this issue with jsfiddle. I was able to build it here https://gijgo.com/Temp/5b496fe0-f961-4610-a623-face682e4370.html

**Comment by Mashiane** [comment]
Thanks to much, I can safely confirm that the version of the files in your example work perfectly without hurdles.

The modular ones on the repo itself for some reason, dont.
