### ISSUE TITLE
grid.on not firing

### ISSUE THREAD

**Issue by mvmvishal** [atatanasov/gijgo#73]
I am working on asp.net, and my code is similar to this.

**<!DOCTYPE html>
<html>
<head>
    <title>Manage Ajax Sourced Data With Grid</title>
    <meta charset="utf-8" />
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="http://code.gijgo.com/1.3.0/js/gijgo.js" type="text/javascript"></script>
    <link href="http://code.gijgo.com/1.3.0/css/gijgo.css" rel="stylesheet" type="text/css" />
    <link href="http://code.gijgo.com/1.3.0/css/demo.css" rel="stylesheet" type="text/css" />
</head>
<body>
 <table id="grid"></table>
 <script>
     var grid = $('#grid').grid({
         dataSource: [{ "ID": "1", "Name": "ddd", "PlaceOfBirth": "ddd", "Bulgarian": "ddd"}],
         columns: [ { field: 'ID' }, { field: 'Name' }, { field: 'PlaceOfBirth' }, { field: 'Bulgarian', title: 'Is Bulgarian?' } ]
     });
     grid.on('cellDataBound', function (e, $displayEl, id, column, record) {
         alert("s");
         if ('ddd' === column.field) {
             $displayEl.text(record.PlaceOfBirth.indexOf('Bulgaria') > -1 ? 'Yes' : 'No');
         }
     });
 </script>
</body>
</html>**

The datasource is ajax returned value and after which JSON.parse has been used on the response. In this case the grid.on event is not firing. Please let me know what changes has to be done?

Regards

M V M

**Comment by atatanasov** [comment]
Please use our ASP.NET examples in order to build your page. You can download them at https://github.com/atatanasov/gijgo-asp-net-examples/releases

You can also see our code at https://github.com/atatanasov/gijgo-asp-net-examples
