### ISSUE TITLE
Grid - notFoundText

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#74]
The text for this option should be managed in the i18n-files.

**Comment by atatanasov** [comment]
I agree. I will add this to the new version. Thanks for the feedback.

**Comment by atatanasov** [comment]
We added this to our new version. You can see an example at https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.Base.notFoundText.localization.html

Thanks again for the feedback.
