### ISSUE TITLE
Issue With Pagination

### ISSUE THREAD

**Issue by nafeesaslam** [atatanasov/gijgo#75]
![grids inline edit delete](https://cloud.githubusercontent.com/assets/11805585/25483721/aebd737e-2b74-11e7-9b81-12b1a1c0a35d.png)
I set pager limit up to 5 rows per page. But all the rows are displayed in single page.
Extra: Pager's next and previous icons also broken.Sorting is set to true but not working .
note: I am working with php

**Comment by atatanasov** [comment]
If you use remote dataSource you need to handle the paging and sorting with code on the server side.
You can see how we do that for asp.net in our examples at https://github.com/atatanasov/gijgo-asp-net-examples
