### ISSUE TITLE
Dialog - titel

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#76]
It would be very helpful, to change the titel as paramater in the open method. (e.g. dialog.open("Add record" / dialog.open("Edit record")

**Comment by atatanasov** [comment]
I agree. I will add this option in the future version.

**Comment by stvowi** [comment]
Please implement this feature as soon as possible.

**Comment by atatanasov** [comment]
We added this feature in the new development version. You can find the new build at the "dist" folder

**Comment by stvowi** [comment]
Thanks!!

**Comment by vinod408** [comment]
can we have example how to use dist for title

**Comment by atatanasov** [comment]
http://gijgo.com/dialog/configuration/title
http://gijgo.com/dialog/methods/open
