### ISSUE TITLE
Dialog - dataSource option

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#77]
It would be nice to define/ set the content of the body container via ajax remote call/ html-string.

The dataSource option be also changeable via open method.

**Comment by atatanasov** [comment]
I will think about it and may add it in future versions.
Right now you can initiate an ajax call on open on initialized events in order to populate the body with remote call.

**Comment by stvowi** [comment]
I'm consider me as beginner in javascript.
Can you give an example how I can load html content via ajax in the dialog body with ID as parameter?

**Comment by stvowi** [comment]
I see at the moment no easy way to set the content of the body after the initialisation of the dialog.

**Comment by atatanasov** [comment]
Hi Stefan,

We added new method in the new development version called 'content'. You can use this method in a combination with initialized event in order to easily manage the dialog content via ajax calls.

Here is an example: http://gijgo.com/Temp/49ff3f7f-1353-47dd-81b3-d8ddc3860c4a.html

Here is the sample code:

```
<!DOCTYPE html>
<html>
<head>
    <title>jQuery Dialog</title>
    <meta charset="utf-8" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="http://code.gijgo.com/1.6.0/js/gijgo.js" type="text/javascript"></script>
    <link href="http://code.gijgo.com/1.6.0/css/gijgo.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="dialog" title="jQuery Dialog" width="400"></div>
    <script type="text/javascript">
        var dialog;
        $(document).ready(function () {
            dialog = $("#dialog").dialog({
                initialized: function() {
                  $.ajax({ url: '/Players/Get' }).done(function (result) {
                    dialog.content('<b>' + result.records[0].Name + '</b>');
                  });
                }
            });
        });
    </script>
</body>
</html>

```

**Comment by stvowi** [comment]
okay, thanks...
This solution is universal.
