### ISSUE TITLE
Dialog - scrollable body

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#78]
There should be the possibility to switch on a scrollbar for the body div if the content is to large.

(Scenario: the form fit in the dialog but the validation messages &  the forms is to big (high) for the body content)

**Comment by atatanasov** [comment]
I agree. This is going to be nice and usefull feature. I will add it in future versions. Thanks for the feedback.

**Comment by stvowi** [comment]
Please implement this feature as soon as possible.

**Comment by atatanasov** [comment]
We added scrollable configuration option for the dialog. You can see some examples at:
https://github.com/atatanasov/gijgo/blob/master/examples/dialog/Dialog.Base.scrollable.Bootstrap.3.html
https://github.com/atatanasov/gijgo/blob/master/examples/dialog/Dialog.Base.scrollable.Bootstrap.4.html
https://github.com/atatanasov/gijgo/blob/master/examples/dialog/Dialog.Base.scrollable.Material.Design.html

**Comment by stvowi** [comment]
Great! Thanks!
