### ISSUE TITLE
headerFilter bug

### ISSUE THREAD

**Issue by ata-amini** [atatanasov/gijgo#79]
In grid.js:5951 (dev version) **onenterkeypress** has no effect

it should be like this:

                        if(data.headerFilter.type === 'onenterkeypress') {
                            $ctrl.on('keypress', function (e) {
                                if (e.which == 13) {
                                    gj.grid.plugins.headerFilter.private.reload($grid, $(this));
                                }
                            });
                        }else {
                            $ctrl.on('blur', function (e) {
                                gj.grid.plugins.headerFilter.private.reload($grid, $(this));
                            });
                        }
                    }

thanks

**Comment by atatanasov** [comment]
Everything looks good in our examples at http://gijgo.com/grid/Configuration/headerFilter.type
Could you reopen the ticket if you setup an example when I can recreate this issue.
