### ISSUE TITLE
Table Footer overlaps columns/controls layout

### ISSUE THREAD

**Issue by MikeGitIt** [atatanasov/gijgo#8]
![image](https://cloud.githubusercontent.com/assets/2125656/13931101/228e8ea8-ef78-11e5-9611-3d758ad3599c.png)

**Comment by atatanasov** [comment]
That was an issue with version 0.6.0. Are you using 0.6.0? Could you upgrade to latest version - 0.6.2.

**Comment by MikeGitIt** [comment]
The grid.js version was not in sync with the grid.css version i.e., the css file was newer than the js file. Once I made the correction, the grid worked as expected. Thanks!
