### ISSUE TITLE
Grid - detailTemplate

### ISSUE THREAD

**Issue by KalyaniDev** [atatanasov/gijgo#81]
Hi, 
New to Gijgo grid. Need some help with the detailTemplate feature. 
Field values of my grid are json. sample-

{"header": {"active": 1, "deal_id": 34345, "regions": [1], "brand_id": 10041, "comments": "test header comments", "segments": [{"channels": [{"channel_id": 970}], "segment_id": 10000090}], "agency_id": 26606, "executive_id": 3, "target_group": 5, "id": 10084, "campaign_name": "order", "type": 1, "cdate": "2000-10-08T11:32:09+05:30", "agency": "343545", "date": "2017-06-08T11:32:09+05:30", "date": "2017-07-08T11:32:09+05:59"}, "order_line": [{"tvr": 0.5, "cprp": 1000, "zone": "A1", "reach": 100, "active": 1, "regions": [1], "description": "mon-fri", "id": 123456, "id": 1, spot": 1000, "duration": 20, "line_id": 9999, "details": [{"spots": [{"date": "2000-08-20T11:32:09+05:30", "count": 1, "spot_details": [{"id": 121, "spot_status": "U", "position": 1}]}], "comments": "test order line comments", "end_time": 10800, "channel_id": 970, "segment_id": 10000090, "start_time": 9000, "spot_type_id": 3, "week_end_date": "2000-09-08T11:32:09+05:30", "week_start_date": "2000-09-08T11:32:09+05:30", status": "test status"}]}]}

When the detailtemplate is expanded for the first time json is shown with out any issues. But when expanded from second time onwards without browser refresh, part of the text from json is being chopped as shown below.

], "segment_id": 10000090}], "agency_id": 26606, "executive_id": 3, "target_group": 5, "id": 10084, "campaign_name": "order", "type": 1, "cdate": "2000-10-08T11:32:09+05:30", "agency": "343545", "date": "2017-06-08T11:32:09+05:30", "date": "2017-07-08T11:32:09+05:59"}, "order_line": [{"tvr": 0.5, "cprp": 1000, "zone": "A1", "reach": 100, "active": 1, "regions": [1], "description": "mon-fri", "id": 123456, "id": 1, spot": 1000, "duration": 20, "line_id": 9999, "details": [{"spots": [{"date": "2000-08-20T11:32:09+05:30", "count": 1, "spot_details": [{"id": 121, "spot_status": "U", "position": 1}]}], "comments": "test order line comments", "end_time": 10800, "channel_id": 970, "segment_id": 10000090, "start_time": 9000, "spot_type_id": 3, "week_end_date": "2000-09-08T11:32:09+05:30", "week_start_date": "2000-09-08T11:32:09+05:30", status": "test status"}]}]}

Any pointers to resolve this will be of great help. 
Thanks.

**Comment by KalyaniDev** [comment]
Looks like my question is a duplicate of #61. Will try out column renderer to see if helps.

**Comment by atatanasov** [comment]
Could you recreate the issue in sites like jsfiddle.net or codepen.io and send me the link to see that is going on.

**Comment by KalyaniDev** [comment]
For now, I have used detailExpand event and it works. Will try to create the link and share for further investigation.

**Comment by atatanasov** [comment]
ok. Thanks. I will close the ticket. Please reopen it if you can provide example and replication steps
