### ISSUE TITLE
Grid - Enhancement

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#84]
I prefer to work with the ajax datasource.
I have to display the sum of the values of an colum at the end of the grid (footer).

Is there an easy solution?

**Comment by atatanasov** [comment]
You can use dataBound event in order to attach summary in the grid.
This is a simple example:
```
<table id="grid"></table>
 <script>
     var grid = $('#grid').grid({
         dataSource: '/Players/Get',
         columns: [ { field: 'ID' }, { field: 'Name' }, { field: 'PlaceOfBirth' } ],
       pager: {limit: 5}
     });
     grid.on('dataBound', function (e, records, totalRecords) {
         var sum = 0, $tfoot;
         $.each(records, function() {
           sum += this.ID;
         });
         $tfoot = grid.children('tfoot');
         $tfoot.children('tr[data-role="summary"]').remove();
         $tfoot.prepend('<tr data-role="summary"><th>'+sum+'</th><th></th><th></th></tr>');
     });
 </script>
```

**Comment by stvowi** [comment]
Thanks! How about it to have a method to set the footer content?

**Comment by code35net** [comment]
> You can use dataBound event in order to attach summary in the grid.
> This is a simple example:
> 
> ```
> <table id="grid"></table>
>  <script>
>      var grid = $('#grid').grid({
>          dataSource: '/Players/Get',
>          columns: [ { field: 'ID' }, { field: 'Name' }, { field: 'PlaceOfBirth' } ],
>        pager: {limit: 5}
>      });
>      grid.on('dataBound', function (e, records, totalRecords) {
>          var sum = 0, $tfoot;
>          $.each(records, function() {
>            sum += this.ID;
>          });
>          $tfoot = grid.children('tfoot');
>          $tfoot.children('tr[data-role="summary"]').remove();
>          $tfoot.prepend('<tr data-role="summary"><th>'+sum+'</th><th></th><th></th></tr>');
>      });
>  </script>
> ```

not working
