### ISSUE TITLE
grid - detailTemplate

### ISSUE THREAD

**Issue by stvowi** [atatanasov/gijgo#87]
The icons for switch on/ off the detail view should be a arrows (arrow right/ down...like accordion style).

Reason:

You have the same "plus / minus" icons by "grouping" and by the display of sub grids.
It's more usere friendly to show a difference.

**Comment by atatanasov** [comment]
Thanks for the recommendation. I will fix that in the new version.

**Comment by atatanasov** [comment]
Hello,
This is improved in the latest development build. You can find the build at https://github.com/atatanasov/gijgo/tree/master/dist

You can see an example about this at https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.Grouping.grouping.groupBy.Bootstrap.3.html
