### ISSUE TITLE
Tree - column option

### ISSUE THREAD

**Issue by allenz0810** [atatanasov/gijgo#88]
Is it possible to have a ColumnNum option under Tree's Configuration.  

For more detail please see example image.

![example](https://cloud.githubusercontent.com/assets/5561722/26424796/6e2fdf18-40a0-11e7-8fca-d1b25b6d8e54.png)

**Comment by atatanasov** [comment]
Do you want to achieve something like this?
![col-num](https://cloud.githubusercontent.com/assets/11516772/26446312/34ef0d26-414c-11e7-965d-25081d286212.PNG)

**Comment by allenz0810** [comment]
@atatanasov  it works as the layout you mention, but is it a way to let users know which one did they checked or how many did checked when this layout collapsed.

**Comment by atatanasov** [comment]
I'm still not sure what you need to have as configuration option. Could you give me more details and examples.

**Comment by atatanasov** [comment]
I will close this ticket for now. Please reopen it if you can provide more details and make it more clear.
