### ISSUE TITLE
i missing edit method

### ISSUE THREAD

**Issue by x-ercise** [atatanasov/gijgo#89]
grid.edit(key);
as gijgo-combined-1.3.1

**Comment by atatanasov** [comment]
You can see in the following examples that the edit method is working as expected:
http://gijgo.com/Temp/5438638f-02a3-49a4-81bd-ecfce6f299ff.html
http://gijgo.com/grid/methods/edit

**Comment by x-ercise** [comment]
Thank you, atatanasov
