### ISSUE TITLE
on column's checkbox in edit mode, the grid change type to textbox

### ISSUE THREAD

**Issue by x-ercise** [atatanasov/gijgo#90]
i define the column template like these
{ hidden: false, editor: true, sortable: false, field: 'R53', title: '5.3', align: 'center', width: 30, type: 'checkbox' },

**Comment by x-ercise** [comment]
1. only support **uiLibrary: 'bootstrap'**, other else always show black color insteal checkbox place.
2. initial grid config as **inlineEditing: { mode: 'command', managementColumn: false }** 
and column as **{ field: 'R53', title: '5.2', type:'checkbox', editor: true, width: 37, align: 'center' }**, let step follow me
     2.1 click on edit command button in the row.
     2.2 and click for change state of checkbox and click update command button.
     2.3 call getChanges() outsite grid (assume as save button or submit) to get what's changed
     2.4 it still have checked state on checkbox, although re-step again.

Regards

**Comment by atatanasov** [comment]
We are still working on the inline editing in the new version, but we already fixed that bug.
You can see an example at:
https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.InlineEditing.column.editor.sample.html

The build in development from the new version is located at https://github.com/atatanasov/gijgo/tree/master/dist

I think that we will be able to release a stable build of the new version in early June

**Comment by x-ercise** [comment]
good sound, i hope it's for the best tool, thank
