### ISSUE TITLE
Change the "loading" message in the location file.

### ISSUE THREAD

**Issue by luizAzevedo** [atatanasov/gijgo#92]
It would be interesting to be able to change the "loading" message in the location file, what do you think?
Thank you.

**Comment by atatanasov** [comment]
You can do that. You can use the following example:
https://github.com/atatanasov/gijgo/blob/master/examples/grid/Grid.Base.locale.French.MaterialDesign.Custom.html

You just need to use .Loading instead of gj.grid.messages['fr-fr'].DisplayingRecords
