### ISSUE TITLE
tree option: checkboxes not automatically checking subnodes when selecting group

### ISSUE THREAD

**Issue by omsiqveland** [atatanasov/gijgo#93]
Currently, if I select a checkbox on a group it also selects all subnodes of that group. Additionally, if I check all subnodes of a group the parent-group is checked. This is fine, however, it would be great to have the possibility of disabling it. Such that checking a checkbox does not affect any other checkbox.

I'm working on a project where i want to compare data referred by items in the tree versus each other by selecting them using checkboxes. I also want to compare subnodes with its parent group node, hence I would like to be able to "check" subnodes and groupnodes individually.

**Comment by atatanasov** [comment]
Thanks for the feedback. We don't support this feature right now, but we are going to add it in future versions.

**Comment by atatanasov** [comment]
We added this option in the new version that is development right now. You can find the new builds at https://github.com/atatanasov/gijgo/tree/master/dist

You can see a demo of this feature at https://github.com/atatanasov/gijgo/blob/master/examples/tree/Tree.Checkboxes.cascadeCheck.False.html
