### ISSUE TITLE
Grid first row replaced with second row when updating

### ISSUE THREAD

**Issue by ikumshyamal** [atatanasov/gijgo#96]
I used following steps,
1. I added 3 records using addRow method
2. Clicking on first row, filled first row data to controls
3. After edit data, updated the first row
4. Then clicking on second row, filled second row data to controls
5. After edit data, update the row
(Rows updated using updateRow method.)

this replaced the first row data with second row.

I think the reason is first row e.data.id changed to 2 when updating the first row

[Detail.zip](https://github.com/atatanasov/gijgo/files/1048746/Detail.zip)

**Comment by atatanasov** [comment]
Hello,

I think that this will be resolved if you follow our example at http://gijgo.com/grid/demos/javascript-sourced-data and use a primaryKey configuration option for your grid. In your case the promaryKey needs to be set to primaryKey: 'id'

http://gijgo.com/grid/configuration/primaryKey

**Comment by ikumshyamal** [comment]
This is not fix. I checked in your sample it is also happening on that too…

Followed the below steps

1. Removed all the records in the grid
2. Added 3 new records
3. Clicked on edit in first record, don’t change anything and just save
4. Clicked on edit in second record and followed above steps

Then you can see what’s going on….
