### ISSUE TITLE
Tree drag'n'drop for sorting

### ISSUE THREAD

**Issue by hxss** [atatanasov/gijgo#99]
Hello. Thx for your widget.
How I can change sort order of child in node?
E.g. when I try move Mexico higher then Canada - Mexico drops into Canada or into USA
http://gijgo.com/tree/demos/treeview-drag-and-drop

**Comment by atatanasov** [comment]
This is supported. The easiest way to do this is to move the mouse on the left side of the item. You have to see line above or below the node in order to reorder tree items.

**Comment by hxss** [comment]
Got it. Thx

**Comment by PPT150818** [comment]
How I can change sort order of parent nodes in tree? Frontend its showing but in backend its not updating accordingly.
